Repository akaunting/akaunting, pull requests merged in 2018-11, with the labels that each got.

#576 Added filters to reports
  app/Http/Controllers/Reports/ExpenseSummary.php
  app/Http/Controllers/Reports/IncomeExpenseSummary.php
  app/Http/Controllers/Reports/IncomeSummary.php
  app/Http/Controllers/Reports/ProfitLoss.php
  app/Http/Controllers/Reports/TaxSummary.php
  app/Models/Model.php
  app/Traits/DateTime.php
  public/css/app.css
  resources/views/reports/expense_summary/body.blade.php
  resources/views/reports/expense_summary/index.blade.php
  resources/views/reports/income_expense_summary/index.blade.php
  resources/views/reports/income_summary/body.blade.php
  resources/views/reports/income_summary/index.blade.php
  resources/views/reports/profit_loss/index.blade.php
  resources/views/reports/tax_summary/index.blade.php
Labels: Feature

#577 App's page add sliders for screenshots.
  public/css/app.css
  resources/views/modules/item/show.blade.php
Labels: Feature

#579 Added multi-select filters everywhere
  app/Filters/Banking/Reconciliations.php
  app/Filters/Banking/Transactions.php
  app/Filters/Common/Items.php
  app/Filters/Expenses/Bills.php
  app/Filters/Expenses/Payments.php
  app/Filters/Incomes/Invoices.php
  app/Filters/Incomes/Revenues.php
  app/Filters/Settings/Categories.php
  app/Http/Controllers/Banking/Reconciliations.php
  app/Http/Controllers/Banking/Transactions.php
  app/Http/Controllers/Common/Items.php
  app/Http/Controllers/Expenses/Bills.php
  app/Http/Controllers/Expenses/Payments.php
  app/Http/Controllers/Incomes/Invoices.php
  app/Http/Controllers/Incomes/Revenues.php
  app/Http/Controllers/Settings/Categories.php
  resources/views/banking/reconciliations/index.blade.php
  resources/views/banking/transactions/index.blade.php
  resources/views/banking/transfers/index.blade.php
  resources/views/common/items/index.blade.php
  resources/views/expenses/bills/index.blade.php
  resources/views/expenses/payments/index.blade.php
  resources/views/incomes/invoices/index.blade.php
  resources/views/incomes/revenues/index.blade.php
  resources/views/settings/categories/index.blade.php
Labels: Feature

#587 Some request values fixed
  app/Http/Controllers/Incomes/Invoices.php
  tests/Feature/Expenses/BillsTest.php
  tests/Feature/Incomes/InvoicesTest.php
Labels: Feature

#599 Account Test
  tests/Feature/Banking/AccountsTest.php
Labels: Feature

#601 Command to delete a module from console
  app/Console/Commands/ModuleDelete.php
  app/Console/Kernel.php
Labels: Feature

#604 Transfer Test
  tests/Feature/Banking/Transaction.php
  tests/Feature/Banking/TransfersTest.php
Labels: Feature

#619 Serbian (Cyrillic) translation
  config/language.php
  resources/lang/sr-RS/accounts.php
  resources/lang/sr-RS/auth.php
  resources/lang/sr-RS/bills.php
  resources/lang/sr-RS/companies.php
  resources/lang/sr-RS/currencies.php
  resources/lang/sr-RS/customers.php
  resources/lang/sr-RS/dashboard.php
  resources/lang/sr-RS/demo.php
  resources/lang/sr-RS/footer.php
  resources/lang/sr-RS/general.php
  resources/lang/sr-RS/header.php
  resources/lang/sr-RS/import.php
  resources/lang/sr-RS/install.php
  resources/lang/sr-RS/invoices.php
  resources/lang/sr-RS/items.php
  resources/lang/sr-RS/messages.php
  resources/lang/sr-RS/modules.php
  resources/lang/sr-RS/notifications.php
  resources/lang/sr-RS/pagination.php
  resources/lang/sr-RS/passwords.php
  resources/lang/sr-RS/reconciliations.php
  resources/lang/sr-RS/recurring.php
  resources/lang/sr-RS/reports.php
  resources/lang/sr-RS/settings.php
  resources/lang/sr-RS/taxes.php
  resources/lang/sr-RS/transfers.php
  resources/lang/sr-RS/updates.php
  resources/lang/sr-RS/validation.php
Labels: Feature

#627 Updated translations
  resources/lang/de-DE/taxes.php
  resources/lang/es-ES/taxes.php
  resources/lang/it-IT/bills.php
  resources/lang/it-IT/customers.php
  resources/lang/it-IT/general.php
  resources/lang/it-IT/invoices.php
  resources/lang/it-IT/items.php
  resources/lang/it-IT/messages.php
  resources/lang/it-IT/modules.php
  resources/lang/it-IT/reconciliations.php
  resources/lang/it-IT/settings.php
  resources/lang/it-IT/taxes.php
  resources/lang/it-IT/validation.php
  resources/lang/sq-AL/bills.php
  resources/lang/sq-AL/customers.php
  resources/lang/sq-AL/general.php
  resources/lang/sq-AL/invoices.php
  resources/lang/sq-AL/items.php
  resources/lang/sq-AL/messages.php
  resources/lang/sq-AL/modules.php
  resources/lang/sq-AL/reconciliations.php
  resources/lang/sq-AL/settings.php
  resources/lang/sq-AL/taxes.php
  resources/lang/sq-AL/validation.php
  resources/lang/sv-SE/items.php
  resources/lang/sv-SE/taxes.php
  resources/lang/tr-TR/footer.php
  resources/lang/tr-TR/invoices.php
  resources/lang/tr-TR/taxes.php
Labels: Enhancement

#635 #631 Fixed: Add row button on Invoice and Bill
  resources/views/expenses/bills/create.blade.php
  resources/views/expenses/bills/edit.blade.php
  resources/views/incomes/invoices/create.blade.php
Labels: Bug

#636 Updated translations
  resources/lang/el-GR/taxes.php
  resources/lang/fa-IR/bills.php
  resources/lang/fa-IR/customers.php
  resources/lang/fa-IR/import.php
  resources/lang/fa-IR/invoices.php
  resources/lang/fa-IR/modules.php
  resources/lang/fa-IR/reports.php
  resources/lang/fa-IR/settings.php
  resources/lang/fa-IR/taxes.php
  resources/lang/fa-IR/transfers.php
  resources/lang/fa-IR/validation.php
  resources/lang/pt-BR/bills.php
  resources/lang/pt-BR/customers.php
  resources/lang/pt-BR/general.php
  resources/lang/pt-BR/invoices.php
  resources/lang/pt-BR/items.php
  resources/lang/pt-BR/messages.php
  resources/lang/pt-BR/modules.php
  resources/lang/pt-BR/reconciliations.php
  resources/lang/pt-BR/settings.php
  resources/lang/pt-BR/taxes.php
  resources/lang/pt-BR/validation.php
  resources/lang/ru-RU/auth.php
  resources/lang/ru-RU/bills.php
  resources/lang/ru-RU/customers.php
  resources/lang/ru-RU/general.php
  resources/lang/ru-RU/invoices.php
  resources/lang/ru-RU/recurring.php
  resources/lang/ru-RU/taxes.php
  resources/lang/ru-RU/validation.php
  resources/lang/sr-RS/taxes.php
  resources/lang/tr-TR/general.php
Labels: Enhancement

#638 #637 Fixed: Moved popover initialisation to Document ready
  resources/views/expenses/bills/create.blade.php
  resources/views/expenses/bills/edit.blade.php
  resources/views/incomes/invoices/create.blade.php
  resources/views/incomes/invoices/edit.blade.php
Labels: Bug

#646 Link to reports
  app/Http/ViewComposers/All.php
  resources/views/banking/accounts/index.blade.php
  resources/views/common/dashboard/index.blade.php
  resources/views/expenses/vendors/index.blade.php
  resources/views/incomes/customers/index.blade.php
  resources/views/settings/categories/index.blade.php
Labels: Feature

#653 Not checking account currency before changing it
  app/Http/Controllers/Banking/Accounts.php
  app/Http/Controllers/Settings/Currencies.php
  resources/lang/en-GB/messages.php
Labels: Bug, Language Change

#656 Updated translations
  resources/lang/de-DE/general.php
  resources/lang/de-DE/messages.php
  resources/lang/de-DE/reconciliations.php
  resources/lang/de-DE/taxes.php
  resources/lang/it-IT/general.php
  resources/lang/it-IT/messages.php
  resources/lang/it-IT/reconciliations.php
  resources/lang/lt-LT/dashboard.php
  resources/lang/lt-LT/general.php
  resources/lang/lt-LT/messages.php
  resources/lang/lt-LT/reconciliations.php
  resources/lang/lt-LT/settings.php
  resources/lang/lt-LT/taxes.php
  resources/lang/nl-NL/general.php
  resources/lang/nl-NL/invoices.php
  resources/lang/nl-NL/messages.php
  resources/lang/nl-NL/modules.php
  resources/lang/nl-NL/reconciliations.php
  resources/lang/nl-NL/settings.php
  resources/lang/nl-NL/taxes.php
  resources/lang/tr-TR/general.php
  resources/lang/tr-TR/messages.php
  resources/lang/tr-TR/reconciliations.php
Labels: Enhancement
