Repository akaunting/akaunting, pull requests merged in 2018-08, with the labels that each got.

#443 Added developer stacks
  resources/views/layouts/admin.blade.php
  resources/views/layouts/auth.blade.php
  resources/views/layouts/bill.blade.php
  resources/views/layouts/customer.blade.php
  resources/views/layouts/invoice.blade.php
  resources/views/layouts/modules.blade.php
  resources/views/layouts/print.blade.php
  resources/views/partials/admin/content.blade.php
  resources/views/partials/admin/footer.blade.php
  resources/views/partials/admin/head.blade.php
  resources/views/partials/admin/header.blade.php
  resources/views/partials/admin/menu.blade.php
  resources/views/partials/admin/pagination.blade.php
  resources/views/partials/auth/head.blade.php
  resources/views/partials/bill/head.blade.php
  resources/views/partials/customer/content.blade.php
  resources/views/partials/customer/footer.blade.php
  resources/views/partials/customer/head.blade.php
  resources/views/partials/customer/header.blade.php
  resources/views/partials/customer/menu.blade.php
  resources/views/partials/customer/pagination.blade.php
  resources/views/partials/install/head.blade.php
  resources/views/partials/invoice/head.blade.php
  resources/views/partials/modules/head.blade.php
Labels: Enhancement

#445 Latvian translation
  config/language.php
  resources/lang/lv-LV/accounts.php
  resources/lang/lv-LV/auth.php
  resources/lang/lv-LV/bills.php
  resources/lang/lv-LV/companies.php
  resources/lang/lv-LV/currencies.php
  resources/lang/lv-LV/customers.php
  resources/lang/lv-LV/dashboard.php
  resources/lang/lv-LV/demo.php
  resources/lang/lv-LV/footer.php
  resources/lang/lv-LV/general.php
  resources/lang/lv-LV/header.php
  resources/lang/lv-LV/import.php
  resources/lang/lv-LV/install.php
  resources/lang/lv-LV/invoices.php
  resources/lang/lv-LV/items.php
  resources/lang/lv-LV/messages.php
  resources/lang/lv-LV/modules.php
  resources/lang/lv-LV/notifications.php
  resources/lang/lv-LV/pagination.php
  resources/lang/lv-LV/passwords.php
  resources/lang/lv-LV/recurring.php
  resources/lang/lv-LV/reports.php
  resources/lang/lv-LV/settings.php
  resources/lang/lv-LV/taxes.php
  resources/lang/lv-LV/transfers.php
  resources/lang/lv-LV/updates.php
  resources/lang/lv-LV/validation.php
Labels: Feature

#447 Update popover function call method signature
  resources/views/expenses/bills/create.blade.php
  resources/views/expenses/bills/edit.blade.php
  resources/views/incomes/invoices/create.blade.php
  resources/views/incomes/invoices/edit.blade.php
Labels: Enhancement

#459 Banking account edit set always default account
  app/Http/Controllers/Banking/Accounts.php
Labels: Bug

#469 Delete button bug fixed for Turkish language
  resources/views/partials/form/delete_button.blade.php
  resources/views/partials/form/delete_link.blade.php
Labels: Bug

#471 Mass delete relationships
  app/Http/Controllers/Controller.php
  app/Http/Controllers/Expenses/Bills.php
  app/Http/Controllers/Incomes/Invoices.php
Labels: Enhancement
