Repository akaunting/akaunting, pull requests merged in 2018-10, with the labels that each got.

#512 square brackets error and seed option
  app/Listeners/Updates/Version130.php
  database/seeds/Settings.php
Labels: Bug

#514 Updates progress get Core check api token and upload error message is…
  app/Http/Controllers/Install/Updates.php
Labels: Bug

#515 App store vendor's app page added.
  app/Http/Controllers/Modules/Tiles.php
  app/Traits/Modules.php
  resources/views/modules/item/show.blade.php
  routes/web.php
Labels: Feature

#520 refs #517 date rage language text
  resources/lang/en-GB/general.php
  resources/views/partials/form/date_range.blade.php
Labels: Language Change

#533 Slovak translation
  config/language.php
  resources/lang/sk-SK/accounts.php
  resources/lang/sk-SK/auth.php
  resources/lang/sk-SK/bills.php
  resources/lang/sk-SK/companies.php
  resources/lang/sk-SK/currencies.php
  resources/lang/sk-SK/customers.php
  resources/lang/sk-SK/dashboard.php
  resources/lang/sk-SK/demo.php
  resources/lang/sk-SK/footer.php
  resources/lang/sk-SK/general.php
  resources/lang/sk-SK/header.php
  resources/lang/sk-SK/import.php
  resources/lang/sk-SK/install.php
  resources/lang/sk-SK/invoices.php
  resources/lang/sk-SK/items.php
  resources/lang/sk-SK/messages.php
  resources/lang/sk-SK/modules.php
  resources/lang/sk-SK/notifications.php
  resources/lang/sk-SK/pagination.php
  resources/lang/sk-SK/passwords.php
  resources/lang/sk-SK/recurring.php
  resources/lang/sk-SK/reports.php
  resources/lang/sk-SK/settings.php
  resources/lang/sk-SK/taxes.php
  resources/lang/sk-SK/transfers.php
  resources/lang/sk-SK/updates.php
  resources/lang/sk-SK/validation.php
Labels: Feature

#534 Tests for Expenses
  tests/Feature/Expenses/VendorsTest.php
Labels: Feature

#535 Tests for Payments and Revenues
  tests/Feature/Expenses/PaymentsTest.php
  tests/Feature/Incomes/RevenuesTest.php
Labels: Feature

#537 Invoice/Bill: Multiple tax rate
  app/Http/Controllers/Common/Items.php
  app/Http/Controllers/Expenses/Bills.php
  app/Http/Controllers/Incomes/Invoices.php
  resources/lang/en-GB/bills.php
  resources/lang/en-GB/invoices.php
  resources/views/expenses/bills/create.blade.php
  resources/views/expenses/bills/edit.blade.php
  resources/views/incomes/invoices/create.blade.php
  resources/views/incomes/invoices/edit.blade.php
Labels: Feature, Language Change

#538 Adding not paid amount column for customers and vendors
  app/Models/Expense/Vendor.php
  app/Models/Income/Customer.php
  resources/views/expenses/vendors/index.blade.php
  resources/views/incomes/customers/index.blade.php
Labels: Feature

#541 Fix the add payment modal title
  resources/views/modals/invoices/payment.blade.php
Labels: Bug

#542 Translate footer/header links
  resources/lang/en-GB/footer.php
  resources/lang/en-GB/header.php
  resources/views/layouts/auth.blade.php
  resources/views/partials/admin/footer.blade.php
  resources/views/partials/admin/header.blade.php
  resources/views/partials/customer/footer.blade.php
Labels: Enhancement

#544 Show unpaid cloumn in customer/vendor list
  app/Models/Expense/Vendor.php
  app/Models/Income/Customer.php
  resources/views/expenses/vendors/index.blade.php
  resources/views/incomes/customers/index.blade.php
Labels: Enhancement

#546 Forgotten Out of stock reminder input and radioGroup.
  resources/views/settings/settings/edit.blade.php
Labels: Bug

#554 Allow to pay invoice through a unique link
  app/Http/Controllers/Customers/Invoices.php
  app/Http/Controllers/Incomes/Invoices.php
  app/Utilities/Modules.php
  composer.json
  config/app.php
  public/css/app.css
  resources/lang/en-GB/invoices.php
  resources/views/customers/invoices/link.blade.php
  resources/views/incomes/invoices/show.blade.php
  resources/views/layouts/link.blade.php
  resources/views/partials/link/content.blade.php
  resources/views/partials/link/footer.blade.php
  resources/views/partials/link/head.blade.php
  routes/web.php
Labels: Feature, Language Change

#555 Offlinepayment compability invoice unique link feature
  modules/OfflinePayment/Http/Controllers/OfflinePayment.php
  modules/OfflinePayment/Http/routes.php
  modules/OfflinePayment/Resources/views/link.blade.php
Labels: Feature

#556 Paypal compability invoice unique link feature
  modules/PaypalStandard/Http/routes.php
Labels: Feature

#557 Reflect next recurrings to reports
  app/Http/Controllers/Reports/ExpenseSummary.php
  app/Http/Controllers/Reports/IncomeExpenseSummary.php
  app/Http/Controllers/Reports/IncomeSummary.php
Labels: Feature

#559 Invoice customization
  app/Http/Controllers/Settings/Settings.php
  app/Http/ViewComposers/InvoiceText.php
  app/Providers/FormServiceProvider.php
  app/Providers/ViewComposerServiceProvider.php
  resources/lang/en-GB/settings.php
  resources/views/incomes/invoices/create.blade.php
  resources/views/incomes/invoices/edit.blade.php
  resources/views/incomes/invoices/invoice.blade.php
  resources/views/incomes/invoices/show.blade.php
  resources/views/partials/form/invoice_text.blade.php
  resources/views/settings/settings/edit.blade.php
Labels: Feature

#560 Invoice customization fixed some css and js issue
  app/Http/ViewComposers/InvoiceText.php
  public/css/app.css
  public/js/app.js
  resources/lang/en-GB/settings.php
  resources/views/partials/form/invoice_text.blade.php
Labels: Feature

#561 Permission and Role tests
  tests/Feature/Auth/PermissionsTest.php
  tests/Feature/Auth/RolesTest.php
  tests/Feature/Auth/UsersTest.php
Labels: Feature

#565 Invoice/Bill Items: Multiple tax rate
  app/Http/Controllers/Common/Items.php
  app/Http/Controllers/Expenses/Bills.php
  app/Http/Controllers/Incomes/Invoices.php
  app/Http/Controllers/Modals/Taxes.php
  app/Models/Expense/Bill.php
  app/Models/Expense/BillItem.php
  app/Models/Expense/BillItemTax.php
  app/Models/Income/Invoice.php
  app/Models/Income/InvoiceItem.php
  app/Models/Income/InvoiceItemTax.php
  database/migrations/2018_10_22_000000_create_bill_item_taxes_table.php
  database/migrations/2018_10_22_000000_create_invoice_item_taxes_table.php
  public/css/app.css
  resources/lang/en-GB/bills.php
  resources/lang/en-GB/invoices.php
  resources/views/expenses/bills/create.blade.php
  resources/views/expenses/bills/edit.blade.php
  resources/views/expenses/bills/item.blade.php
  resources/views/incomes/invoices/create.blade.php
  resources/views/incomes/invoices/edit.blade.php
  resources/views/incomes/invoices/item.blade.php
  resources/views/modals/taxes/create.blade.php
  routes/web.php
Labels: Feature

#567 Wizard
  app/Events/AdminMenuCreated.php
  app/Events/BillCreated.php
  app/Events/BillUpdated.php
  app/Events/CompanySwitched.php
  app/Events/CustomerMenuCreated.php
  app/Events/InvoiceCreated.php
  app/Events/InvoicePrinting.php
  app/Events/InvoiceUpdated.php
  app/Events/ModuleInstalled.php
  app/Events/UpdateFinished.php
  app/Http/Controllers/Auth/Login.php
  app/Http/Controllers/Common/Companies.php
  app/Http/Controllers/Wizard/Companies.php
  app/Http/Controllers/Wizard/Currencies.php
  app/Http/Controllers/Wizard/Finish.php
  app/Http/Controllers/Wizard/Taxes.php
  app/Http/Kernel.php
  app/Http/Middleware/AdminMenu.php
  app/Http/Requests/Wizard/Company.php
  app/Listeners/Updates/Version130.php
  app/Providers/ViewComposerServiceProvider.php
  app/Traits/Modules.php
  app/Utilities/Installer.php
  database/seeds/Roles.php
  database/seeds/Settings.php
  public/css/app.css
  public/js/app.js
  resources/lang/en-GB/general.php
  resources/lang/en-GB/modules.php
  resources/views/layouts/wizard.blade.php
  resources/views/partials/wizard/content.blade.php
  resources/views/partials/wizard/head.blade.php
  resources/views/partials/wizard/pagination.blade.php
  resources/views/settings/settings/edit.blade.php
  resources/views/wizard/companies/edit.blade.php
  resources/views/wizard/currencies/create.blade.php
  resources/views/wizard/currencies/edit.blade.php
  resources/views/wizard/currencies/index.blade.php
  resources/views/wizard/finish/index.blade.php
  resources/views/wizard/taxes/create.blade.php
  resources/views/wizard/taxes/edit.blade.php
  resources/views/wizard/taxes/index.blade.php
  routes/web.php
Labels: Feature, Language Change

#568 Lithuanian translation
  config/language.php
  resources/lang/lt-LT/accounts.php
  resources/lang/lt-LT/auth.php
  resources/lang/lt-LT/bills.php
  resources/lang/lt-LT/companies.php
  resources/lang/lt-LT/currencies.php
  resources/lang/lt-LT/customers.php
  resources/lang/lt-LT/dashboard.php
  resources/lang/lt-LT/demo.php
  resources/lang/lt-LT/footer.php
  resources/lang/lt-LT/general.php
  resources/lang/lt-LT/header.php
  resources/lang/lt-LT/import.php
  resources/lang/lt-LT/install.php
  resources/lang/lt-LT/invoices.php
  resources/lang/lt-LT/items.php
  resources/lang/lt-LT/messages.php
  resources/lang/lt-LT/modules.php
  resources/lang/lt-LT/notifications.php
  resources/lang/lt-LT/pagination.php
  resources/lang/lt-LT/passwords.php
  resources/lang/lt-LT/recurring.php
  resources/lang/lt-LT/reports.php
  resources/lang/lt-LT/settings.php
  resources/lang/lt-LT/taxes.php
  resources/lang/lt-LT/transfers.php
  resources/lang/lt-LT/updates.php
  resources/lang/lt-LT/validation.php
Labels: Feature

#570 Bills Test
  tests/Feature/Expenses/BillsTest.php
Labels: Feature

#573 Wizard on Invoice and Bill work flow
  app/Http/Controllers/Expenses/Bills.php
  public/css/app.css
  resources/lang/en-GB/bills.php
  resources/lang/en-GB/general.php
  resources/lang/en-GB/invoices.php
  resources/views/expenses/bills/show.blade.php
  resources/views/incomes/invoices/show.blade.php
Labels: Feature, Language Change

#574 Invoice Test
  tests/Feature/Incomes/InvoicesTest.php
Labels: Feature
