Repository akaunting/akaunting, pull requests merged in 2018-05, with the labels that each got.

#332 Romanian translation
  config/language.php
  resources/lang/ro-RO/accounts.php
  resources/lang/ro-RO/auth.php
  resources/lang/ro-RO/bills.php
  resources/lang/ro-RO/companies.php
  resources/lang/ro-RO/currencies.php
  resources/lang/ro-RO/customers.php
  resources/lang/ro-RO/dashboard.php
  resources/lang/ro-RO/demo.php
  resources/lang/ro-RO/footer.php
  resources/lang/ro-RO/general.php
  resources/lang/ro-RO/header.php
  resources/lang/ro-RO/import.php
  resources/lang/ro-RO/install.php
  resources/lang/ro-RO/invoices.php
  resources/lang/ro-RO/items.php
  resources/lang/ro-RO/messages.php
  resources/lang/ro-RO/modules.php
  resources/lang/ro-RO/pagination.php
  resources/lang/ro-RO/passwords.php
  resources/lang/ro-RO/recurring.php
  resources/lang/ro-RO/reports.php
  resources/lang/ro-RO/settings.php
  resources/lang/ro-RO/taxes.php
  resources/lang/ro-RO/transfers.php
  resources/lang/ro-RO/updates.php
  resources/lang/ro-RO/validation.php
Labels: Feature

#343 Thai translation
  config/language.php
  resources/lang/th-TH/accounts.php
  resources/lang/th-TH/auth.php
  resources/lang/th-TH/bills.php
  resources/lang/th-TH/companies.php
  resources/lang/th-TH/currencies.php
  resources/lang/th-TH/customers.php
  resources/lang/th-TH/dashboard.php
  resources/lang/th-TH/demo.php
  resources/lang/th-TH/footer.php
  resources/lang/th-TH/general.php
  resources/lang/th-TH/header.php
  resources/lang/th-TH/import.php
  resources/lang/th-TH/install.php
  resources/lang/th-TH/invoices.php
  resources/lang/th-TH/items.php
  resources/lang/th-TH/messages.php
  resources/lang/th-TH/modules.php
  resources/lang/th-TH/pagination.php
  resources/lang/th-TH/passwords.php
  resources/lang/th-TH/recurring.php
  resources/lang/th-TH/reports.php
  resources/lang/th-TH/settings.php
  resources/lang/th-TH/taxes.php
  resources/lang/th-TH/transfers.php
  resources/lang/th-TH/updates.php
  resources/lang/th-TH/validation.php
Labels: Feature

#348 Password reset not multilingual
  app/Notifications/Auth/Reset.php
  resources/lang/en-GB/auth.php
Labels: Bug

#356 Added Suggestion module on pages
  app/Http/ViewComposers/Header.php
  app/Http/ViewComposers/Suggestions.php
  app/Providers/ViewComposerServiceProvider.php
  app/Traits/Modules.php
  app/Traits/SiteApi.php
  app/Utilities/Updater.php
Labels: Feature

#353 Docker env update
  Dockerfile
  README.md
  docker-compose.yml
  docker/docker-compose.build.yaml
Labels: Enhancement
