Repository akaunting/akaunting, pull requests merged in 2018-04, with the labels that each got.

#287 Print Reports
  app/Http/Controllers/Reports/ExpenseSummary.php
  app/Http/Controllers/Reports/IncomeExpenseSummary.php
  app/Http/Controllers/Reports/IncomeSummary.php
  public/css/app.css
  resources/views/layouts/print.blade.php
  resources/views/reports/expense_summary/body.blade.php
  resources/views/reports/expense_summary/index.blade.php
  resources/views/reports/expense_summary/print.blade.php
  resources/views/reports/income_expense_summary/body.blade.php
  resources/views/reports/income_expense_summary/index.blade.php
  resources/views/reports/income_expense_summary/print.blade.php
  resources/views/reports/income_summary/body.blade.php
  resources/views/reports/income_summary/index.blade.php
  resources/views/reports/income_summary/print.blade.php
  resources/views/vendor/consoletvs/charts/chartjs/multi/line_print.blade.php
Labels: Feature

#291 Search items by SKU in invoice/bill
  app/Http/Controllers/Api/Expenses/Bills.php
  app/Http/Controllers/Api/Incomes/Invoices.php
  app/Http/Controllers/Expenses/Bills.php
  app/Http/Controllers/Incomes/Invoices.php
  app/Http/Controllers/Items/Items.php
  app/Models/Item/Item.php
  resources/views/expenses/bills/create.blade.php
  resources/views/expenses/bills/edit.blade.php
  resources/views/incomes/invoices/create.blade.php
  resources/views/incomes/invoices/edit.blade.php
Labels: Feature

#294 Bulgarian translation
  composer.lock
  config/language.php
  resources/lang/bg-BG/accounts.php
  resources/lang/bg-BG/auth.php
  resources/lang/bg-BG/bills.php
  resources/lang/bg-BG/companies.php
  resources/lang/bg-BG/currencies.php
  resources/lang/bg-BG/customers.php
  resources/lang/bg-BG/dashboard.php
  resources/lang/bg-BG/demo.php
  resources/lang/bg-BG/footer.php
  resources/lang/bg-BG/general.php
  resources/lang/bg-BG/header.php
  resources/lang/bg-BG/import.php
  resources/lang/bg-BG/install.php
  resources/lang/bg-BG/invoices.php
  resources/lang/bg-BG/items.php
  resources/lang/bg-BG/messages.php
  resources/lang/bg-BG/modules.php
  resources/lang/bg-BG/pagination.php
  resources/lang/bg-BG/passwords.php
  resources/lang/bg-BG/reports.php
  resources/lang/bg-BG/settings.php
  resources/lang/bg-BG/taxes.php
  resources/lang/bg-BG/transfers.php
  resources/lang/bg-BG/updates.php
  resources/lang/bg-BG/validation.php
Labels: Feature

#298 Updated rules so rate must be between 0 and 100
  app/Http/Requests/Setting/Tax.php
Labels: Enhancement

#303 Greek translation
  config/language.php
  resources/lang/el-GR/accounts.php
  resources/lang/el-GR/auth.php
  resources/lang/el-GR/bills.php
  resources/lang/el-GR/companies.php
  resources/lang/el-GR/currencies.php
  resources/lang/el-GR/customers.php
  resources/lang/el-GR/dashboard.php
  resources/lang/el-GR/demo.php
  resources/lang/el-GR/footer.php
  resources/lang/el-GR/general.php
  resources/lang/el-GR/header.php
  resources/lang/el-GR/import.php
  resources/lang/el-GR/install.php
  resources/lang/el-GR/invoices.php
  resources/lang/el-GR/items.php
  resources/lang/el-GR/messages.php
  resources/lang/el-GR/modules.php
  resources/lang/el-GR/pagination.php
  resources/lang/el-GR/passwords.php
  resources/lang/el-GR/reports.php
  resources/lang/el-GR/settings.php
  resources/lang/el-GR/taxes.php
  resources/lang/el-GR/transfers.php
  resources/lang/el-GR/updates.php
  resources/lang/el-GR/validation.php
Labels: Feature

#306 Change API token of App Store
  resources/views/modules/home/index.blade.php
  resources/views/modules/item/show.blade.php
  resources/views/modules/tiles/index.blade.php
  resources/views/modules/token/create.blade.php
Labels: Enhancement

#307 App store token verification
  app/Http/Requests/Module/Module.php
  app/Traits/Modules.php
  resources/lang/en-GB/modules.php
Labels: Enhancement, Language Change

#308 App Store search issue solved
  app/Http/Controllers/Modules/Tiles.php
  app/Traits/Modules.php
  resources/lang/en-GB/modules.php
  resources/views/partials/modules/bar.blade.php
  routes/web.php
Labels: Bug, Enhancement, Language Change

#310 App store app price style change
  app/Traits/Modules.php
  resources/views/modules/item/show.blade.php
  resources/views/partials/modules/item.blade.php
Labels: Enhancement

#311 Payment, Revenue account and currency input combination
  public/css/app.css
  resources/views/expenses/payments/create.blade.php
  resources/views/expenses/payments/edit.blade.php
  resources/views/incomes/revenues/create.blade.php
  resources/views/incomes/revenues/edit.blade.php
Labels: Enhancement

#312 refs payment, revenue style
  public/css/app.css
  resources/views/expenses/payments/create.blade.php
  resources/views/expenses/payments/edit.blade.php
  resources/views/incomes/revenues/create.blade.php
  resources/views/incomes/revenues/edit.blade.php
Labels: Enhancement

#314 Ukrainian translation
  config/language.php
  resources/lang/uk-UA/accounts.php
  resources/lang/uk-UA/auth.php
  resources/lang/uk-UA/bills.php
  resources/lang/uk-UA/companies.php
  resources/lang/uk-UA/currencies.php
  resources/lang/uk-UA/customers.php
  resources/lang/uk-UA/dashboard.php
  resources/lang/uk-UA/demo.php
  resources/lang/uk-UA/footer.php
  resources/lang/uk-UA/general.php
  resources/lang/uk-UA/header.php
  resources/lang/uk-UA/import.php
  resources/lang/uk-UA/install.php
  resources/lang/uk-UA/invoices.php
  resources/lang/uk-UA/items.php
  resources/lang/uk-UA/messages.php
  resources/lang/uk-UA/modules.php
  resources/lang/uk-UA/pagination.php
  resources/lang/uk-UA/passwords.php
  resources/lang/uk-UA/reports.php
  resources/lang/uk-UA/settings.php
  resources/lang/uk-UA/taxes.php
  resources/lang/uk-UA/transfers.php
  resources/lang/uk-UA/updates.php
  resources/lang/uk-UA/validation.php
Labels: Feature

#317 Invoice & Bill add discount style change
  app/Http/Controllers/Items/Items.php
  public/css/app.css
  resources/lang/en-GB/bills.php
  resources/lang/en-GB/invoices.php
  resources/views/expenses/bills/create.blade.php
  resources/views/expenses/bills/edit.blade.php
  resources/views/incomes/invoices/create.blade.php
  resources/views/incomes/invoices/edit.blade.php
Labels: Enhancement

#318 Hebrew translation
  config/language.php
  resources/lang/he-IL/accounts.php
  resources/lang/he-IL/auth.php
  resources/lang/he-IL/bills.php
  resources/lang/he-IL/companies.php
  resources/lang/he-IL/currencies.php
  resources/lang/he-IL/customers.php
  resources/lang/he-IL/dashboard.php
  resources/lang/he-IL/demo.php
  resources/lang/he-IL/footer.php
  resources/lang/he-IL/general.php
  resources/lang/he-IL/header.php
  resources/lang/he-IL/import.php
  resources/lang/he-IL/install.php
  resources/lang/he-IL/invoices.php
  resources/lang/he-IL/items.php
  resources/lang/he-IL/messages.php
  resources/lang/he-IL/modules.php
  resources/lang/he-IL/pagination.php
  resources/lang/he-IL/passwords.php
  resources/lang/he-IL/recurring.php
  resources/lang/he-IL/reports.php
  resources/lang/he-IL/settings.php
  resources/lang/he-IL/taxes.php
  resources/lang/he-IL/transfers.php
  resources/lang/he-IL/updates.php
  resources/lang/he-IL/validation.php
Labels: Feature

#320 Invoice/Bill: Decimal value for quantity
  app/Http/Controllers/Expenses/Bills.php
  app/Http/Controllers/Incomes/Invoices.php
  app/Http/Controllers/Items/Items.php
  composer.json
  database/migrations/2018_04_30_000000_change_quantity_column_invoice_bill_items.php
  resources/views/expenses/bills/create.blade.php
  resources/views/expenses/bills/edit.blade.php
  resources/views/expenses/payments/create.blade.php
  resources/views/expenses/payments/edit.blade.php
  resources/views/incomes/invoices/create.blade.php
  resources/views/incomes/invoices/edit.blade.php
  resources/views/incomes/revenues/create.blade.php
  resources/views/incomes/revenues/edit.blade.php
  resources/views/items/items/create.blade.php
  resources/views/items/items/edit.blade.php
Labels: Feature
