Repository akaunting/akaunting, pull requests merged in 2018-09, with the labels that each got.

#492 Add today button on Datetimepicker
  resources/views/banking/transfers/create.blade.php
  resources/views/banking/transfers/edit.blade.php
  resources/views/expenses/bills/create.blade.php
  resources/views/expenses/bills/edit.blade.php
  resources/views/expenses/payments/create.blade.php
  resources/views/expenses/payments/edit.blade.php
  resources/views/incomes/invoices/create.blade.php
  resources/views/incomes/invoices/edit.blade.php
  resources/views/incomes/revenues/create.blade.php
  resources/views/incomes/revenues/edit.blade.php
  resources/views/modals/bills/payment.blade.php
  resources/views/modals/invoices/payment.blade.php
Labels: Enhancement

#493 Disable save button after click
  public/js/app.js
  resources/lang/en-GB/general.php
  resources/views/auth/permissions/create.blade.php
  resources/views/auth/permissions/edit.blade.php
  resources/views/auth/roles/create.blade.php
  resources/views/auth/roles/edit.blade.php
  resources/views/auth/users/create.blade.php
  resources/views/auth/users/edit.blade.php
  resources/views/banking/accounts/create.blade.php
  resources/views/banking/accounts/edit.blade.php
  resources/views/banking/transfers/create.blade.php
  resources/views/banking/transfers/edit.blade.php
  resources/views/common/companies/create.blade.php
  resources/views/common/companies/edit.blade.php
  resources/views/common/import/create.blade.php
  resources/views/common/items/create.blade.php
  resources/views/common/items/edit.blade.php
  resources/views/customers/profile/edit.blade.php
  resources/views/expenses/bills/create.blade.php
  resources/views/expenses/bills/edit.blade.php
  resources/views/expenses/payments/create.blade.php
  resources/views/expenses/payments/edit.blade.php
  resources/views/expenses/vendors/create.blade.php
  resources/views/expenses/vendors/edit.blade.php
  resources/views/incomes/customers/create.blade.php
  resources/views/incomes/customers/edit.blade.php
  resources/views/incomes/invoices/create.blade.php
  resources/views/incomes/invoices/edit.blade.php
  resources/views/incomes/revenues/create.blade.php
  resources/views/incomes/revenues/edit.blade.php
  resources/views/modals/bills/payment.blade.php
  resources/views/modals/categories/create.blade.php
  resources/views/modals/customers/create.blade.php
  resources/views/modals/invoices/payment.blade.php
  resources/views/modals/vendors/create.blade.php
  resources/views/modules/token/create.blade.php
  resources/views/partials/form/save_buttons.blade.php
  resources/views/settings/categories/create.blade.php
  resources/views/settings/categories/edit.blade.php
  resources/views/settings/currencies/create.blade.php
  resources/views/settings/currencies/edit.blade.php
  resources/views/settings/modules/edit.blade.php
  resources/views/settings/settings/edit.blade.php
  resources/views/settings/taxes/create.blade.php
  resources/views/settings/taxes/edit.blade.php
Labels: Enhancement, Language Change

#495 Added app store pagination
  app/Http/Controllers/Modules/Item.php
  app/Http/Controllers/Modules/Tiles.php
  app/Traits/Modules.php
  public/css/app.css
  resources/views/modules/home/index.blade.php
  resources/views/modules/item/show.blade.php
  resources/views/modules/tiles/index.blade.php
  resources/views/partials/modules/reviews.blade.php
  routes/web.php
Labels: Feature

#496 List invoices/bills in customer/vendor show page
  app/Http/Controllers/Expenses/Vendors.php
  app/Http/Controllers/Incomes/Customers.php
  resources/views/expenses/vendors/show.blade.php
  resources/views/incomes/customers/show.blade.php
Labels: Feature

#501 Send notification to admin after customer pay the invoice
  app/Listeners/Incomes/Invoice/Paid.php
  app/Notifications/Customer/Invoice.php
  modules/OfflinePayment/Http/Controllers/OfflinePayment.php
  modules/OfflinePayment/Http/routes.php
  resources/lang/en-GB/customers.php
Labels: Feature, Language Change

#502 Refactor Role form
  app/Http/Controllers/Auth/Roles.php
  public/css/app.css
  resources/lang/en-GB/general.php
  resources/views/auth/roles/create.blade.php
  resources/views/auth/roles/edit.blade.php
Labels: Enhancement, Language Change

#503 Reference field in Vendors/Customers
  app/Models/Expense/Vendor.php
  app/Models/Income/Customer.php
  database/migrations/2018_09_26_000000_add_reference_column_customers.php
  database/migrations/2018_09_26_000000_add_reference_column_vendors.php
  resources/views/expenses/vendors/create.blade.php
  resources/views/expenses/vendors/edit.blade.php
  resources/views/expenses/vendors/show.blade.php
  resources/views/incomes/customers/create.blade.php
  resources/views/incomes/customers/edit.blade.php
  resources/views/incomes/customers/show.blade.php
Labels: Feature

#505 Improve the update process
  app/Http/Controllers/Install/Updates.php
  app/Utilities/Updater.php
  resources/lang/en-GB/modules.php
  resources/views/install/updates/edit.blade.php
  routes/web.php
Labels: Feature, Language Change

#509 comma error fixed
  resources/views/settings/settings/edit.blade.php
Labels: Bug

#510 Fixed laravel use
  resources/views/settings/settings/edit.blade.php
Labels: Code Style
