Repository akaunting/akaunting, pull requests merged in 2018-12, with the labels that each got.

#662 Redirect to current URL if session timeout
  app/Exceptions/Handler.php
  app/Http/Controllers/Auth/Login.php
Labels: Feature

#667 Nginx config file
  nginx.conf.example
Labels: Feature

#675 Updated translations
  resources/lang/de-DE/messages.php
  resources/lang/de-DE/modules.php
  resources/lang/de-DE/reconciliations.php
  resources/lang/fa-IR/auth.php
  resources/lang/fa-IR/general.php
  resources/lang/fa-IR/invoices.php
  resources/lang/fa-IR/messages.php
  resources/lang/fa-IR/modules.php
  resources/lang/fa-IR/reconciliations.php
  resources/lang/it-IT/modules.php
  resources/lang/nb-NO/auth.php
  resources/lang/nb-NO/bills.php
  resources/lang/nb-NO/companies.php
  resources/lang/nb-NO/customers.php
  resources/lang/nb-NO/general.php
  resources/lang/nb-NO/header.php
  resources/lang/nb-NO/import.php
  resources/lang/nb-NO/install.php
  resources/lang/nb-NO/invoices.php
  resources/lang/nb-NO/items.php
  resources/lang/nb-NO/messages.php
  resources/lang/nb-NO/modules.php
  resources/lang/nb-NO/notifications.php
  resources/lang/nb-NO/passwords.php
  resources/lang/nb-NO/reconciliations.php
  resources/lang/nb-NO/reports.php
  resources/lang/nb-NO/settings.php
  resources/lang/nb-NO/taxes.php
  resources/lang/nb-NO/transfers.php
  resources/lang/nb-NO/validation.php
  resources/lang/nl-NL/bills.php
  resources/lang/nl-NL/modules.php
  resources/lang/pt-BR/bills.php
  resources/lang/pt-BR/general.php
  resources/lang/pt-BR/messages.php
  resources/lang/pt-BR/modules.php
  resources/lang/pt-BR/reconciliations.php
  resources/lang/sq-AL/general.php
  resources/lang/sq-AL/messages.php
  resources/lang/sq-AL/modules.php
  resources/lang/sq-AL/reconciliations.php
  resources/lang/sr-RS/customers.php
  resources/lang/sr-RS/dashboard.php
  resources/lang/sr-RS/footer.php
  resources/lang/sr-RS/general.php
  resources/lang/sr-RS/invoices.php
  resources/lang/sr-RS/messages.php
  resources/lang/sr-RS/modules.php
  resources/lang/sr-RS/notifications.php
  resources/lang/sr-RS/reconciliations.php
  resources/lang/sr-RS/taxes.php
  resources/lang/tr-TR/modules.php
Labels: Enhancement

#683 Offline Payment re-factoring
  modules/OfflinePayment/Assets/.gitkeep
  modules/OfflinePayment/Config/.gitkeep
  modules/OfflinePayment/Config/config.php
  modules/OfflinePayment/Console/.gitkeep
  modules/OfflinePayment/Database/Migrations/.gitkeep
  modules/OfflinePayment/Database/Seeders/.gitkeep
  modules/OfflinePayment/Entities/.gitkeep
  modules/OfflinePayment/Events/.gitkeep
  modules/OfflinePayment/Events/Handlers/.gitkeep
  modules/OfflinePayment/Http/Controllers/.gitkeep
  modules/OfflinePayment/Http/Controllers/OfflinePayment.php
  modules/OfflinePayment/Http/Controllers/Settings.php
  modules/OfflinePayment/Http/Middleware/.gitkeep
  modules/OfflinePayment/Http/Requests/.gitkeep
  modules/OfflinePayment/Http/routes.php
  modules/OfflinePayment/Jobs/.gitkeep
  modules/OfflinePayment/Listeners/OfflinePaymentAdminMenu.php
  modules/OfflinePayment/Listeners/OfflinePaymentGateway.php
  modules/OfflinePayment/Mail/.gitkeep
  modules/OfflinePayment/Providers/.gitkeep
  modules/OfflinePayment/Providers/OfflinePaymentServiceProvider.php
  modules/OfflinePayment/Repositories/.gitkeep
  modules/OfflinePayment/Resources/lang/.gitkeep
  modules/OfflinePayment/Resources/lang/en-GB/general.php
  modules/OfflinePayment/Resources/lang/en-GB/offlinepayment.php
  modules/OfflinePayment/Resources/views/.gitkeep
  modules/OfflinePayment/Resources/views/confirm.blade.php
  modules/OfflinePayment/Resources/views/edit.blade.php
  modules/OfflinePayment/Resources/views/link.blade.php
  modules/OfflinePayment/Resources/views/show.blade.php
  modules/OfflinePayment/Tests/.gitkeep
  modules/OfflinePayment/module.json
Labels: Enhancement, Language Change

#684 Paypal Standard re-factoring
  modules/PaypalStandard/Assets/.gitkeep
  modules/PaypalStandard/Config/.gitkeep
  modules/PaypalStandard/Config/config.php
  modules/PaypalStandard/Console/.gitkeep
  modules/PaypalStandard/Database/Migrations/.gitkeep
  modules/PaypalStandard/Database/Seeders/.gitkeep
  modules/PaypalStandard/Database/Seeders/PaypalStandardDatabaseSeeder.php
  modules/PaypalStandard/Entities/.gitkeep
  modules/PaypalStandard/Events/.gitkeep
  modules/PaypalStandard/Events/Handlers/.gitkeep
  modules/PaypalStandard/Http/Controllers/.gitkeep
  modules/PaypalStandard/Http/Middleware/.gitkeep
  modules/PaypalStandard/Http/Requests/.gitkeep
  modules/PaypalStandard/Jobs/.gitkeep
  modules/PaypalStandard/Listeners/PaypalStandardGateway.php
  modules/PaypalStandard/Mail/.gitkeep
  modules/PaypalStandard/Providers/.gitkeep
  modules/PaypalStandard/Providers/PaypalStandardServiceProvider.php
  modules/PaypalStandard/Repositories/.gitkeep
  modules/PaypalStandard/Resources/lang/.gitkeep
  modules/PaypalStandard/Resources/lang/en-GB/general.php
  modules/PaypalStandard/Resources/lang/en-GB/paypalstandard.php
  modules/PaypalStandard/Resources/views/.gitkeep
  modules/PaypalStandard/Resources/views/show.blade.php
  modules/PaypalStandard/Tests/.gitkeep
  modules/PaypalStandard/module.json
Labels: Enhancement, Language Change

#693 Removed demo tax rates
  database/seeds/CompanySeeder.php
  database/seeds/Taxes.php
  resources/lang/en-GB/demo.php
Labels: Enhancement

#696 Item add new tax
  resources/views/common/items/create.blade.php
  resources/views/common/items/edit.blade.php
Labels: Enhancement

#697 Urdu (Pakistan) translation
  config/language.php
  resources/lang/ur-PK/accounts.php
  resources/lang/ur-PK/auth.php
  resources/lang/ur-PK/bills.php
  resources/lang/ur-PK/companies.php
  resources/lang/ur-PK/currencies.php
  resources/lang/ur-PK/customers.php
  resources/lang/ur-PK/dashboard.php
  resources/lang/ur-PK/demo.php
  resources/lang/ur-PK/footer.php
  resources/lang/ur-PK/general.php
  resources/lang/ur-PK/header.php
  resources/lang/ur-PK/import.php
  resources/lang/ur-PK/install.php
  resources/lang/ur-PK/invoices.php
  resources/lang/ur-PK/items.php
  resources/lang/ur-PK/messages.php
  resources/lang/ur-PK/modules.php
  resources/lang/ur-PK/notifications.php
  resources/lang/ur-PK/pagination.php
  resources/lang/ur-PK/passwords.php
  resources/lang/ur-PK/reconciliations.php
  resources/lang/ur-PK/recurring.php
  resources/lang/ur-PK/reports.php
  resources/lang/ur-PK/settings.php
  resources/lang/ur-PK/taxes.php
  resources/lang/ur-PK/transfers.php
  resources/lang/ur-PK/updates.php
  resources/lang/ur-PK/validation.php
Labels: Feature

#689 Fix calculation to show correct amount in modal
  app/Http/Controllers/Modals/BillPayments.php
Labels: Bug

#699 Remove passing of unused variable
  app/Http/Controllers/Incomes/Customers.php
Labels: Bug

#703 Dashboard Test Added
  tests/Feature/Common/DashboardTest.php
Labels: Feature
