Repository akaunting/akaunting, pull requests merged in 2019-12, with the labels that each got.

#967 Modals button animation and pagination updated
  resources/assets/js/components/AkauntingDashboard.vue
  resources/assets/js/components/AkauntingModal.vue
  resources/views/vendor/pagination/bootstrap-4.blade.php
Labels: Enhancement

#968 Delete animation added
  resources/assets/js/components/AkauntingModal.vue
Labels: Enhancement

#969 Delete animation styles updated
  public/css/custom.css
  resources/assets/js/components/AkauntingModal.vue
Labels: Enhancement

#971 Pagination max page item updated
  resources/views/vendor/pagination/bootstrap-4.blade.php
Labels: Enhancement

#972 Added update command
  app/Console/Commands/FinishUpdate.php
  app/Console/Commands/Update.php
  app/Http/Controllers/Install/Updates.php
  app/Http/Controllers/Modules/Item.php
  app/Listeners/Update/CreateModuleUpdatedHistory.php
  app/Providers/Event.php
  app/Traits/Modules.php
  app/Utilities/Console.php
  app/Utilities/Updater.php
  app/Utilities/Versions.php
  overrides/akaunting/module/Commands/InstallCommand.php
  resources/lang/en-GB/modules.php
  routes/admin.php
Labels: Feature

#973 enable/disable mail protocol
  resources/assets/js/views/settings/settings.js
  resources/views/settings/email/edit.blade.php
Labels: Bug

#975 transactions.js deleted close issues :#974
  webpack.mix.js
Labels: Bug

#977 Improved invoice/bill jobs
  app/Events/Expense/BillCreating.php
  app/Events/Expense/BillUpdating.php
  app/Http/Controllers/Common/Items.php
  app/Jobs/Expense/CreateBill.php
  app/Jobs/Expense/CreateBillItem.php
  app/Jobs/Expense/UpdateBill.php
  app/Jobs/Income/CreateInvoice.php
  app/Jobs/Income/CreateInvoiceItem.php
  app/Jobs/Income/UpdateInvoice.php
  database/factories/Item.php
Labels: Enhancement

#990 Invoice and bill show positions updated
  resources/views/expenses/bills/show.blade.php
  resources/views/incomes/invoices/show.blade.php
Labels: Enhancement

#991 Invoice and bill show transaction line updated
  resources/views/expenses/bills/show.blade.php
  resources/views/incomes/invoices/show.blade.php
Labels: Enhancement

#992 Vendor bills show column problem fixed
  resources/views/expenses/vendors/show.blade.php
Labels: Enhancement

#993 Empty page style added
  public/css/custom.css
  public/img/empty_pages/bills.png
  public/img/empty_pages/customers.png
  public/img/empty_pages/invoices.png
  public/img/empty_pages/items.png
  public/img/empty_pages/payments.png
  public/img/empty_pages/revenues.png
  public/img/empty_pages/vendors.png
  resources/lang/en-GB/general.php
  resources/views/common/items/index.blade.php
  resources/views/expenses/bills/index.blade.php
  resources/views/expenses/payments/index.blade.php
  resources/views/expenses/vendors/index.blade.php
  resources/views/incomes/customers/index.blade.php
  resources/views/incomes/invoices/index.blade.php
  resources/views/incomes/revenues/index.blade.php
  resources/views/partials/admin/empty_page.blade.php
Labels: Enhancement

#995 Open sans font added in core
  public/css/custom.css
  public/fonts/nucleo-icons.eot
  public/fonts/nucleo-icons.svg
  public/fonts/nucleo-icons.ttf
  public/fonts/nucleo-icons.woff
  public/fonts/nucleo-icons.woff2
  public/fonts/nucleo/nucleo-icons.eot
  public/fonts/nucleo/nucleo-icons.svg
  public/fonts/nucleo/nucleo-icons.ttf
  public/fonts/nucleo/nucleo-icons.woff
  public/fonts/nucleo/nucleo-icons.woff2
  public/vendor/opensans/css/opensans.css
  public/vendor/opensans/fonts/OpenSans-Bold.ttf
  public/vendor/opensans/fonts/OpenSans-Light.ttf
  public/vendor/opensans/fonts/OpenSans-Regular.ttf
  public/vendor/opensans/fonts/OpenSans-SemiBold.ttf
  resources/views/partials/admin/head.blade.php
  resources/views/partials/auth/head.blade.php
  resources/views/partials/install/head.blade.php
  resources/views/partials/modules/head.blade.php
  resources/views/partials/portal/head.blade.php
  resources/views/partials/signed/head.blade.php
  resources/views/partials/wizard/head.blade.php
Labels: Enhancement

#996 Unnecessary css lines deleted
  public/css/custom.css
  resources/views/expenses/bills/show.blade.php
  resources/views/incomes/invoices/print.blade.php
  resources/views/incomes/invoices/show.blade.php
  resources/views/layouts/auth.blade.php
  resources/views/layouts/install.blade.php
  resources/views/partials/form/file_group.blade.php
  resources/views/portal/invoices/show.blade.php
  resources/views/portal/invoices/signed.blade.php
Labels: Code Style, Enhancement

#1002 Hidden classes updated
  public/css/custom.css
  resources/views/auth/permissions/index.blade.php
  resources/views/auth/roles/index.blade.php
  resources/views/auth/users/index.blade.php
  resources/views/banking/accounts/index.blade.php
  resources/views/banking/reconciliations/create.blade.php
  resources/views/banking/reconciliations/edit.blade.php
  resources/views/banking/reconciliations/index.blade.php
  resources/views/banking/transactions/index.blade.php
  resources/views/banking/transfers/index.blade.php
  resources/views/common/companies/index.blade.php
  resources/views/common/items/index.blade.php
  resources/views/expenses/bills/index.blade.php
  resources/views/expenses/bills/show.blade.php
  resources/views/expenses/payments/index.blade.php
  resources/views/expenses/vendors/index.blade.php
  resources/views/expenses/vendors/show.blade.php
  resources/views/incomes/customers/index.blade.php
  resources/views/incomes/customers/show.blade.php
  resources/views/incomes/invoices/index.blade.php
  resources/views/incomes/invoices/print.blade.php
  resources/views/incomes/invoices/show.blade.php
  resources/views/incomes/revenues/index.blade.php
  resources/views/install/updates/edit.blade.php
  resources/views/install/updates/index.blade.php
  resources/views/partials/admin/navbar.blade.php
  resources/views/partials/admin/pagination.blade.php
  resources/views/partials/form/bulk_action_row_group.blade.php
  resources/views/partials/modules/reviews.blade.php
  resources/views/partials/portal/navbar.blade.php
  resources/views/partials/portal/pagination.blade.php
  resources/views/partials/portal/payment_method/redirect/show.blade.php
  resources/views/partials/portal/payment_method/redirect/signed.blade.php
  resources/views/partials/widget/head.blade.php
  resources/views/portal/invoices/index.blade.php
  resources/views/portal/invoices/show.blade.php
  resources/views/portal/payments/index.blade.php
  resources/views/settings/categories/index.blade.php
  resources/views/settings/currencies/index.blade.php
  resources/views/settings/taxes/index.blade.php
  resources/views/vendor/pagination/bootstrap-4.blade.php
Labels: Code Style

#1004 Radio group style fixed
  resources/views/partials/form/radio_group.blade.php
Labels: Code Style, Enhancement

#1005 Invoice and bill show pages time line updated
  resources/views/expenses/bills/show.blade.php
  resources/views/incomes/invoices/show.blade.php
Labels: Code Style, Enhancement

#1009 History and transaction tables style updated
  resources/views/expenses/bills/show.blade.php
  resources/views/incomes/invoices/show.blade.php
Labels: Code Style, Enhancement

#1012 Email body text size updated
  public/css/custom.css
Labels: Enhancement

#1014 Tax tags style and auto complate fixed
  public/css/custom.css
  resources/views/expenses/bills/item.blade.php
  resources/views/incomes/invoices/item.blade.php
Labels: Enhancement

#1017 Unnecessary css deleted
  resources/assets/js/components/AkauntingWidget.vue
Labels: Enhancement

#1018 Table layout updated for module show page
  public/css/custom.css
  resources/views/modules/item/show.blade.php
Labels: Enhancement

#1019 Some position in modules updated
  public/css/custom.css
  resources/views/modules/item/show.blade.php
  resources/views/partials/form/date_range.blade.php
  resources/views/partials/modules/bar.blade.php
  resources/views/partials/reports/filter.blade.php
Labels: Code Style, Enhancement

#1020 enable/disable email protocol
  resources/assets/js/components/AkauntingSelect.vue
  resources/assets/js/views/settings/settings.js
  resources/views/partials/form/select_group.blade.php
  resources/views/settings/email/edit.blade.php
Labels: Bug

#1023 Refactored bulk actions
  app/Abstracts/BulkAction.php
  app/BulkActions/Auth/Permissions.php
  app/BulkActions/Auth/Roles.php
  app/BulkActions/Auth/Users.php
  app/BulkActions/Banking/Accounts.php
  app/BulkActions/Banking/Reconciliations.php
  app/BulkActions/Banking/Transfers.php
  app/BulkActions/Common/Companies.php
  app/BulkActions/Common/Items.php
  app/BulkActions/Expenses/Bills.php
  app/BulkActions/Expenses/Payments.php
  app/BulkActions/Expenses/Vendors.php
  app/BulkActions/Incomes/Customers.php
  app/BulkActions/Incomes/Invoices.php
  app/BulkActions/Incomes/Revenues.php
  app/BulkActions/Settings/Categories.php
  app/BulkActions/Settings/Currencies.php
  app/BulkActions/Settings/Taxes.php
  app/Jobs/Common/UpdateContact.php
  resources/lang/en-GB/bulk_actions.php
Labels: Enhancement, Language Change

#1025 Fixing style of description column on transactions page. It should wr…
  resources/views/banking/transactions/index.blade.php
Labels: Enhancement

#1026 Value of radio group controls should be given on edit page of settings
  resources/views/settings/modules/edit.blade.php
Labels: Bug

#1013 fix invoice hang
  resources/assets/js/mixins/global.js
  resources/views/modals/customers/create.blade.php
  resources/views/partials/admin/content.blade.php
Labels: Enhancement

#1011 fix add tax modal
  resources/views/incomes/invoices/item.blade.php
  resources/views/modals/taxes/create.blade.php
  resources/views/partials/form/multi_select_add_new_group.blade.php
Labels: Enhancement

#1028 Select tax style updated
  public/css/custom.css
Labels: Code Style, Enhancement

#1029 Icelandic translation
  config/language.php
  resources/lang/is-IS/accounts.php
  resources/lang/is-IS/auth.php
  resources/lang/is-IS/bills.php
  resources/lang/is-IS/bulk_actions.php
  resources/lang/is-IS/companies.php
  resources/lang/is-IS/currencies.php
  resources/lang/is-IS/customers.php
  resources/lang/is-IS/dashboard.php
  resources/lang/is-IS/demo.php
  resources/lang/is-IS/email_templates.php
  resources/lang/is-IS/errors.php
  resources/lang/is-IS/footer.php
  resources/lang/is-IS/general.php
  resources/lang/is-IS/header.php
  resources/lang/is-IS/import.php
  resources/lang/is-IS/install.php
  resources/lang/is-IS/invoices.php
  resources/lang/is-IS/items.php
  resources/lang/is-IS/maintenance.php
  resources/lang/is-IS/messages.php
  resources/lang/is-IS/modules.php
  resources/lang/is-IS/notifications.php
  resources/lang/is-IS/pagination.php
  resources/lang/is-IS/passwords.php
  resources/lang/is-IS/reconciliations.php
  resources/lang/is-IS/recurring.php
  resources/lang/is-IS/reports.php
  resources/lang/is-IS/settings.php
  resources/lang/is-IS/taxes.php
  resources/lang/is-IS/transfers.php
  resources/lang/is-IS/updates.php
  resources/lang/is-IS/validation.php
Labels: Feature

#1030 Uzbek translation
  config/language.php
  resources/lang/uz-UZ/accounts.php
  resources/lang/uz-UZ/auth.php
  resources/lang/uz-UZ/bills.php
  resources/lang/uz-UZ/bulk_actions.php
  resources/lang/uz-UZ/companies.php
  resources/lang/uz-UZ/currencies.php
  resources/lang/uz-UZ/customers.php
  resources/lang/uz-UZ/dashboard.php
  resources/lang/uz-UZ/demo.php
  resources/lang/uz-UZ/email_templates.php
  resources/lang/uz-UZ/errors.php
  resources/lang/uz-UZ/footer.php
  resources/lang/uz-UZ/general.php
  resources/lang/uz-UZ/header.php
  resources/lang/uz-UZ/import.php
  resources/lang/uz-UZ/install.php
  resources/lang/uz-UZ/invoices.php
  resources/lang/uz-UZ/items.php
  resources/lang/uz-UZ/maintenance.php
  resources/lang/uz-UZ/messages.php
  resources/lang/uz-UZ/modules.php
  resources/lang/uz-UZ/notifications.php
  resources/lang/uz-UZ/pagination.php
  resources/lang/uz-UZ/passwords.php
  resources/lang/uz-UZ/reconciliations.php
  resources/lang/uz-UZ/recurring.php
  resources/lang/uz-UZ/reports.php
  resources/lang/uz-UZ/settings.php
  resources/lang/uz-UZ/taxes.php
  resources/lang/uz-UZ/transfers.php
  resources/lang/uz-UZ/updates.php
  resources/lang/uz-UZ/validation.php
Labels: Feature

#1033 Print template
  app/Http/Controllers/Incomes/Invoices.php
  app/Http/Controllers/Modals/InvoiceTemplates.php
  app/Providers/ViewComposer.php
  public/css/custom.css
  public/img/print_templates/classic.png
  public/img/print_templates/default.png
  public/img/print_templates/modern.png
  resources/assets/js/views/settings/settings.js
  resources/lang/en-GB/settings.php
  resources/views/incomes/invoices/print.blade.php
  resources/views/incomes/invoices/print_classic.blade.php
  resources/views/incomes/invoices/print_default.blade.php
  resources/views/incomes/invoices/print_modern.blade.php
  resources/views/modals/settings/template.blade.php
  resources/views/settings/invoice/edit.blade.php
  routes/admin.php
Labels: Code Style, Enhancement, Feature

#1037 Caurosel style fixed #1036
  public/css/custom.css
  resources/assets/js/components/AkauntingCarousel.vue
  resources/views/modules/item/show.blade.php
Labels: Code Style, Enhancement

#1038 Carousel forgotten frame added
  public/css/custom.css
  resources/assets/js/components/AkauntingCarousel.vue
Labels: Code Style, Enhancement

#1039 Dashboard general style updated
  public/css/custom.css
  resources/views/common/dashboard/index.blade.php
Labels: Code Style, Enhancement

#1040 Forgotten date style added
  public/css/custom.css
Labels: Code Style, Enhancement

#1045 Revenue empty page image updated
  public/img/empty_pages/revenues.png
Labels: Enhancement

#1046 Forgot page converted to vue form
  resources/assets/js/views/auth/forgot.js
  resources/assets/js/views/auth/login.js
  resources/views/auth/forgot/create.blade.php
Labels: Code Style, Enhancement

#1047 Unnecessary classes deleted in portal
  resources/views/partials/portal/navbar.blade.php
  resources/views/portal/dashboard/index.blade.php
Labels: Code Style

#1048 Dashboard date style updated
  public/css/custom.css
Labels: Code Style

#1049 Forgot and login styles updated
  public/css/custom.css
  resources/views/auth/forgot/create.blade.php
  resources/views/auth/login/create.blade.php
Labels: Code Style, Enhancement

#1051 Reset page converted to vue form
  public/css/custom.css
  resources/assets/js/views/auth/reset.js
  resources/views/auth/reset/create.blade.php
  resources/views/partials/form/text_group.blade.php
  routes/guest.php
Labels: Code Style, Enhancement

#1057 Unnecessary styles deleted in role page
  resources/views/auth/roles/create.blade.php
  resources/views/auth/roles/edit.blade.php
Labels: Code Style, Enhancement

#1058 New widget structure
  app/Abstracts/Widget.php
  app/Console/Stubs/Modules/json.stub
  app/Http/Controllers/Common/Dashboard.php
  app/Http/Controllers/Common/Widgets.php
  app/Jobs/Auth/DeleteUser.php
  app/Jobs/Common/DeleteCompany.php
  app/Models/Auth/User.php
  app/Models/Common/Company.php
  app/Models/Common/Dashboard.php
  app/Models/Common/DashboardWidget.php
  app/Models/Common/Widget.php
  app/Providers/Blade.php
  app/Utilities/Widgets.php
  app/Utilities/helpers.php
  app/Widgets/AccountBalance.php
  app/Widgets/CashFlow.php
  app/Widgets/ExpensesByCategory.php
  app/Widgets/IncomeByCategory.php
  app/Widgets/LatestExpenses.php
  app/Widgets/LatestIncome.php
  app/Widgets/TotalExpenses.php
  app/Widgets/TotalIncome.php
  app/Widgets/TotalProfit.php
  composer.json
  composer.lock
  config/laravel-widgets.php
  database/migrations/2019_11_14_000000_create_dashboards_table.php
  database/seeds/Dashboards.php
  database/seeds/UserSeeder.php
  database/seeds/Widgets.php
  modules/OfflinePayments/module.json
  modules/PaypalStandard/module.json
  resources/lang/en-GB/widgets.php
  resources/views/common/dashboard/index.blade.php
  resources/views/widgets/account_balance.blade.php
  resources/views/widgets/cash_flow.blade.php
  resources/views/widgets/expenses_by_category.blade.php
  resources/views/widgets/income_by_category.blade.php
  resources/views/widgets/latest_expenses.blade.php
  resources/views/widgets/latest_income.blade.php
  resources/views/widgets/total_expenses.blade.php
  resources/views/widgets/total_income.blade.php
  resources/views/widgets/total_profit.blade.php
  routes/admin.php
Labels: Enhancement

#1060 Nucleo font deleted for compile
  resources/assets/js/plugins/dashboard-plugin.js
Labels: Code Style, Enhancement

#1061 Code review for js files
  resources/assets/js/views/auth/permissions.js
  resources/assets/js/views/auth/users.js
  resources/assets/js/views/banking/accounts.js
  resources/assets/js/views/banking/reconciliations.js
  resources/assets/js/views/banking/transactions.js
  resources/assets/js/views/banking/transfers.js
  resources/assets/js/views/common/companies.js
  resources/assets/js/views/common/reports.js
  resources/assets/js/views/common/search.js
  resources/assets/js/views/purchases/bills.js
  resources/assets/js/views/purchases/payments.js
  resources/assets/js/views/purchases/vendors.js
  resources/assets/js/views/sales/invoices.js
  resources/assets/js/views/settings/currencies.js
  resources/assets/js/views/settings/taxes.js
Labels: Code Style, Enhancement

#1062 Forgotten review
  resources/assets/js/views/wizard/company.js
Labels: Code Style, Enhancement
