Repository akaunting/akaunting, pull requests merged in 2019-11, with the labels that each got.

#899 placeholder property added for textarea controls.
  resources/views/partials/form/textarea_group.blade.php
Labels: Bug

#900 Fixed bill creation & deletion
  app/Http/Controllers/Expenses/Bills.php
  app/Models/Expense/Bill.php
  app/Models/Expense/BillItem.php
Labels: Bug

#902 Portal dashboard view updated
  resources/views/portal/dashboard/index.blade.php
Labels: Enhancement

#906 Applied jobs to tests
  .env.testing
  database/migrations/2019_11_17_000000_modify_sku_quantity_column_items_table.php
  database/seeds/TestCompany.php
  tests/Feature/Auth/LoginTest.php
  tests/Feature/Auth/PermissionsTest.php
  tests/Feature/Auth/RolesTest.php
  tests/Feature/Auth/UsersTest.php
  tests/Feature/Banking/AccountsTest.php
  tests/Feature/Banking/ReconciliationsTest.php
  tests/Feature/Banking/TransfersTest.php
  tests/Feature/Commands/BillReminderTest.php
  tests/Feature/Commands/InvoiceReminderTest.php
  tests/Feature/Common/DashboardTest.php
  tests/Feature/Common/ItemsTest.php
  tests/Feature/Expenses/BillsTest.php
  tests/Feature/Expenses/PaymentsTest.php
  tests/Feature/Expenses/VendorsTest.php
  tests/Feature/FeatureTestCase.php
  tests/Feature/Incomes/CustomersTest.php
  tests/Feature/Incomes/InvoicesTest.php
  tests/Feature/Incomes/RevenuesTest.php
  tests/Feature/Settings/CategoriesTest.php
  tests/Feature/Settings/CurrenciesTest.php
  tests/Feature/Settings/TaxesTest.php
  tests/TestCase.php
Labels: Enhancement

#908 Fixed item creation
  database/migrations/2019_11_17_000000_modify_sku_quantity_column_items_table.php
Labels: Bug

#910 Invoice logo updated to company logo
  resources/views/incomes/invoices/show.blade.php
  resources/views/portal/invoices/invoice.blade.php
  resources/views/portal/invoices/show.blade.php
  resources/views/portal/invoices/signed.blade.php
  resources/views/settings/invoice/edit.blade.php
Labels: Enhancement

#911 Fixed user deletion
  app/Observers/User.php
Labels: Bug

#912 Modal button actions updated
  public/css/custom.css
  resources/views/partials/form/save_buttons.blade.php
Labels: Bug

#913 Fixed tests
  .gitignore
  app/Jobs/Banking/CreateReconciliation.php
  database/factories/ItemFacorty.php
  database/factories/ItemFactory.php
  database/factories/TransactionFactory.php
  database/seeds/TestCompany.php
  tests/Feature/Auth/UsersTest.php
  tests/Feature/Banking/AccountsTest.php
  tests/Feature/Banking/ReconciliationsTest.php
  tests/Feature/Banking/TransfersTest.php
  tests/Feature/Commands/BillReminderTest.php
  tests/Feature/Commands/InvoiceReminderTest.php
  tests/Feature/Common/ItemsTest.php
  tests/Feature/Expenses/BillsTest.php
  tests/Feature/FeatureTestCase.php
  tests/Feature/Incomes/CustomersTest.php
  tests/Feature/Incomes/InvoicesTest.php
Labels: Bug

#921 Bulgarian translation
  resources/lang/bg-BG/accounts.php
  resources/lang/bg-BG/auth.php
  resources/lang/bg-BG/bills.php
  resources/lang/bg-BG/bulk_actions.php
  resources/lang/bg-BG/companies.php
  resources/lang/bg-BG/customers.php
  resources/lang/bg-BG/dashboard.php
  resources/lang/bg-BG/demo.php
  resources/lang/bg-BG/email_templates.php
  resources/lang/bg-BG/errors.php
  resources/lang/bg-BG/general.php
  resources/lang/bg-BG/header.php
  resources/lang/bg-BG/invoices.php
  resources/lang/bg-BG/items.php
  resources/lang/bg-BG/maintenance.php
  resources/lang/bg-BG/messages.php
  resources/lang/bg-BG/modules.php
  resources/lang/bg-BG/pagination.php
  resources/lang/bg-BG/reconciliations.php
  resources/lang/bg-BG/reports.php
  resources/lang/bg-BG/settings.php
  resources/lang/bg-BG/taxes.php
  resources/lang/bg-BG/validation.php
Labels: Enhancement

#922 Danish translation
  resources/lang/da-DK/auth.php
  resources/lang/da-DK/bulk_actions.php
  resources/lang/da-DK/companies.php
  resources/lang/da-DK/customers.php
  resources/lang/da-DK/dashboard.php
  resources/lang/da-DK/email_templates.php
  resources/lang/da-DK/general.php
  resources/lang/da-DK/header.php
  resources/lang/da-DK/invoices.php
  resources/lang/da-DK/items.php
  resources/lang/da-DK/maintenance.php
  resources/lang/da-DK/messages.php
  resources/lang/da-DK/modules.php
  resources/lang/da-DK/pagination.php
  resources/lang/da-DK/reconciliations.php
  resources/lang/da-DK/reports.php
  resources/lang/da-DK/settings.php
  resources/lang/da-DK/taxes.php
  resources/lang/da-DK/validation.php
Labels: Enhancement

#923 German translation
  resources/lang/de-DE/auth.php
  resources/lang/de-DE/bulk_actions.php
  resources/lang/de-DE/companies.php
  resources/lang/de-DE/customers.php
  resources/lang/de-DE/dashboard.php
  resources/lang/de-DE/email_templates.php
  resources/lang/de-DE/general.php
  resources/lang/de-DE/header.php
  resources/lang/de-DE/invoices.php
  resources/lang/de-DE/items.php
  resources/lang/de-DE/maintenance.php
  resources/lang/de-DE/messages.php
  resources/lang/de-DE/modules.php
  resources/lang/de-DE/pagination.php
  resources/lang/de-DE/reconciliations.php
  resources/lang/de-DE/reports.php
  resources/lang/de-DE/settings.php
  resources/lang/de-DE/taxes.php
  resources/lang/de-DE/validation.php
Labels: Enhancement

#924 Russian translation
  resources/lang/ru-RU/auth.php
  resources/lang/ru-RU/bills.php
  resources/lang/ru-RU/bulk_actions.php
  resources/lang/ru-RU/companies.php
  resources/lang/ru-RU/customers.php
  resources/lang/ru-RU/dashboard.php
  resources/lang/ru-RU/email_templates.php
  resources/lang/ru-RU/general.php
  resources/lang/ru-RU/header.php
  resources/lang/ru-RU/import.php
  resources/lang/ru-RU/install.php
  resources/lang/ru-RU/invoices.php
  resources/lang/ru-RU/items.php
  resources/lang/ru-RU/maintenance.php
  resources/lang/ru-RU/messages.php
  resources/lang/ru-RU/modules.php
  resources/lang/ru-RU/notifications.php
  resources/lang/ru-RU/pagination.php
  resources/lang/ru-RU/reconciliations.php
  resources/lang/ru-RU/recurring.php
  resources/lang/ru-RU/reports.php
  resources/lang/ru-RU/settings.php
  resources/lang/ru-RU/taxes.php
  resources/lang/ru-RU/transfers.php
  resources/lang/ru-RU/validation.php
Labels: Enhancement

#925 Ukrainian translation
  resources/lang/uk-UA/accounts.php
  resources/lang/uk-UA/auth.php
  resources/lang/uk-UA/bills.php
  resources/lang/uk-UA/bulk_actions.php
  resources/lang/uk-UA/companies.php
  resources/lang/uk-UA/currencies.php
  resources/lang/uk-UA/customers.php
  resources/lang/uk-UA/dashboard.php
  resources/lang/uk-UA/demo.php
  resources/lang/uk-UA/email_templates.php
  resources/lang/uk-UA/errors.php
  resources/lang/uk-UA/general.php
  resources/lang/uk-UA/header.php
  resources/lang/uk-UA/import.php
  resources/lang/uk-UA/install.php
  resources/lang/uk-UA/invoices.php
  resources/lang/uk-UA/items.php
  resources/lang/uk-UA/maintenance.php
  resources/lang/uk-UA/messages.php
  resources/lang/uk-UA/modules.php
  resources/lang/uk-UA/notifications.php
  resources/lang/uk-UA/pagination.php
  resources/lang/uk-UA/reconciliations.php
  resources/lang/uk-UA/recurring.php
  resources/lang/uk-UA/reports.php
  resources/lang/uk-UA/settings.php
  resources/lang/uk-UA/taxes.php
  resources/lang/uk-UA/transfers.php
  resources/lang/uk-UA/updates.php
  resources/lang/uk-UA/validation.php
Labels: Enhancement

#927 Removed enabled column from reports
  app/Http/Controllers/Api/Common/Reports.php
  app/Http/Controllers/Common/Reports.php
  app/Http/Requests/Common/Report.php
  app/Listeners/Update/V20/Version201.php
  app/Models/Common/Report.php
  app/Providers/Event.php
  app/Transformers/Common/Report.php
  app/Utilities/Reports.php
  database/migrations/2019_11_19_000000_drop_enabled_column_reports_table.php
  database/seeds/Reports.php
  resources/views/common/reports/create.blade.php
  resources/views/common/reports/edit.blade.php
  routes/admin.php
Labels: Enhancement

#928 Api key create responsive problem fixed
  resources/views/modules/api_key/create.blade.php
Labels: Bug

#930 Simplified install command
  README.md
  app/Console/Commands/Install.php
Labels: Enhancement

#933 Modules bar and user permission style updated
  resources/views/partials/form/checkbox_group.blade.php
  resources/views/partials/modules/bar.blade.php
Labels: Enhancement

#936 Refactored report and update abstracts
  app/Abstracts/Listeners/Report.php
  app/Abstracts/Listeners/Update.php
  app/Abstracts/Report.php
  app/Listeners/Common/ExpenseSummaryReport.php
  app/Listeners/Common/IncomeExpenseSummaryReport.php
  app/Listeners/Common/IncomeSummaryReport.php
  app/Listeners/Common/ProfitLossReport.php
  app/Listeners/Common/TaxSummaryReport.php
  app/Listeners/Update/V10/Version106.php
  app/Listeners/Update/V10/Version107.php
  app/Listeners/Update/V10/Version108.php
  app/Listeners/Update/V10/Version109.php
  app/Listeners/Update/V11/Version110.php
  app/Listeners/Update/V11/Version112.php
  app/Listeners/Update/V11/Version113.php
  app/Listeners/Update/V11/Version119.php
  app/Listeners/Update/V12/Version120.php
  app/Listeners/Update/V12/Version1210.php
  app/Listeners/Update/V12/Version1211.php
  app/Listeners/Update/V12/Version126.php
  app/Listeners/Update/V12/Version127.php
  app/Listeners/Update/V12/Version129.php
  app/Listeners/Update/V13/Version130.php
  app/Listeners/Update/V13/Version1311.php
  app/Listeners/Update/V13/Version1313.php
  app/Listeners/Update/V13/Version1316.php
  app/Listeners/Update/V13/Version132.php
  app/Listeners/Update/V13/Version135.php
  app/Listeners/Update/V13/Version138.php
  app/Listeners/Update/V13/Version139.php
  app/Listeners/Update/V20/Version200.php
  app/Listeners/Update/V20/Version201.php
  app/Reports/ExpenseSummary.php
  app/Reports/IncomeExpenseSummary.php
  app/Reports/IncomeSummary.php
  app/Reports/ProfitLoss.php
  app/Reports/TaxSummary.php
Labels: Enhancement

#937 Spanish translation
  resources/lang/es-ES/auth.php
  resources/lang/es-ES/bills.php
  resources/lang/es-ES/bulk_actions.php
  resources/lang/es-ES/companies.php
  resources/lang/es-ES/customers.php
  resources/lang/es-ES/dashboard.php
  resources/lang/es-ES/email_templates.php
  resources/lang/es-ES/errors.php
  resources/lang/es-ES/general.php
  resources/lang/es-ES/header.php
  resources/lang/es-ES/invoices.php
  resources/lang/es-ES/items.php
  resources/lang/es-ES/maintenance.php
  resources/lang/es-ES/messages.php
  resources/lang/es-ES/modules.php
  resources/lang/es-ES/pagination.php
  resources/lang/es-ES/reconciliations.php
  resources/lang/es-ES/reports.php
  resources/lang/es-ES/settings.php
  resources/lang/es-ES/taxes.php
  resources/lang/es-ES/validation.php
Labels: Enhancement

#938 Japanese translation
  resources/lang/ja-JP/accounts.php
  resources/lang/ja-JP/auth.php
  resources/lang/ja-JP/bills.php
  resources/lang/ja-JP/bulk_actions.php
  resources/lang/ja-JP/companies.php
  resources/lang/ja-JP/customers.php
  resources/lang/ja-JP/dashboard.php
  resources/lang/ja-JP/email_templates.php
  resources/lang/ja-JP/general.php
  resources/lang/ja-JP/header.php
  resources/lang/ja-JP/invoices.php
  resources/lang/ja-JP/items.php
  resources/lang/ja-JP/maintenance.php
  resources/lang/ja-JP/messages.php
  resources/lang/ja-JP/modules.php
  resources/lang/ja-JP/pagination.php
  resources/lang/ja-JP/reconciliations.php
  resources/lang/ja-JP/reports.php
  resources/lang/ja-JP/settings.php
  resources/lang/ja-JP/taxes.php
  resources/lang/ja-JP/validation.php
Labels: Enhancement

#943 Fixed bill show page
  resources/views/expenses/bills/show.blade.php
  resources/views/incomes/invoices/show.blade.php
  routes/admin.php
Labels: Bug

#944 Long texts class name changed
  public/css/custom.css
  resources/views/auth/permissions/index.blade.php
  resources/views/auth/users/index.blade.php
  resources/views/banking/reconciliations/create.blade.php
  resources/views/banking/reconciliations/edit.blade.php
  resources/views/common/companies/index.blade.php
  resources/views/expenses/bills/create.blade.php
  resources/views/expenses/bills/edit.blade.php
  resources/views/expenses/bills/item.blade.php
  resources/views/expenses/vendors/index.blade.php
  resources/views/expenses/vendors/show.blade.php
  resources/views/incomes/customers/index.blade.php
  resources/views/incomes/customers/show.blade.php
  resources/views/install/updates/index.blade.php
  resources/views/partials/admin/header.blade.php
  resources/views/partials/admin/menu.blade.php
  resources/views/partials/portal/header.blade.php
  resources/views/partials/portal/menu.blade.php
  resources/views/portal/payments/show.blade.php
Labels: Code Style

#946 Long text status updated for invoice and bill
  resources/views/expenses/bills/edit.blade.php
  resources/views/expenses/bills/show.blade.php
  resources/views/incomes/invoices/create.blade.php
  resources/views/incomes/invoices/edit.blade.php
  resources/views/incomes/invoices/item.blade.php
  resources/views/incomes/invoices/show.blade.php
  resources/views/partials/admin/header.blade.php
  resources/views/partials/portal/header.blade.php
Labels: Enhancement

#947 Admin and portal header sort style updated
  resources/views/partials/admin/header.blade.php
  resources/views/partials/portal/header.blade.php
  resources/views/wizard/currencies/index.blade.php
Labels: Enhancement

#948 Left menu long company name style fixed
  public/css/custom.css
  resources/views/partials/admin/menu.blade.php
  resources/views/partials/portal/menu.blade.php
Labels: Bug

#949 Brazilian translation
  resources/lang/pt-BR/auth.php
  resources/lang/pt-BR/bills.php
  resources/lang/pt-BR/bulk_actions.php
  resources/lang/pt-BR/companies.php
  resources/lang/pt-BR/customers.php
  resources/lang/pt-BR/dashboard.php
  resources/lang/pt-BR/email_templates.php
  resources/lang/pt-BR/general.php
  resources/lang/pt-BR/header.php
  resources/lang/pt-BR/invoices.php
  resources/lang/pt-BR/items.php
  resources/lang/pt-BR/maintenance.php
  resources/lang/pt-BR/messages.php
  resources/lang/pt-BR/modules.php
  resources/lang/pt-BR/pagination.php
  resources/lang/pt-BR/reconciliations.php
  resources/lang/pt-BR/reports.php
  resources/lang/pt-BR/settings.php
  resources/lang/pt-BR/taxes.php
  resources/lang/pt-BR/validation.php
Labels: Enhancement

#950 Hindi translation
  config/language.php
  resources/lang/hi-IN/accounts.php
  resources/lang/hi-IN/auth.php
  resources/lang/hi-IN/bills.php
  resources/lang/hi-IN/bulk_actions.php
  resources/lang/hi-IN/companies.php
  resources/lang/hi-IN/currencies.php
  resources/lang/hi-IN/customers.php
  resources/lang/hi-IN/dashboard.php
  resources/lang/hi-IN/demo.php
  resources/lang/hi-IN/email_templates.php
  resources/lang/hi-IN/errors.php
  resources/lang/hi-IN/footer.php
  resources/lang/hi-IN/general.php
  resources/lang/hi-IN/header.php
  resources/lang/hi-IN/import.php
  resources/lang/hi-IN/install.php
  resources/lang/hi-IN/invoices.php
  resources/lang/hi-IN/items.php
  resources/lang/hi-IN/maintenance.php
  resources/lang/hi-IN/messages.php
  resources/lang/hi-IN/modules.php
  resources/lang/hi-IN/notifications.php
  resources/lang/hi-IN/pagination.php
  resources/lang/hi-IN/passwords.php
  resources/lang/hi-IN/reconciliations.php
  resources/lang/hi-IN/recurring.php
  resources/lang/hi-IN/reports.php
  resources/lang/hi-IN/settings.php
  resources/lang/hi-IN/taxes.php
  resources/lang/hi-IN/transfers.php
  resources/lang/hi-IN/updates.php
  resources/lang/hi-IN/validation.php
Labels: Feature

#951 Diffrent reports status tables updated
  resources/views/partials/reports/chart.blade.php
  resources/views/partials/reports/filter.blade.php
  resources/views/partials/reports/header.blade.php
  resources/views/partials/reports/table.blade.php
  resources/views/reports/profit_loss/content/header.blade.php
  resources/views/reports/profit_loss/table/footer.blade.php
  resources/views/reports/tax_summary/content/header.blade.php
  resources/views/reports/tax_summary/table/footer.blade.php
  resources/views/widgets/cash_flow.blade.php
  resources/views/widgets/expenses_by_category.blade.php
  resources/views/widgets/incomes_by_category.blade.php
Labels: Enhancement

#952 Notifications and save buttons fixed
  public/css/custom.css
  resources/views/partials/admin/navbar.blade.php
  resources/views/partials/form/save_buttons.blade.php
  resources/views/partials/portal/navbar.blade.php
  resources/views/partials/reports/filter.blade.php
Labels: Enhancement

#953 Wizard interface updated
  public/css/custom.css
  resources/views/wizard/companies/edit.blade.php
  resources/views/wizard/currencies/index.blade.php
  resources/views/wizard/finish/index.blade.php
  resources/views/wizard/taxes/index.blade.php
Labels: Enhancement

#956 Forgotten company and user logo added
  public/img/company.png
  public/img/user.png
  resources/views/expenses/bills/bill.blade.php
  resources/views/expenses/bills/show.blade.php
  resources/views/incomes/invoices/invoice.blade.php
  resources/views/incomes/invoices/show.blade.php
  resources/views/layouts/auth.blade.php
  resources/views/modules/item/pre_sale.blade.php
  resources/views/modules/item/show.blade.php
  resources/views/partials/admin/navbar.blade.php
  resources/views/partials/modules/item.blade.php
  resources/views/partials/modules/pre_sale.blade.php
  resources/views/partials/portal/navbar.blade.php
  resources/views/wizard/companies/edit.blade.php
Labels: Enhancement

#957 Reconciliations styles updated
  resources/views/banking/reconciliations/create.blade.php
  resources/views/banking/reconciliations/edit.blade.php
  resources/views/banking/reconciliations/index.blade.php
  resources/views/portal/invoices/signed.blade.php
Labels: Enhancement

#959 Renamed print files
  app/Http/Controllers/Expenses/Bills.php
  app/Http/Controllers/Incomes/Invoices.php
  app/Http/Controllers/Portal/Invoices.php
  app/Http/ViewComposers/Logo.php
  app/Providers/ViewComposer.php
  resources/views/expenses/bills/print.blade.php
  resources/views/expenses/bills/show.blade.php
  resources/views/incomes/invoices/print.blade.php
  resources/views/incomes/invoices/show.blade.php
  resources/views/portal/invoices/invoice.blade.php
  resources/views/portal/invoices/show.blade.php
Labels: Enhancement

#960 Moved menus to listeners
  app/Events/Menu/AdminCreating.php
  app/Events/Menu/PortalCreating.php
  app/Http/Middleware/AdminMenu.php
  app/Http/Middleware/PortalMenu.php
  app/Listeners/Menu/AddAdminItems.php
  app/Listeners/Menu/AddPortalItems.php
  app/Providers/Event.php
Labels: Enhancement

#961 Removed transactions from portal
  app/Http/Controllers/Portal/Payments.php
  app/Http/Controllers/Portal/Transactions.php
  app/Listeners/Menu/AddPortalItems.php
  app/Listeners/Update/V20/Version200.php
  database/seeds/Roles.php
  resources/assets/js/views/portal/transactions.js
  resources/views/portal/payments/index.blade.php
  resources/views/portal/payments/show.blade.php
  resources/views/portal/transactions/index.blade.php
  routes/portal.php
Labels: Enhancement
