Repository akaunting/akaunting, pull requests merged in 2019-03, with the labels that each got.

#751 Closes #688
  app/Http/Controllers/Common/Items.php
  app/Jobs/Expense/CreateBillItem.php
Labels: Bug

#780 Georgian language
  config/language.php
  resources/lang/ka-GE/accounts.php
  resources/lang/ka-GE/auth.php
  resources/lang/ka-GE/bills.php
  resources/lang/ka-GE/companies.php
  resources/lang/ka-GE/currencies.php
  resources/lang/ka-GE/customers.php
  resources/lang/ka-GE/dashboard.php
  resources/lang/ka-GE/demo.php
  resources/lang/ka-GE/errors.php
  resources/lang/ka-GE/footer.php
  resources/lang/ka-GE/general.php
  resources/lang/ka-GE/header.php
  resources/lang/ka-GE/import.php
  resources/lang/ka-GE/install.php
  resources/lang/ka-GE/invoices.php
  resources/lang/ka-GE/items.php
  resources/lang/ka-GE/messages.php
  resources/lang/ka-GE/modules.php
  resources/lang/ka-GE/notifications.php
  resources/lang/ka-GE/pagination.php
  resources/lang/ka-GE/passwords.php
  resources/lang/ka-GE/reconciliations.php
  resources/lang/ka-GE/recurring.php
  resources/lang/ka-GE/reports.php
  resources/lang/ka-GE/settings.php
  resources/lang/ka-GE/taxes.php
  resources/lang/ka-GE/transfers.php
  resources/lang/ka-GE/updates.php
  resources/lang/ka-GE/validation.php
Labels: Feature

#785 Removed APP_URL requirement
  .env.example
  .env.testing
  app/Traits/Modules.php
  app/Traits/SiteApi.php
  app/Utilities/Installer.php
  config/charts.php
  config/filesystems.php
  resources/views/partials/admin/head.blade.php
  resources/views/partials/customer/head.blade.php
  resources/views/partials/link/head.blade.php
  resources/views/partials/modules/head.blade.php
Labels: Enhancement

#802 Japanese language
  config/language.php
  resources/lang/ja-JP/accounts.php
  resources/lang/ja-JP/auth.php
  resources/lang/ja-JP/bills.php
  resources/lang/ja-JP/companies.php
  resources/lang/ja-JP/currencies.php
  resources/lang/ja-JP/customers.php
  resources/lang/ja-JP/dashboard.php
  resources/lang/ja-JP/demo.php
  resources/lang/ja-JP/errors.php
  resources/lang/ja-JP/footer.php
  resources/lang/ja-JP/general.php
  resources/lang/ja-JP/header.php
  resources/lang/ja-JP/import.php
  resources/lang/ja-JP/install.php
  resources/lang/ja-JP/invoices.php
  resources/lang/ja-JP/items.php
  resources/lang/ja-JP/messages.php
  resources/lang/ja-JP/modules.php
  resources/lang/ja-JP/notifications.php
  resources/lang/ja-JP/pagination.php
  resources/lang/ja-JP/passwords.php
  resources/lang/ja-JP/reconciliations.php
  resources/lang/ja-JP/recurring.php
  resources/lang/ja-JP/reports.php
  resources/lang/ja-JP/settings.php
  resources/lang/ja-JP/taxes.php
  resources/lang/ja-JP/transfers.php
  resources/lang/ja-JP/updates.php
  resources/lang/ja-JP/validation.php
Labels: Feature

#803 Updated translations
  resources/lang/ar-SA/bills.php
  resources/lang/pt-BR/demo.php
  resources/lang/pt-BR/errors.php
  resources/lang/pt-BR/invoices.php
  resources/lang/pt-BR/modules.php
  resources/lang/pt-BR/settings.php
  resources/lang/ru-RU/auth.php
  resources/lang/ru-RU/bills.php
  resources/lang/ru-RU/customers.php
  resources/lang/ru-RU/dashboard.php
  resources/lang/ru-RU/errors.php
  resources/lang/ru-RU/general.php
  resources/lang/ru-RU/header.php
  resources/lang/ru-RU/import.php
  resources/lang/ru-RU/invoices.php
  resources/lang/ru-RU/items.php
  resources/lang/ru-RU/messages.php
  resources/lang/ru-RU/modules.php
  resources/lang/ru-RU/reports.php
  resources/lang/ru-RU/settings.php
  resources/lang/ru-RU/validation.php
Labels: Enhancement

#805 closed #804
  .env.example
  app/Http/Controllers/Common/Companies.php
  database/seeds/Settings.php
Labels: Bug
