Repository akaunting/akaunting, pull requests merged in 2019-01, with the labels that each got.

#721 Korean translation
  config/language.php
  resources/lang/ko-KR/accounts.php
  resources/lang/ko-KR/auth.php
  resources/lang/ko-KR/bills.php
  resources/lang/ko-KR/companies.php
  resources/lang/ko-KR/currencies.php
  resources/lang/ko-KR/customers.php
  resources/lang/ko-KR/dashboard.php
  resources/lang/ko-KR/demo.php
  resources/lang/ko-KR/footer.php
  resources/lang/ko-KR/general.php
  resources/lang/ko-KR/header.php
  resources/lang/ko-KR/import.php
  resources/lang/ko-KR/install.php
  resources/lang/ko-KR/invoices.php
  resources/lang/ko-KR/items.php
  resources/lang/ko-KR/messages.php
  resources/lang/ko-KR/modules.php
  resources/lang/ko-KR/notifications.php
  resources/lang/ko-KR/pagination.php
  resources/lang/ko-KR/passwords.php
  resources/lang/ko-KR/reconciliations.php
  resources/lang/ko-KR/recurring.php
  resources/lang/ko-KR/reports.php
  resources/lang/ko-KR/settings.php
  resources/lang/ko-KR/taxes.php
  resources/lang/ko-KR/transfers.php
  resources/lang/ko-KR/updates.php
  resources/lang/ko-KR/validation.php
Labels: Feature

#722 Updated translations
  resources/lang/es-ES/bills.php
  resources/lang/es-ES/general.php
  resources/lang/es-ES/invoices.php
  resources/lang/es-ES/messages.php
  resources/lang/es-ES/modules.php
  resources/lang/es-ES/reconciliations.php
  resources/lang/es-ES/settings.php
  resources/lang/lt-LT/bills.php
  resources/lang/lt-LT/general.php
  resources/lang/lt-LT/invoices.php
  resources/lang/lt-LT/modules.php
  resources/lang/lt-LT/reconciliations.php
  resources/lang/lt-LT/recurring.php
  resources/lang/lt-LT/settings.php
  resources/lang/lt-LT/taxes.php
  resources/lang/lt-LT/validation.php
  resources/lang/nb-NO/general.php
  resources/lang/sq-AL/settings.php
  resources/lang/th-TH/auth.php
  resources/lang/th-TH/bills.php
  resources/lang/th-TH/customers.php
  resources/lang/th-TH/general.php
  resources/lang/th-TH/header.php
  resources/lang/th-TH/invoices.php
  resources/lang/th-TH/messages.php
  resources/lang/th-TH/modules.php
  resources/lang/th-TH/notifications.php
  resources/lang/th-TH/reconciliations.php
  resources/lang/th-TH/settings.php
  resources/lang/th-TH/taxes.php
  resources/lang/th-TH/transfers.php
  resources/lang/th-TH/validation.php
  resources/lang/tr-TR/modules.php
  resources/lang/tr-TR/settings.php
Labels: Enhancement

#728 Updated translations
  resources/lang/it-IT/demo.php
  resources/lang/it-IT/invoices.php
  resources/lang/nb-NO/demo.php
  resources/lang/nb-NO/invoices.php
  resources/lang/sq-AL/demo.php
  resources/lang/sq-AL/invoices.php
  resources/lang/tr-TR/demo.php
  resources/lang/tr-TR/invoices.php
  resources/lang/tr-TR/reconciliations.php
  resources/lang/ur-PK/demo.php
  resources/lang/ur-PK/invoices.php
Labels: Enhancement

#729 Fixed issue #718
  .gitignore
  app/Traits/Currencies.php
Labels: Bug
