Repository akaunting/akaunting, pull requests merged in 2020-06, with the labels that each got.

#1464 Nepali language
  config/language.php
  resources/lang/ne-NP/accounts.php
  resources/lang/ne-NP/auth.php
  resources/lang/ne-NP/bills.php
  resources/lang/ne-NP/bulk_actions.php
  resources/lang/ne-NP/companies.php
  resources/lang/ne-NP/currencies.php
  resources/lang/ne-NP/customers.php
  resources/lang/ne-NP/dashboards.php
  resources/lang/ne-NP/demo.php
  resources/lang/ne-NP/email_templates.php
  resources/lang/ne-NP/errors.php
  resources/lang/ne-NP/footer.php
  resources/lang/ne-NP/general.php
  resources/lang/ne-NP/header.php
  resources/lang/ne-NP/import.php
  resources/lang/ne-NP/install.php
  resources/lang/ne-NP/invoices.php
  resources/lang/ne-NP/items.php
  resources/lang/ne-NP/maintenance.php
  resources/lang/ne-NP/messages.php
  resources/lang/ne-NP/modules.php
  resources/lang/ne-NP/notifications.php
  resources/lang/ne-NP/pagination.php
  resources/lang/ne-NP/passwords.php
  resources/lang/ne-NP/reconciliations.php
  resources/lang/ne-NP/recurring.php
  resources/lang/ne-NP/reports.php
  resources/lang/ne-NP/settings.php
  resources/lang/ne-NP/taxes.php
  resources/lang/ne-NP/transfers.php
  resources/lang/ne-NP/updates.php
  resources/lang/ne-NP/validation.php
  resources/lang/ne-NP/widgets.php
Labels: Feature

#1466 Prevent duplicating document transactions
  app/Models/Banking/Transaction.php
  resources/views/purchases/payments/index.blade.php
  resources/views/sales/revenues/index.blade.php
Labels: Bug

#1467 Missing avatar styling
  public/css/custom.css
  resources/views/auth/users/index.blade.php
  resources/views/partials/admin/navbar.blade.php
Labels: Bug

#1465 Show dynamic component also in portal
  resources/views/partials/portal/content.blade.php
Labels: Enhancement

#1469 Not deleting user related to customer
  app/Jobs/Common/DeleteContact.php
Labels: Bug

#1470 Hide lines w/o money in reports
  resources/views/partials/reports/table.blade.php
  resources/views/partials/reports/table/footer.blade.php
  resources/views/partials/reports/table/rows.blade.php
  resources/views/reports/profit_loss/table/footer.blade.php
  resources/views/reports/tax_summary/table/footer.blade.php
Labels: Enhancement

#1474 Redirect from signed url if user logged in
  app/Http/Kernel.php
  app/Http/Middleware/RedirectSignedIfAuthenticated.php
Labels: Enhancement

#1477 Reconciliations multi currency and calculate fixed.
  app/Models/Banking/Transaction.php
  resources/assets/js/components/AkauntingMoney.vue
  resources/assets/js/views/banking/reconciliations.js
  resources/lang/en-GB/reconciliations.php
  resources/views/banking/reconciliations/create.blade.php
  resources/views/banking/reconciliations/edit.blade.php
  resources/views/partials/form/money_group.blade.php
Labels: Bug

#1480 Invoice/Bill add payment change method..
  app/Http/Controllers/Modals/BillTransactions.php
  app/Http/Controllers/Modals/InvoiceTransactions.php
  resources/assets/js/components/AkauntingModalAddNew.vue
  resources/assets/js/views/purchases/bills.js
  resources/assets/js/views/sales/invoices.js
  resources/views/modals/bills/payment.blade.php
  resources/views/modals/invoices/payment.blade.php
  resources/views/purchases/bills/show.blade.php
  resources/views/sales/invoices/show.blade.php
Labels: Enhancement

#1486 Not able to enable/disable currency and tax in wizard
  app/Http/Middleware/RedirectIfWizardNotCompleted.php
Labels: Bug

#1490 Apps cache key change
  app/Traits/Modules.php
Labels: Enhancement

#1494 Not able to give access only to user profile
  app/Http/Controllers/Auth/Users.php
  resources/views/auth/users/edit.blade.php
  resources/views/partials/admin/navbar.blade.php
Labels: Bug

#1507 Added database transaction to jobs
  app/Jobs/Auth/CreatePermission.php
  app/Jobs/Auth/CreateRole.php
  app/Jobs/Auth/CreateUser.php
  app/Jobs/Auth/DeletePermission.php
  app/Jobs/Auth/DeleteRole.php
  app/Jobs/Auth/DeleteUser.php
  app/Jobs/Auth/UpdatePermission.php
  app/Jobs/Auth/UpdateRole.php
  app/Jobs/Auth/UpdateUser.php
  app/Jobs/Banking/CreateAccount.php
  app/Jobs/Banking/CreateDocumentTransaction.php
  app/Jobs/Banking/CreateReconciliation.php
  app/Jobs/Banking/CreateTransaction.php
  app/Jobs/Banking/CreateTransfer.php
  app/Jobs/Banking/DeleteAccount.php
  app/Jobs/Banking/DeleteReconciliation.php
  app/Jobs/Banking/DeleteTransaction.php
  app/Jobs/Banking/DeleteTransfer.php
  app/Jobs/Banking/UpdateAccount.php
  app/Jobs/Banking/UpdateReconciliation.php
  app/Jobs/Banking/UpdateTransaction.php
  app/Jobs/Banking/UpdateTransfer.php
  app/Jobs/Common/CreateCompany.php
  app/Jobs/Common/CreateContact.php
  app/Jobs/Common/CreateDashboard.php
  app/Jobs/Common/CreateItem.php
  app/Jobs/Common/CreateReport.php
  app/Jobs/Common/DeleteCompany.php
  app/Jobs/Common/DeleteContact.php
  app/Jobs/Common/DeleteDashboard.php
  app/Jobs/Common/DeleteItem.php
  app/Jobs/Common/DeleteReport.php
  app/Jobs/Common/UpdateCompany.php
  app/Jobs/Common/UpdateContact.php
  app/Jobs/Common/UpdateDashboard.php
  app/Jobs/Common/UpdateItem.php
  app/Jobs/Common/UpdateReport.php
  app/Jobs/Purchase/CancelBill.php
  app/Jobs/Purchase/CreateBill.php
  app/Jobs/Purchase/DeleteBill.php
  app/Jobs/Purchase/DuplicateBill.php
  app/Jobs/Purchase/UpdateBill.php
  app/Jobs/Sale/CancelInvoice.php
  app/Jobs/Sale/CreateInvoice.php
  app/Jobs/Sale/DeleteInvoice.php
  app/Jobs/Sale/DuplicateInvoice.php
  app/Jobs/Sale/UpdateInvoice.php
  app/Jobs/Setting/CreateCategory.php
  app/Jobs/Setting/CreateCurrency.php
  app/Jobs/Setting/CreateTax.php
  app/Jobs/Setting/DeleteCategory.php
  app/Jobs/Setting/DeleteCurrency.php
  app/Jobs/Setting/DeleteTax.php
  app/Jobs/Setting/UpdateCategory.php
  app/Jobs/Setting/UpdateCurrency.php
  app/Jobs/Setting/UpdateTax.php
  app/Traits/Jobs.php
Labels: Enhancement

#1508 Added account to payment methods
  app/Abstracts/Http/PaymentController.php
  app/Http/Controllers/Settings/Modules.php
  modules/PaypalStandard/module.json
  resources/views/settings/modules/edit.blade.php
Labels: Enhancement

#1509 Removed php executable finder
  app/Utilities/Console.php
  app/Utilities/Installer.php
  bootstrap/autoload.php
  composer.json
  overrides/Illuminate/Console/Application.php
  resources/lang/en-GB/install.php
Labels: Enhancement
