Repository akaunting/akaunting, pull requests merged in 2020-12, with the labels that each got.

#1680 File group template changes and use drag&drop style
  public/1.js
  public/css/custom.css
  resources/assets/js/mixins/global.js
  resources/views/partials/admin/head.blade.php
  resources/views/partials/admin/scripts.blade.php
  resources/views/partials/form/file_group.blade.php
Labels: Enhancement

#1681 Invoice items columns hide feature
  config/setting.php
  resources/assets/js/mixins/global.js
  resources/lang/en-GB/settings.php
  resources/views/settings/invoice/edit.blade.php
Labels: Feature, Language Change

#1682 Item multiple tax added
  app/Http/Requests/Common/Item.php
  app/Jobs/Common/CreateItem.php
  app/Jobs/Common/CreateItemTaxes.php
  app/Jobs/Common/DeleteItem.php
  app/Jobs/Common/UpdateItem.php
  app/Listeners/Update/V21/Version210.php
  app/Models/Common/Item.php
  app/Models/Common/ItemTax.php
  database/migrations/2020_10_13_000000_core_v210.php
  resources/views/common/items/create.blade.php
  resources/views/common/items/edit.blade.php
Labels: Feature

#1684 Apps install page re-factoring..
  app/Http/Controllers/Modules/Item.php
  app/Traits/Modules.php
  resources/assets/js/views/modules/item.js
  resources/views/modules/item/show.blade.php
  routes/admin.php
Labels: Enhancement, Language Change

#1690 Move some translations of invoice and bill to documents language file
  app/Http/Controllers/Purchases/Bills.php
  app/Http/Controllers/Sales/Invoices.php
  app/Listeners/Document/MarkDocumentCancelled.php
  app/Listeners/Document/MarkDocumentReceived.php
  app/Listeners/Document/MarkDocumentSent.php
  app/Listeners/Document/MarkDocumentViewed.php
  resources/lang/en-GB/bills.php
  resources/lang/en-GB/documents.php
  resources/lang/en-GB/invoices.php
Labels: Language Change

#1693 Add Notification class to DocumentReminded event
  app/Console/Commands/BillReminder.php
  app/Console/Commands/InvoiceReminder.php
  app/Events/Document/DocumentReminded.php
  app/Listeners/Document/SendDocumentReminderNotification.php
  modules/BC21/Events/Purchase/BillReminded.php
  modules/BC21/Events/Sale/InvoiceReminded.php
Labels: Enhancement

#1699 minor bugs fixed
  app/Models/Document/DocumentHistory.php
  app/Models/Document/DocumentItem.php
  app/Models/Document/DocumentItemTax.php
  app/Models/Document/DocumentTotal.php
  resources/assets/js/views/common/documents.js
  resources/views/partials/form/multi_select_add_new_group.blade.php
  resources/views/partials/form/multi_select_group.blade.php
  resources/views/partials/form/multi_select_remote_add_new_group.blade.php
  resources/views/partials/form/multi_select_remote_group.blade.php
  resources/views/partials/form/select_add_new_group.blade.php
  resources/views/partials/form/select_group.blade.php
  resources/views/partials/form/select_group_add_new_group.blade.php
  resources/views/partials/form/select_group_group.blade.php
  resources/views/partials/form/select_remote_add_new_group.blade.php
  resources/views/partials/form/select_remote_group.blade.php
Labels: Enhancement

#1702 Handle a possible issue with orphaned 'document_item_taxes' while upg…
  app/Listeners/Update/V21/Version210.php
Labels: Bug

#1705 Fix a typo.
  app/Abstracts/View/Components/DocumentIndex.php
  resources/views/components/documents/form/content.blade.php
  resources/views/components/documents/form/main.blade.php
  resources/views/components/documents/index/card-body.blade.php
  resources/views/components/documents/index/content.blade.php
Labels: Enhancement

#1706 Fix a width of a column with a document number.
  app/Abstracts/View/Components/DocumentIndex.php
Labels: Bug

#1707 dynamic options feature is added to akaunting-select components
  resources/assets/js/components/AkauntingSelect.vue
  resources/assets/js/components/AkauntingSelectRemote.vue
  resources/views/partials/form/multi_select_add_new_group.blade.php
  resources/views/partials/form/multi_select_group.blade.php
  resources/views/partials/form/multi_select_remote_add_new_group.blade.php
  resources/views/partials/form/multi_select_remote_group.blade.php
  resources/views/partials/form/select_add_new_group.blade.php
  resources/views/partials/form/select_group.blade.php
  resources/views/partials/form/select_group_add_new_group.blade.php
  resources/views/partials/form/select_group_group.blade.php
  resources/views/partials/form/select_remote_add_new_group.blade.php
  resources/views/partials/form/select_remote_group.blade.php
Labels: Enhancement
