Repository akaunting/akaunting, pull requests merged in 2020-08, with the labels that each got.

#1557 Use fallback for default settings
  app/Http/Controllers/Common/Items.php
  app/Http/Controllers/Modals/Items.php
  app/Http/Controllers/Sales/Invoices.php
  app/Http/Controllers/Settings/Company.php
  app/Http/Controllers/Settings/Defaults.php
  app/Http/Controllers/Settings/Email.php
  app/Http/Controllers/Settings/Invoice.php
  app/Http/Controllers/Settings/Localisation.php
  app/Http/Controllers/Settings/Schedule.php
  app/Traits/Currencies.php
  composer.json
  composer.lock
  config/setting.php
  database/seeds/Settings.php
  database/seeds/TestCompany.php
  resources/views/modals/settings/invoice_template.blade.php
  resources/views/settings/company/edit.blade.php
  resources/views/settings/default/edit.blade.php
  resources/views/settings/email/edit.blade.php
  resources/views/settings/invoice/edit.blade.php
  resources/views/settings/localisation/edit.blade.php
  resources/views/settings/schedule/edit.blade.php
Labels: Enhancement

#1561 Added withholding option to tax report
  app/Reports/TaxSummary.php
  resources/views/common/reports/edit.blade.php
Labels: Feature

#1564 Remove empty spaces in show invoice view
  app/Providers/Macro.php
  resources/views/sales/invoices/show.blade.php
Labels: Enhancement

#1568 replace url to route
  app/Http/Controllers/Api/Auth/Permissions.php
  app/Http/Controllers/Api/Auth/Roles.php
  app/Http/Controllers/Api/Auth/Users.php
  app/Http/Controllers/Api/Banking/Accounts.php
  app/Http/Controllers/Api/Banking/Reconciliations.php
  app/Http/Controllers/Api/Banking/Transactions.php
  app/Http/Controllers/Api/Banking/Transfers.php
  app/Http/Controllers/Api/Common/Companies.php
  app/Http/Controllers/Api/Common/Contacts.php
  app/Http/Controllers/Api/Common/Items.php
  app/Http/Controllers/Api/Common/Reports.php
  app/Http/Controllers/Api/Purchases/Bills.php
  app/Http/Controllers/Api/Sales/Invoices.php
  app/Http/Controllers/Api/Settings/Categories.php
  app/Http/Controllers/Api/Settings/Currencies.php
  app/Http/Controllers/Api/Settings/Settings.php
  app/Http/Controllers/Api/Settings/Taxes.php
  app/Http/Controllers/Common/Search.php
  app/Http/ViewComposers/Notifications.php
  app/Listeners/Update/V20/Version200.php
  app/Notifications/Auth/Reset.php
  app/Traits/SiteApi.php
  app/Utilities/Overrider.php
  resources/views/partials/media/file.blade.php
  resources/views/wizard/companies/edit.blade.php
  resources/views/wizard/currencies/index.blade.php
  resources/views/wizard/finish/index.blade.php
  resources/views/wizard/taxes/index.blade.php
Labels: Enhancement

#1572 Module item show page added multi support categories.
  resources/views/modules/item/pre_sale.blade.php
  resources/views/modules/item/show.blade.php
Labels: Enhancement

#1580 Fixed issue #1554 Item autocomplete/search not working in invoice/bill
  resources/assets/js/components/AkauntingSelectRemote.vue
  resources/views/purchases/bills/item.blade.php
  resources/views/sales/invoices/item.blade.php
Labels: Bug

#1583 Hotfixed typo in file partial.
  resources/views/partials/media/file.blade.php
Labels: Bug
