Repository akaunting/akaunting, pull requests merged in 2020-04, with the labels that each got.

#1389 fix: adding discount_amounth_total for empty items on invoice creation
  app/Jobs/Sale/CreateInvoice.php
Labels: Bug

#1396 Refactored portal dashboard
  app/Http/Controllers/Portal/Dashboard.php
  resources/views/portal/dashboard/index.blade.php
Labels: Enhancement

#1397 Added customer and vendor scopes
  app/Http/Controllers/Common/Search.php
  app/Http/Controllers/Purchases/Bills.php
  app/Http/Controllers/Purchases/Payments.php
  app/Http/Controllers/Purchases/Vendors.php
  app/Http/Controllers/Sales/Customers.php
  app/Http/Controllers/Sales/Invoices.php
  app/Http/Controllers/Sales/Revenues.php
  app/Models/Common/Contact.php
Labels: Feature

#1404 Fixed recurring reflection for bills
  app/Utilities/Recurring.php
Labels: Bug

#1375 Don't overwrite the bg-variant mixin
  package.json
  resources/assets/sass/core/mixins/_background-variant.scss
Labels: Enhancement

#1412 Show invoice/bill totals sorted
  app/Abstracts/DocumentModel.php
  app/Http/Controllers/Purchases/Bills.php
  app/Http/Controllers/Sales/Invoices.php
  resources/views/portal/invoices/show.blade.php
  resources/views/portal/invoices/signed.blade.php
  resources/views/purchases/bills/print.blade.php
  resources/views/purchases/bills/show.blade.php
  resources/views/sales/invoices/print_classic.blade.php
  resources/views/sales/invoices/print_default.blade.php
  resources/views/sales/invoices/print_modern.blade.php
  resources/views/sales/invoices/show.blade.php
Labels: Enhancement

#1413 Added invoice/bill number to pdf filename
  app/Http/Controllers/Purchases/Bills.php
  app/Http/Controllers/Sales/Invoices.php
  app/Traits/Purchases.php
  app/Traits/Sales.php
Labels: Feature

#1415 Updated translations
  resources/lang/bn-BD/install.php
  resources/lang/de-DE/install.php
  resources/lang/hi-IN/bills.php
  resources/lang/hi-IN/bulk_actions.php
  resources/lang/hi-IN/install.php
  resources/lang/hi-IN/invoices.php
  resources/lang/hi-IN/settings.php
  resources/lang/hr-HR/bills.php
  resources/lang/hr-HR/bulk_actions.php
  resources/lang/hr-HR/general.php
  resources/lang/hr-HR/install.php
  resources/lang/hr-HR/invoices.php
  resources/lang/hr-HR/messages.php
  resources/lang/hr-HR/passwords.php
  resources/lang/hr-HR/reports.php
  resources/lang/hr-HR/settings.php
  resources/lang/hr-HR/validation.php
  resources/lang/hr-HR/widgets.php
  resources/lang/id-ID/auth.php
  resources/lang/id-ID/bills.php
  resources/lang/id-ID/bulk_actions.php
  resources/lang/id-ID/companies.php
  resources/lang/id-ID/customers.php
  resources/lang/id-ID/dashboards.php
  resources/lang/id-ID/demo.php
  resources/lang/id-ID/email_templates.php
  resources/lang/id-ID/errors.php
  resources/lang/id-ID/general.php
  resources/lang/id-ID/install.php
  resources/lang/id-ID/invoices.php
  resources/lang/id-ID/maintenance.php
  resources/lang/id-ID/messages.php
  resources/lang/id-ID/modules.php
  resources/lang/id-ID/pagination.php
  resources/lang/id-ID/passwords.php
  resources/lang/id-ID/reconciliations.php
  resources/lang/id-ID/reports.php
  resources/lang/id-ID/settings.php
  resources/lang/id-ID/taxes.php
  resources/lang/id-ID/validation.php
  resources/lang/id-ID/widgets.php
  resources/lang/it-IT/install.php
  resources/lang/ja-JP/bills.php
  resources/lang/ja-JP/bulk_actions.php
  resources/lang/ja-JP/install.php
  resources/lang/ja-JP/invoices.php
  resources/lang/ja-JP/messages.php
  resources/lang/ja-JP/passwords.php
  resources/lang/ja-JP/settings.php
  resources/lang/ja-JP/validation.php
  resources/lang/pt-BR/install.php
  resources/lang/sq-AL/bills.php
  resources/lang/sq-AL/bulk_actions.php
  resources/lang/sq-AL/install.php
  resources/lang/sq-AL/invoices.php
  resources/lang/sq-AL/settings.php
  resources/lang/tr-TR/email_templates.php
  resources/lang/tr-TR/install.php
Labels: Enhancement

#1417 Fix: wizard currency
  app/Http/Controllers/Settings/Currencies.php
  resources/views/partials/wizard/content.blade.php
  resources/views/wizard/currencies/index.blade.php
Labels: Bug

#1426 Prevent CSV injection
  app/Abstracts/Export.php
Labels: Security
