Repository akaunting/akaunting, pull requests merged in 2020-11, with the labels that each got.

#1654 path of ManagesStacks.php is fixed
  overrides/Illuminate/View/Concerns/ManagesStacks.php
Labels: Bug

#1655 Added Sales & Purchases default category
  app/Http/Controllers/Settings/Defaults.php
  app/Listeners/Update/V21/Version210.php
  database/seeds/Categories.php
  resources/lang/en-GB/settings.php
  resources/views/purchases/bills/create.blade.php
  resources/views/purchases/payments/create.blade.php
  resources/views/sales/invoices/create.blade.php
  resources/views/sales/revenues/create.blade.php
  resources/views/settings/default/edit.blade.php
Labels: Enhancement, Language Change

#1656 Change default category prefix sales to income, purchases to expense
  app/Listeners/Update/V21/Version210.php
  database/seeds/Categories.php
  resources/lang/en-GB/settings.php
  resources/views/purchases/bills/create.blade.php
  resources/views/purchases/payments/create.blade.php
  resources/views/sales/invoices/create.blade.php
  resources/views/sales/revenues/create.blade.php
  resources/views/settings/default/edit.blade.php
Labels: Enhancement, Language Change

#1658 Fix icon of money inputs
  resources/assets/js/components/AkauntingMoney.vue
Labels: Bug

#1661 Fix transaction not visible when paid on the end date of a reconciliation
  app/Http/Controllers/Banking/Reconciliations.php
Labels: Bug

#1660 Use all income types for reconciliations
  resources/views/banking/reconciliations/create.blade.php
  resources/views/banking/reconciliations/edit.blade.php
Labels: Enhancement

#1663 scopes are added for InvoiceTotal and BillTotal models
  app/Models/Purchase/BillTotal.php
  app/Models/Sale/InvoiceTotal.php
Labels: Enhancement

#1657 Search & Filter enhancement feature..
  app/Http/Controllers/Common/BulkActions.php
  app/View/Components/SearchString.php
  config/search-string.php
  public/css/custom.css
  public/vendor/js-cookie/js.cookie.js
  resources/assets/js/components/AkauntingSearch.vue
  resources/assets/js/views/auth/roles.js
  resources/lang/en-GB/general.php
  resources/lang/en-GB/search_string.php
  resources/views/auth/permissions/index.blade.php
  resources/views/auth/roles/index.blade.php
  resources/views/auth/users/index.blade.php
  resources/views/banking/accounts/index.blade.php
  resources/views/banking/reconciliations/index.blade.php
  resources/views/banking/transactions/index.blade.php
  resources/views/banking/transfers/index.blade.php
  resources/views/common/companies/index.blade.php
  resources/views/common/dashboards/index.blade.php
  resources/views/common/items/index.blade.php
  resources/views/components/search-string.blade.php
  resources/views/purchases/bills/index.blade.php
  resources/views/purchases/payments/index.blade.php
  resources/views/purchases/vendors/index.blade.php
  resources/views/sales/customers/index.blade.php
  resources/views/sales/invoices/index.blade.php
  resources/views/sales/revenues/index.blade.php
  resources/views/settings/categories/index.blade.php
  resources/views/settings/currencies/index.blade.php
  resources/views/settings/taxes/index.blade.php
Labels: Enhancement, Language Change

#1672 message error is fixed
  app/Jobs/Setting/UpdateTax.php
Labels: Bug

#1673 Invoice columns name changed
  resources/assets/js/plugins/form.js
  resources/views/partials/form/invoice_text.blade.php
Labels: Enhancement
