Repository akaunting/akaunting, pull requests merged in 2020-01, with the labels that each got.

#1064 Element style added for components
  public/css/akaunting-color.css
  public/css/custom.css
  public/css/element.css
  resources/assets/js/plugins/dashboard-plugin.js
  resources/views/partials/admin/head.blade.php
  resources/views/partials/auth/head.blade.php
  resources/views/partials/install/head.blade.php
  resources/views/partials/modules/head.blade.php
  resources/views/partials/portal/head.blade.php
  resources/views/partials/signed/head.blade.php
  resources/views/partials/wizard/head.blade.php
Labels: Code Style, Enhancement

#1054 value parameter is fixed on select group
  resources/views/partials/form/select_group.blade.php
Labels: Bug

#1065 Dashboard widget headers dynamically updated
  resources/views/partials/widgets/standard_header.blade.php
  resources/views/widgets/account_balance.blade.php
  resources/views/widgets/cash_flow.blade.php
  resources/views/widgets/expenses_by_category.blade.php
  resources/views/widgets/income_by_category.blade.php
  resources/views/widgets/latest_expenses.blade.php
  resources/views/widgets/latest_income.blade.php
  resources/views/widgets/total_expenses.blade.php
  resources/views/widgets/total_income.blade.php
  resources/views/widgets/total_profit.blade.php
Labels: Code Style, Enhancement

#1066 Card view updated
  resources/assets/js/components/CreditCard/CardForm.vue
Labels: Code Style

#1068 Add discount style updated
  resources/views/purchases/bills/create.blade.php
  resources/views/purchases/bills/edit.blade.php
  resources/views/sales/invoices/create.blade.php
  resources/views/sales/invoices/edit.blade.php
Labels: Code Style, Enhancement

#1069 Responsive problems fixed for some tables
  resources/views/auth/roles/create.blade.php
  resources/views/auth/roles/edit.blade.php
  resources/views/auth/roles/index.blade.php
  resources/views/auth/users/index.blade.php
  resources/views/banking/accounts/index.blade.php
Labels: Code Style, Enhancement

#1070 Tooltips added for dashboard status
  public/css/custom.css
  public/css/element.css
  resources/assets/js/views/common/dashboard.js
  resources/assets/js/views/portal/dashboard.js
  resources/views/portal/dashboard/index.blade.php
  resources/views/widgets/total_expenses.blade.php
  resources/views/widgets/total_income.blade.php
  resources/views/widgets/total_profit.blade.php
Labels: Code Style, Enhancement

#1071 Left menu scroll problem fixed
  public/css/custom.css
  resources/views/partials/admin/menu.blade.php
Labels: Code Style, Enhancement

#1072 Short company name dropdown menu problem fixed
  public/css/custom.css
Labels: Code Style, Enhancement

#1077 Portal profile form updated to vue form
  resources/assets/js/views/portal/profile.js
  resources/views/portal/profile/edit.blade.php
Labels: Code Style, Enhancement

#1078 Portal payment search js path updated
  resources/views/portal/invoices/index.blade.php
  resources/views/portal/payments/index.blade.php
Labels: Code Style, Enhancement

#1081 Widget permissions
  app/Abstracts/Report.php
  app/Http/Controllers/Common/Dashboard.php
  app/Http/Controllers/Common/Reports.php
  app/Listeners/Update/V20/Version200.php
  app/Utilities/Reports.php
  app/Utilities/Widgets.php
  database/seeds/Roles.php
  resources/views/auth/roles/create.blade.php
  resources/views/auth/roles/edit.blade.php
Labels: Feature

#1082 Delay time lowered
  resources/views/portal/dashboard/index.blade.php
  resources/views/widgets/total_expenses.blade.php
  resources/views/widgets/total_income.blade.php
  resources/views/widgets/total_profit.blade.php
Labels: Enhancement

#1083 Tooltip colors changed
  resources/views/portal/dashboard/index.blade.php
  resources/views/widgets/total_expenses.blade.php
  resources/views/widgets/total_income.blade.php
  resources/views/widgets/total_profit.blade.php
Labels: Code Style, Enhancement

#1084 Charts tooltip style updated
  app/Http/Controllers/Portal/Dashboard.php
  app/Http/ViewComposers/Logo.php
Labels: Code Style, Enhancement

#1085 All tooltip styles updated
  app/Traits/Charts.php
  public/css/element.css
  resources/views/portal/dashboard/index.blade.php
  resources/views/widgets/total_expenses.blade.php
  resources/views/widgets/total_income.blade.php
  resources/views/widgets/total_profit.blade.php
Labels: Code Style, Enhancement

#1086 Email tag styles updated
  public/css/akaunting-color.css
  public/css/custom.css
  resources/views/modals/settings/invoice_template.blade.php
  resources/views/partials/admin/menu.blade.php
  resources/views/partials/modules/item.blade.php
  resources/views/partials/portal/menu.blade.php
  resources/views/sales/invoices/print_classic.blade.php
  resources/views/settings/email/edit.blade.php
Labels: Code Style, Enhancement

#1087 Some placeholders updated
  resources/views/partials/form/email_group.blade.php
  resources/views/partials/form/invoice_text.blade.php
  resources/views/partials/form/number_group.blade.php
  resources/views/partials/form/password_group.blade.php
  resources/views/settings/currencies/create.blade.php
  resources/views/settings/currencies/edit.blade.php
Labels: Code Style, Enhancement

#1088 Fix Import Page title for modules
  resources/views/common/import/create.blade.php
Labels: Bug

#1089 Missing Contact Phone header in Bill and Invoice export file
  app/Exports/Purchases/Sheets/Bills.php
  app/Exports/Sales/Sheets/Invoices.php
Labels: Bug

#1090 Module permissions for reports/settings/widgets
  app/Http/Controllers/Settings/Modules.php
  app/Http/Controllers/Settings/Settings.php
  app/Listeners/Update/V20/Version200.php
  app/Utilities/Reports.php
  app/Utilities/Widgets.php
  database/seeds/Roles.php
  modules/OfflinePayments/Http/Controllers/Settings.php
  modules/OfflinePayments/Listeners/ShowSetting.php
  modules/OfflinePayments/Resources/views/edit.blade.php
  modules/OfflinePayments/Routes/admin.php
  resources/views/settings/modules/edit.blade.php
  resources/views/settings/settings/index.blade.php
  routes/admin.php
Labels: Enhancement

#1092 Improved factories and tests
  database/factories/Account.php
  database/factories/Contact.php
  database/factories/Item.php
  database/factories/Transaction.php
  database/factories/User.php
  tests/Feature/Auth/UsersTest.php
  tests/Feature/Banking/AccountsTest.php
  tests/Feature/Banking/TransfersTest.php
  tests/Feature/Common/ItemsTest.php
  tests/Feature/Purchases/PaymentsTest.php
  tests/Feature/Purchases/VendorsTest.php
  tests/Feature/Sales/CustomersTest.php
  tests/Feature/Sales/RevenuesTest.php
Labels: Enhancement

#1094 Print template pdf problem solved
  public/css/custom.css
  public/css/print.css
  resources/views/layouts/print.blade.php
  resources/views/partials/print/head.blade.php
  resources/views/sales/invoices/print_classic.blade.php
  resources/views/sales/invoices/print_default.blade.php
  resources/views/sales/invoices/print_modern.blade.php
Labels: Code Style, Enhancement

#1097 Print template color feature added
  app/Models/Sale/Invoice.php
  public/css/custom.css
  public/css/element.css
  resources/assets/js/views/settings/categories.js
  resources/assets/js/views/settings/settings.js
  resources/views/modals/settings/invoice_template.blade.php
  resources/views/sales/invoices/print_classic.blade.php
  resources/views/sales/invoices/print_default.blade.php
  resources/views/sales/invoices/print_modern.blade.php
  resources/views/settings/categories/create.blade.php
Labels: Code Style, Enhancement, Feature

#1098 Wizard save button style updated
  resources/views/wizard/companies/edit.blade.php
  resources/views/wizard/currencies/index.blade.php
  resources/views/wizard/finish/index.blade.php
  resources/views/wizard/taxes/index.blade.php
Labels: Code Style, Enhancement

#1099 Unnecessary classes deleted
  resources/views/common/reports/index.blade.php
  resources/views/install/updates/edit.blade.php
  resources/views/modules/home/index.blade.php
  resources/views/modules/item/documentation.blade.php
  resources/views/modules/item/pre_sale.blade.php
  resources/views/modules/item/show.blade.php
  resources/views/modules/my/index.blade.php
  resources/views/modules/tiles/index.blade.php
  resources/views/portal/invoices/signed.blade.php
Labels: Code Style, Enhancement

#1100 Code review for vue installation files
  resources/assets/js/views/install/Database.vue
  resources/assets/js/views/install/Language.vue
  resources/assets/js/views/install/Settings.vue
Labels: Code Style, Enhancement

#1101 Dynamic email templates
  app/Http/Controllers/Settings/Email.php
  app/Models/Common/EmailTemplate.php
  database/migrations/2020_01_08_000000_core_v200.php
  database/seeds/EmailTemplates.php
  resources/views/settings/email/edit.blade.php
Labels: Feature

#1102 Line spaces deleting in email editor
  resources/lang/en-GB/email_templates.php
Labels: Code Style, Enhancement, Language Change

#1103 Print template color picker alignment updated
  public/css/element.css
  resources/views/modals/settings/invoice_template.blade.php
Labels: Code Style, Enhancement

#1107 Menu dropdown text problem fixed
  public/css/custom.css
  resources/views/partials/admin/menu.blade.php
Labels: Code Style, Enhancement

#1108 Cashflow date filter fix
  app/Widgets/CashFlow.php
Labels: Bug

#1111 Portal payment page view updated
  app/Http/Controllers/Portal/Profile.php
  public/css/akaunting-color.css
  public/css/custom.css
  resources/views/portal/payments/show.blade.php
Labels: Code Style, Enhancement

#1112 Portal profile value problem fixed
  resources/views/portal/profile/edit.blade.php
Labels: Bug, Code Style, Enhancement

#1115 Unnecessary class deleted
  public/css/custom.css
  resources/assets/js/components/AkauntingSearch.vue
  resources/views/partials/admin/pagination.blade.php
  resources/views/partials/modules/bar.blade.php
  resources/views/partials/portal/pagination.blade.php
  resources/views/partials/reports/filter.blade.php
Labels: Code Style, Enhancement

#1116 Report alignment and big test values fixed
  public/css/custom.css
  resources/views/partials/reports/header.blade.php
  resources/views/partials/reports/table.blade.php
  resources/views/partials/reports/table/footer.blade.php
  resources/views/partials/reports/table/rows.blade.php
  resources/views/reports/profit_loss/content/footer.blade.php
  resources/views/reports/profit_loss/content/header.blade.php
  resources/views/reports/profit_loss/table/footer.blade.php
  resources/views/reports/profit_loss/table/header.blade.php
  resources/views/reports/tax_summary/content/header.blade.php
  resources/views/reports/tax_summary/table/footer.blade.php
  resources/views/sales/invoices/item.blade.php
Labels: Bug, Code Style, Enhancement

#1117 Money alignment is updated
  public/css/custom.css
  resources/views/partials/reports/table/footer.blade.php
  resources/views/partials/reports/table/header.blade.php
  resources/views/partials/reports/table/rows.blade.php
  resources/views/reports/profit_loss/content/footer.blade.php
  resources/views/reports/profit_loss/content/header.blade.php
  resources/views/reports/profit_loss/table/footer.blade.php
  resources/views/reports/tax_summary/content/header.blade.php
  resources/views/reports/tax_summary/table/footer.blade.php
Labels: Code Style, Enhancement

#1118 Paid row color updated
  resources/views/purchases/bills/show.blade.php
  resources/views/sales/invoices/show.blade.php
Labels: Enhancement

#1119 Report header alignment updated
  resources/views/partials/reports/table/header.blade.php
  resources/views/reports/profit_loss/content/header.blade.php
  resources/views/reports/tax_summary/content/header.blade.php
Labels: Enhancement

#1120 Alignment of numeric values
  resources/views/auth/users/index.blade.php
  resources/views/banking/accounts/index.blade.php
  resources/views/common/items/index.blade.php
  resources/views/purchases/bills/index.blade.php
  resources/views/purchases/bills/show.blade.php
  resources/views/purchases/payments/index.blade.php
  resources/views/purchases/vendors/index.blade.php
  resources/views/sales/customers/index.blade.php
  resources/views/sales/invoices/index.blade.php
  resources/views/sales/invoices/show.blade.php
  resources/views/sales/revenues/index.blade.php
Labels: Code Style, Enhancement

#1121 Content layout width updated
  public/css/custom.css
Labels: Enhancement

#1122 Some component usage updated
  resources/assets/js/views/modules/item.js
  resources/assets/js/views/portal/dashboard.js
  resources/assets/js/views/settings/categories.js
Labels: Code Style, Enhancement

#1123 App comment view updated
  public/css/custom.css
  resources/views/partials/modules/reviews.blade.php
Labels: Code Style, Enhancement

#1124 App carousel size problem fixed
  resources/assets/js/components/AkauntingCarousel.vue
Labels: Bug, Enhancement

#1125 Anchor colors added
  resources/views/modules/item/show.blade.php
Labels: Code Style, Enhancement

#1126 Chart alignment updated
  resources/views/partials/reports/table.blade.php
  resources/views/widgets/line_chart.blade.php
Labels: Code Style, Enhancement

#1127 Column size updated for invoice, account
  resources/views/banking/accounts/index.blade.php
  resources/views/sales/invoices/index.blade.php
Labels: Code Style

#1128 Main charts alignment updated
  resources/views/portal/dashboard/index.blade.php
  resources/views/widgets/line_chart.blade.php
Labels: Code Style, Enhancement

#1130 Updated vue wizard
  public/css/element.css
  resources/assets/js/views/wizard/company.js
  resources/assets/js/views/wizard/currencies.js
  resources/assets/js/views/wizard/finish.js
  resources/assets/js/views/wizard/taxes.js
  resources/views/partials/wizard/steps.blade.php
  resources/views/wizard/companies/edit.blade.php
  resources/views/wizard/currencies/index.blade.php
  resources/views/wizard/finish/index.blade.php
  resources/views/wizard/taxes/index.blade.php
Labels: Bug, Code Style, Enhancement

#1132 Forgotten install step line style
  public/css/element.css
Labels: Code Style, Enhancement

#1133 Fixed tests
  resources/views/partials/wizard/steps.blade.php
Labels: Bug, Code Style, Enhancement

#1134 Unnecessary control and responsive are fixed
  resources/assets/js/views/install/Database.vue
  resources/assets/js/views/install/Language.vue
  resources/assets/js/views/install/Settings.vue
  resources/assets/js/views/wizard/company.js
  resources/assets/js/views/wizard/currencies.js
  resources/assets/js/views/wizard/finish.js
  resources/assets/js/views/wizard/taxes.js
  resources/views/wizard/currencies/index.blade.php
  resources/views/wizard/finish/index.blade.php
  resources/views/wizard/taxes/index.blade.php
Labels: Code Style, Enhancement

#1135 Report fields
  app/Abstracts/Report.php
  app/Console/Stubs/Modules/scaffold/provider.stub
  app/Http/Controllers/Common/Reports.php
  app/Listeners/Update/V20/Version200.php
  app/Models/Common/Report.php
  app/Reports/ExpenseSummary.php
  app/Reports/IncomeExpenseSummary.php
  app/Reports/IncomeSummary.php
  app/Reports/ProfitLoss.php
  app/Reports/TaxSummary.php
  app/Utilities/Reports.php
  database/migrations/2020_01_08_000000_core_v200.php
  database/seeds/Reports.php
  resources/lang/en-GB/demo.php
  resources/views/common/reports/create.blade.php
  resources/views/common/reports/edit.blade.php
  resources/views/partials/reports/fields.blade.php
  resources/views/partials/reports/filter.blade.php
  resources/views/partials/reports/header.blade.php
  resources/views/partials/reports/print.blade.php
  resources/views/partials/reports/show.blade.php
  resources/views/partials/reports/table/header.blade.php
  routes/admin.php
Labels: Enhancement

#1136 Reports print view updated
  public/css/print.css
  resources/views/layouts/print.blade.php
  resources/views/partials/reports/header.blade.php
  resources/views/partials/reports/print.blade.php
  resources/views/partials/reports/table.blade.php
  resources/views/partials/reports/table/rows.blade.php
  resources/views/reports/profit_loss/content/footer.blade.php
  resources/views/reports/profit_loss/content/header.blade.php
  resources/views/reports/profit_loss/table/footer.blade.php
  resources/views/reports/profit_loss/table/header.blade.php
  resources/views/reports/tax_summary/content/header.blade.php
  resources/views/reports/tax_summary/table/footer.blade.php
  resources/views/reports/tax_summary/table/header.blade.php
Labels: Code Style, Enhancement

#1137 Model caching
  app/Abstracts/Model.php
  composer.json
  composer.lock
  config/laravel-model-caching.php
Labels: Enhancement

#1138 Report print updated
  public/css/print.css
  resources/views/partials/reports/table.blade.php
  resources/views/partials/reports/table/footer.blade.php
  resources/views/partials/reports/table/rows.blade.php
  resources/views/reports/profit_loss/content/footer.blade.php
  resources/views/reports/profit_loss/content/header.blade.php
  resources/views/reports/profit_loss/table/footer.blade.php
  resources/views/reports/tax_summary/content/header.blade.php
  resources/views/reports/tax_summary/table/footer.blade.php
Labels: Code Style, Enhancement

#1139 Missing sample import files
  app/Exports/Banking/Transactions.php
  app/Exports/Common/Items.php
  app/Exports/Common/Reports.php
  app/Exports/Purchases/Bills.php
  app/Exports/Purchases/Payments.php
  app/Exports/Purchases/Sheets/BillItemTaxes.php
  app/Exports/Purchases/Sheets/BillItems.php
  app/Exports/Purchases/Sheets/BillTotals.php
  app/Exports/Purchases/Sheets/BillTransactions.php
  app/Exports/Purchases/Sheets/Bills.php
  app/Exports/Purchases/Vendors.php
  app/Exports/Sales/Customers.php
  app/Exports/Sales/Invoices.php
  app/Exports/Sales/Revenues.php
  app/Exports/Sales/Sheets/InvoiceItemTaxes.php
  app/Exports/Sales/Sheets/InvoiceItems.php
  app/Exports/Sales/Sheets/InvoiceTotals.php
  app/Exports/Sales/Sheets/InvoiceTransactions.php
  app/Exports/Sales/Sheets/Invoices.php
  database/migrations/2020_01_08_000000_core_v200.php
  public/files/import/bills.xlsx
  public/files/import/customers.xlsx
  public/files/import/invoices.xlsx
  public/files/import/items.xlsx
  public/files/import/payments.xlsx
  public/files/import/revenues.xlsx
  public/files/import/transactions.xlsx
  public/files/import/vendors.xlsx
Labels: Bug

#1141 Print report total position
  resources/views/partials/reports/table/footer.blade.php
Labels: Enhancement

#1142 Unnecessary contact trait path
  app/Traits/Contacts.php
Labels: Code Style, Enhancement

#1143 Empty page button large style deleted
  resources/views/partials/admin/empty_page.blade.php
Labels: Enhancement

#1144 Unnecessary paths deleted, path updated to upper
  app/Exports/Purchases/Sheets/BillItems.php
  app/Http/Controllers/Portal/Payments.php
Labels: Code Style, Enhancement

#1145 Unnecessary artisan usage
  app/Http/Controllers/Install/Database.php
  app/Http/Controllers/Modules/Item.php
Labels: Enhancement

#1146 Transaction button responsive updated
  resources/views/banking/transactions/index.blade.php
Labels: Code Style, Enhancement

#1148 Human friendly invoice import/export
  app/Abstracts/Import.php
  app/Exports/Sales/Sheets/InvoiceHistories.php
  app/Exports/Sales/Sheets/InvoiceItemTaxes.php
  app/Exports/Sales/Sheets/InvoiceItems.php
  app/Exports/Sales/Sheets/InvoiceTotals.php
  app/Exports/Sales/Sheets/InvoiceTransactions.php
  app/Exports/Sales/Sheets/Invoices.php
  app/Http/Requests/Sale/InvoiceItemTax.php
  app/Imports/Sales/Invoices.php
  app/Imports/Sales/Sheets/InvoiceHistories.php
  app/Imports/Sales/Sheets/InvoiceItemTaxes.php
  app/Imports/Sales/Sheets/InvoiceItems.php
  app/Imports/Sales/Sheets/InvoiceTotals.php
  app/Imports/Sales/Sheets/InvoiceTranactions.php
  app/Imports/Sales/Sheets/InvoiceTransactions.php
  app/Imports/Sales/Sheets/Invoices.php
  app/Models/Banking/Account.php
  app/Models/Common/Contact.php
  app/Models/Common/Item.php
  app/Models/Sale/Invoice.php
  app/Models/Sale/InvoiceItem.php
  app/Models/Sale/InvoiceItemTax.php
  app/Models/Setting/Category.php
  app/Models/Setting/Tax.php
  composer.json
  composer.lock
  public/files/import/invoices.xlsx
Labels: Enhancement

#1149 Human friendly import/export
  app/Abstracts/Import.php
  app/Exports/Banking/Transactions.php
  app/Exports/Common/Items.php
  app/Exports/Purchases/Payments.php
  app/Exports/Purchases/Sheets/BillHistories.php
  app/Exports/Purchases/Sheets/BillItemTaxes.php
  app/Exports/Purchases/Sheets/BillItems.php
  app/Exports/Purchases/Sheets/BillTotals.php
  app/Exports/Purchases/Sheets/BillTransactions.php
  app/Exports/Purchases/Sheets/Bills.php
  app/Exports/Sales/Revenues.php
  app/Http/Requests/Purchase/BillItemTax.php
  app/Imports/Banking/Transactions.php
  app/Imports/Common/Items.php
  app/Imports/Purchases/Payments.php
  app/Imports/Purchases/Sheets/BillHistories.php
  app/Imports/Purchases/Sheets/BillItemTaxes.php
  app/Imports/Purchases/Sheets/BillItems.php
  app/Imports/Purchases/Sheets/BillTotals.php
  app/Imports/Purchases/Sheets/BillTransactions.php
  app/Imports/Purchases/Sheets/Bills.php
  app/Imports/Sales/Revenues.php
  app/Imports/Sales/Sheets/InvoiceHistories.php
  app/Imports/Sales/Sheets/InvoiceItemTaxes.php
  app/Imports/Sales/Sheets/InvoiceItems.php
  app/Imports/Sales/Sheets/InvoiceTransactions.php
  app/Imports/Sales/Sheets/Invoices.php
  app/Models/Common/Item.php
  app/Models/Purchase/Bill.php
  app/Models/Purchase/BillItem.php
  app/Models/Purchase/BillItemTax.php
  app/Traits/Import.php
  public/files/import/bills.xlsx
  public/files/import/customers.xlsx
  public/files/import/items.xlsx
  public/files/import/payments.xlsx
  public/files/import/revenues.xlsx
  public/files/import/transactions.xlsx
Labels: Enhancement

#1150 Forgotten tab title added
  resources/views/auth/forgot/create.blade.php
  resources/views/auth/reset/create.blade.php
Labels: Code Style, Enhancement

#1151 Unnecessary js methods deleted
  resources/assets/js/views/auth/forgot.js
  resources/assets/js/views/auth/login.js
Labels: Code Style, Enhancement

#1152 Auth styles updated
  public/css/custom.css
  resources/views/auth/login/create.blade.php
  resources/views/auth/permissions/create.blade.php
  resources/views/auth/permissions/edit.blade.php
  resources/views/auth/permissions/index.blade.php
  resources/views/auth/roles/create.blade.php
  resources/views/auth/roles/edit.blade.php
  resources/views/auth/users/create.blade.php
  resources/views/auth/users/edit.blade.php
Labels: Code Style, Enhancement

#1153 Portal extra invoice status deleted
  app/Http/Controllers/Portal/Dashboard.php
  app/Http/Controllers/Portal/Invoices.php
Labels: Bug, Code Style, Enhancement

#1154 User landing page
  app/Http/Controllers/Auth/Login.php
  app/Http/Controllers/Auth/Users.php
  app/Http/Controllers/Common/Companies.php
  app/Http/Controllers/Common/Dashboards.php
  app/Http/Middleware/RedirectIfAuthenticated.php
  app/Listeners/Menu/AddAdminItems.php
  app/Models/Auth/User.php
  database/migrations/2020_01_08_000000_core_v200.php
  resources/lang/en-GB/auth.php
  resources/views/auth/users/create.blade.php
  resources/views/auth/users/edit.blade.php
  resources/views/common/dashboards/show.blade.php
  resources/views/errors/403.blade.php
  resources/views/errors/404.blade.php
  resources/views/errors/500.blade.php
  resources/views/partials/admin/menu.blade.php
Labels: Enhancement

#1155 Banking extra elements deleted
  resources/views/auth/permissions/index.blade.php
  resources/views/auth/roles/index.blade.php
  resources/views/auth/users/index.blade.php
  resources/views/banking/accounts/index.blade.php
  resources/views/banking/transactions/index.blade.php
  resources/views/banking/transfers/index.blade.php
Labels: Code Style, Enhancement

#1157 General classes updated for blades
  resources/views/auth/permissions/index.blade.php
  resources/views/auth/roles/index.blade.php
  resources/views/auth/users/index.blade.php
  resources/views/banking/reconciliations/create.blade.php
  resources/views/banking/reconciliations/index.blade.php
  resources/views/banking/transactions/index.blade.php
  resources/views/banking/transfers/index.blade.php
  resources/views/common/companies/create.blade.php
  resources/views/common/companies/edit.blade.php
  resources/views/common/companies/index.blade.php
  resources/views/common/dashboards/index.blade.php
  resources/views/common/dashboards/show.blade.php
  resources/views/common/import/create.blade.php
  resources/views/common/items/index.blade.php
  resources/views/common/reports/index.blade.php
  resources/views/install/updates/edit.blade.php
  resources/views/install/updates/index.blade.php
  resources/views/modals/settings/invoice_template.blade.php
  resources/views/modules/home/index.blade.php
  resources/views/modules/item/documentation.blade.php
  resources/views/modules/item/pre_sale.blade.php
  resources/views/modules/item/show.blade.php
  resources/views/modules/my/index.blade.php
  resources/views/modules/tiles/index.blade.php
  resources/views/partials/admin/menu.blade.php
Labels: Bug, Code Style, Enhancement

#1163 Unnecessary variables deleted in portal invoice
  app/Http/Controllers/Portal/Invoices.php
Labels: Code Style, Enhancement

#1164 Forgotten use deleted
  app/Http/Controllers/Portal/Invoices.php
Labels: Enhancement

#1165 Description added for invoice and bill
  resources/views/portal/invoices/show.blade.php
  resources/views/portal/invoices/signed.blade.php
  resources/views/purchases/bills/print.blade.php
  resources/views/purchases/bills/show.blade.php
  resources/views/sales/invoices/print_classic.blade.php
  resources/views/sales/invoices/print_default.blade.php
  resources/views/sales/invoices/print_modern.blade.php
  resources/views/sales/invoices/show.blade.php
Labels: Code Style, Enhancement

#1166 Vendor bills table column display updated
  resources/views/purchases/vendors/show.blade.php
Labels: Enhancement

#1167 Modules styles updated
  public/css/akaunting-color.css
  resources/lang/en-GB/modules.php
  resources/lang/en-GB/pagination.php
  resources/views/modules/api_key/create.blade.php
  resources/views/modules/home/index.blade.php
  resources/views/modules/item/documentation.blade.php
  resources/views/modules/item/show.blade.php
  resources/views/modules/my/index.blade.php
  resources/views/modules/tiles/index.blade.php
Labels: Code Style, Enhancement, Language Change

#1158 Sample data seeder
  app/Console/Commands/SampleData.php
  database/seeds/SampleData.php
Labels: Feature

#1168 Anchor color updated
  public/css/custom.css
  resources/views/auth/permissions/index.blade.php
  resources/views/auth/roles/index.blade.php
  resources/views/auth/users/index.blade.php
  resources/views/banking/accounts/index.blade.php
  resources/views/banking/reconciliations/index.blade.php
  resources/views/banking/transactions/index.blade.php
  resources/views/banking/transfers/index.blade.php
  resources/views/common/companies/index.blade.php
  resources/views/common/dashboards/index.blade.php
  resources/views/common/items/index.blade.php
  resources/views/layouts/auth.blade.php
  resources/views/partials/portal/footer.blade.php
  resources/views/partials/signed/footer.blade.php
  resources/views/portal/invoices/index.blade.php
  resources/views/portal/payments/index.blade.php
  resources/views/purchases/bills/index.blade.php
  resources/views/purchases/payments/index.blade.php
  resources/views/purchases/vendors/index.blade.php
  resources/views/sales/customers/index.blade.php
  resources/views/sales/invoices/index.blade.php
  resources/views/sales/revenues/index.blade.php
  resources/views/settings/categories/index.blade.php
  resources/views/settings/currencies/index.blade.php
  resources/views/settings/taxes/index.blade.php
  resources/views/wizard/currencies/index.blade.php
  resources/views/wizard/taxes/index.blade.php
Labels: Code Style, Enhancement

#1169 Language anchor updated
  resources/lang/en-GB/general.php
Labels: Enhancement, Language Change

#1171 Resposive headers, anchor styles updated
  resources/views/common/reports/index.blade.php
  resources/views/partials/admin/empty_page.blade.php
  resources/views/partials/admin/footer.blade.php
  resources/views/partials/admin/pagination.blade.php
  resources/views/partials/modules/bar.blade.php
  resources/views/portal/invoices/signed.blade.php
Labels: Code Style, Enhancement

#1172 Print template styles updated
  public/css/print.css
  resources/views/sales/invoices/print_classic.blade.php
  resources/views/sales/invoices/print_default.blade.php
  resources/views/sales/invoices/print_modern.blade.php
Labels: Bug, Code Style, Enhancement

#1174 Histories and transaction alignment updated
  resources/views/purchases/bills/show.blade.php
  resources/views/sales/invoices/show.blade.php
Labels: Bug, Enhancement

#1175 Sales and purchases styles updated
  resources/views/purchases/bills/show.blade.php
  resources/views/purchases/payments/edit.blade.php
  resources/views/sales/invoices/show.blade.php
  resources/views/sales/revenues/edit.blade.php
Labels: Code Style, Enhancement

#1176 Invoice and bill notes updated
  public/css/akaunting-color.css
  resources/views/purchases/bills/show.blade.php
  resources/views/sales/invoices/show.blade.php
Labels: Code Style, Enhancement

#1177 Index column alignment updated
  resources/views/purchases/bills/index.blade.php
  resources/views/sales/invoices/index.blade.php
  resources/views/sales/revenues/index.blade.php
Labels: Code Style, Enhancement

#1178 Forgotten code line spaces
  resources/views/partials/admin/head.blade.php
  resources/views/partials/admin/header.blade.php
  resources/views/partials/modules/reviews.blade.php
Labels: Code Style, Enhancement

#1180 Portal dashboard updated to traits
  app/Http/Controllers/Portal/Dashboard.php
Labels: Code Style, Enhancement

#1181 Portal invoice payment method alignment updated
  resources/views/portal/invoices/show.blade.php
Labels: Code Style, Enhancement

#1183 Print template value alignment updated
  public/css/print.css
  resources/views/sales/invoices/print_classic.blade.php
  resources/views/sales/invoices/print_default.blade.php
  resources/views/sales/invoices/print_modern.blade.php
Labels: Code Style, Enhancement

#1184 Long description updated
  resources/views/purchases/bills/show.blade.php
  resources/views/sales/invoices/show.blade.php
Labels: Code Style, Enhancement

#1185 Print value font weights updated
  public/css/print.css
  resources/views/sales/invoices/print_classic.blade.php
  resources/views/sales/invoices/print_default.blade.php
Labels: Code Style, Enhancement

#1186 Item aligment updated for all shows
  public/css/custom.css
  resources/views/portal/invoices/show.blade.php
  resources/views/portal/invoices/signed.blade.php
  resources/views/purchases/bills/show.blade.php
  resources/views/sales/invoices/show.blade.php
Labels: Code Style, Enhancement

#1187 Bill print updated
  resources/views/purchases/bills/print.blade.php
  resources/views/sales/invoices/print_default.blade.php
Labels: Code Style, Enhancement

#1188 New page alignment updated
  resources/views/sales/invoices/print_classic.blade.php
  resources/views/sales/invoices/print_default.blade.php
  resources/views/sales/invoices/print_modern.blade.php
Labels: Enhancement

#1189 Note style updated in signed
  resources/views/portal/invoices/signed.blade.php
Labels: Enhancement

#1190 Refactored report listener
  app/Abstracts/Listeners/Report.php
  app/Abstracts/Report.php
  app/Events/Common/ReportRowsShowing.php
  app/Listeners/Common/AddAccountsToReports.php
  app/Listeners/Common/AddCustomersToReports.php
  app/Listeners/Common/AddExpenseCategoriesToReports.php
  app/Listeners/Common/AddIncomeCategoriesToReports.php
  app/Listeners/Common/AddIncomeExpenseCategoriesToReports.php
  app/Listeners/Common/AddRowsToTaxReport.php
  app/Listeners/Common/AddVendorsToReports.php
  app/Listeners/Update/V20/Version200.php
  app/Models/Sale/InvoiceItem.php
  app/Providers/Event.php
  app/Reports/ExpenseSummary.php
  app/Reports/IncomeExpenseSummary.php
  app/Reports/IncomeSummary.php
  app/Reports/ProfitLoss.php
  app/Reports/TaxSummary.php
  app/Traits/DateTime.php
  app/Utilities/Recurring.php
  database/seeds/Reports.php
  resources/lang/en-GB/demo.php
  resources/views/common/items/edit.blade.php
  resources/views/common/reports/edit.blade.php
  resources/views/common/reports/index.blade.php
  resources/views/partials/reports/print.blade.php
  resources/views/partials/reports/table.blade.php
  resources/views/partials/reports/table/footer.blade.php
  resources/views/partials/reports/table/rows.blade.php
  resources/views/reports/profit_loss/table/footer.blade.php
  resources/views/reports/tax_summary/table/footer.blade.php
Labels: Enhancement

#1191 Styles updated for vue installation
  resources/assets/js/views/install/Database.vue
  resources/assets/js/views/install/Settings.vue
Labels: Enhancement

#1192 Dynamic report row
  app/Abstracts/Report.php
  resources/views/partials/reports/table/rows.blade.php
Labels: Code Style, Enhancement

#1194 Payment modals updated
  public/css/custom.css
  resources/assets/js/views/purchases/bills.js
  resources/assets/js/views/sales/invoices.js
  resources/views/purchases/bills/show.blade.php
  resources/views/sales/invoices/show.blade.php
Labels: Code Style, Enhancement

#1197 Date picker selected day style updated
  public/css/akaunting-color.css
Labels: Enhancement

#1198 Invoice and bill tax alignment
  public/css/element.css
  resources/views/purchases/bills/create.blade.php
  resources/views/purchases/bills/edit.blade.php
  resources/views/purchases/bills/item.blade.php
  resources/views/sales/invoices/create.blade.php
  resources/views/sales/invoices/edit.blade.php
  resources/views/sales/invoices/item.blade.php
Labels: Code Style, Enhancement

#1199 Forgotten spaces and classes for js files
  resources/assets/js/components/forms/AkauntingTextGroup.vue
  resources/assets/js/views/sales/revenues.js
  resources/assets/js/views/settings/modules.js
Labels: Code Style, Enhancement

#1200 Error color updated
  public/css/akaunting-color.css
Labels: Code Style

#1201 Unnecessary usage for providers
  app/Providers/Auth.php
  app/Providers/Broadcast.php
Labels: Enhancement

#1202 Customer modal icons updated
  resources/views/modals/customers/create.blade.php
Labels: Enhancement

#1203 Text group full disabled updated
  public/css/akaunting-color.css
Labels: Enhancement

#1204 Disable input style updated
  public/css/akaunting-color.css
Labels: Enhancement

#1206 Email template body updated
  resources/lang/en-GB/email_templates.php
Labels: Enhancement
