Repository akaunting/akaunting, pull requests merged in 2020-05, with the labels that each got.

#1433 Added tenantable attribute to models
  app/Abstracts/Model.php
  app/Models/Auth/Permission.php
  app/Models/Auth/Role.php
  app/Models/Auth/User.php
  app/Models/Common/Company.php
  app/Models/Common/Media.php
  app/Models/Setting/Setting.php
  app/Scopes/Company.php
  app/Traits/Tenants.php
Labels: Enhancement

#1434 Updated translations
  resources/lang/ar-SA/bills.php
  resources/lang/ar-SA/bulk_actions.php
  resources/lang/ar-SA/install.php
  resources/lang/ar-SA/invoices.php
  resources/lang/ar-SA/settings.php
  resources/lang/ar-SA/validation.php
  resources/lang/es-ES/bills.php
  resources/lang/es-ES/bulk_actions.php
  resources/lang/es-ES/install.php
  resources/lang/es-ES/invoices.php
  resources/lang/es-ES/messages.php
  resources/lang/es-ES/passwords.php
  resources/lang/es-ES/settings.php
  resources/lang/es-ES/validation.php
  resources/lang/ja-JP/install.php
  resources/lang/lt-LT/auth.php
  resources/lang/lt-LT/bills.php
  resources/lang/lt-LT/bulk_actions.php
  resources/lang/lt-LT/companies.php
  resources/lang/lt-LT/customers.php
  resources/lang/lt-LT/dashboards.php
  resources/lang/lt-LT/demo.php
  resources/lang/lt-LT/email_templates.php
  resources/lang/lt-LT/errors.php
  resources/lang/lt-LT/general.php
  resources/lang/lt-LT/header.php
  resources/lang/lt-LT/install.php
  resources/lang/lt-LT/invoices.php
  resources/lang/lt-LT/items.php
  resources/lang/lt-LT/maintenance.php
  resources/lang/lt-LT/messages.php
  resources/lang/lt-LT/modules.php
  resources/lang/lt-LT/pagination.php
  resources/lang/lt-LT/passwords.php
  resources/lang/lt-LT/reconciliations.php
  resources/lang/lt-LT/reports.php
  resources/lang/lt-LT/settings.php
  resources/lang/lt-LT/taxes.php
  resources/lang/lt-LT/validation.php
  resources/lang/lt-LT/widgets.php
Labels: Enhancement

#1435 Default start/end date of new reconciliation
  app/Http/Controllers/Banking/Reconciliations.php
  resources/views/banking/reconciliations/create.blade.php
Labels: Bug

#1441 Added event to global search
  app/Events/Common/GlobalSearched.php
  app/Http/Controllers/Common/Search.php
Labels: Feature

#1442 items of invoices and bills moved to partials path
  resources/views/partials/documents/item/print.blade.php
  resources/views/partials/documents/item/show.blade.php
  resources/views/purchases/bills/print.blade.php
  resources/views/purchases/bills/show.blade.php
  resources/views/sales/invoices/print_classic.blade.php
  resources/views/sales/invoices/print_default.blade.php
  resources/views/sales/invoices/print_modern.blade.php
  resources/views/sales/invoices/show.blade.php
Labels: Enhancement

#1447 Including tax in profit & loss
  app/Abstracts/Report.php
  app/Reports/ProfitLoss.php
  app/Reports/TaxSummary.php
Labels: Bug
