Repository akaunting/akaunting, pull requests merged in 2020-02, with the labels that each got.

#1211 Text editor paragraph space updated
  public/css/custom.css
Labels: Enhancement

#1207 disabled property added to AkauntingDate.vue
  resources/assets/js/components/AkauntingDate.vue
Labels: Feature

#1209 disabled mode added for multiple select group
  resources/assets/js/components/AkauntingSelect.vue
Labels: Bug

#1212 fix radio group disabled mode
  resources/views/partials/form/radio_group.blade.php
Labels: Bug

#1213 Payment list alignment updated
  resources/views/purchases/payments/index.blade.php
Labels: Enhancement

#1214 Net profit print view updated
  public/css/print.css
  resources/views/reports/profit_loss/content/footer.blade.php
Labels: Enhancement

#1215 Unnecessary menu presenters deleted
  config/menu.php
Labels: Code Style, Enhancement

#1216 Price paid and carousel description style updated
  public/css/element.css
  resources/views/portal/invoices/show.blade.php
  resources/views/sales/invoices/show.blade.php
Labels: Code Style, Enhancement

#1217 Modal forgotten styles and transactions added
  resources/assets/js/components/AkauntingModal.vue
  resources/assets/js/components/AkauntingModalAddNew.vue
  resources/lang/en-GB/general.php
  resources/views/modals/bills/payment.blade.php
  resources/views/modals/categories/create.blade.php
  resources/views/modals/invoices/payment.blade.php
  resources/views/modals/settings/invoice_template.blade.php
  resources/views/modals/taxes/create.blade.php
  resources/views/modals/vendors/create.blade.php
  resources/views/purchases/bills/show.blade.php
  resources/views/sales/invoices/show.blade.php
Labels: Bug, Code Style, Enhancement, Language Change

#1218 Wizard passing extra steps issue updated
  resources/assets/js/views/wizard/company.js
  resources/assets/js/views/wizard/currencies.js
  resources/assets/js/views/wizard/finish.js
  resources/assets/js/views/wizard/taxes.js
  resources/views/wizard/companies/edit.blade.php
  resources/views/wizard/currencies/index.blade.php
  resources/views/wizard/finish/index.blade.php
  resources/views/wizard/taxes/index.blade.php
Labels: Bug, Code Style, Enhancement

#1219 Wrong modal content style updated
  resources/assets/js/components/AkauntingModal.vue
Labels: Enhancement

#1221 add form libraries for dynamic component
  resources/assets/js/mixins/global.js
Labels: Bug

#1222 All button icons removed in modals
  resources/assets/js/components/AkauntingModal.vue
  resources/assets/js/components/AkauntingModalAddNew.vue
  resources/assets/js/views/settings/settings.js
  resources/views/partials/form/save_buttons.blade.php
  resources/views/purchases/bills/show.blade.php
  resources/views/sales/invoices/show.blade.php
  resources/views/settings/invoice/edit.blade.php
Labels: Code Style, Enhancement

#1223 change function name
  resources/views/settings/currencies/create.blade.php
  resources/views/settings/currencies/edit.blade.php
Labels: Bug

#1224 Credit card selectbox style updated
  resources/assets/js/components/CreditCard/CardForm.vue
Labels: Code Style, Enhancement

#1226 Selection reference and alignment updated
  public/css/custom.css
  public/css/element.css
  resources/views/purchases/vendors/show.blade.php
  resources/views/sales/customers/show.blade.php
Labels: Code Style, Enhancement

#1227 Flexible invoice/bill item columns
  public/css/custom.css
  resources/views/modules/item/show.blade.php
  resources/views/purchases/bills/create.blade.php
  resources/views/purchases/bills/edit.blade.php
  resources/views/purchases/bills/item.blade.php
  resources/views/sales/invoices/create.blade.php
  resources/views/sales/invoices/edit.blade.php
  resources/views/sales/invoices/item.blade.php
Labels: Code Style, Enhancement

#1228 fix add dynamic form id
  resources/assets/js/mixins/global.js
Labels: Bug

#1229 Blank pages and show pages updated
  public/img/empty_pages/payments.png
  public/img/empty_pages/revenues.png
  resources/views/purchases/bills/show.blade.php
  resources/views/sales/invoices/show.blade.php
Labels: Code Style, Enhancement

#1232 Overflows and tags updated
  public/css/custom.css
  public/css/element.css
  resources/views/common/dashboards/show.blade.php
  resources/views/partials/admin/menu.blade.php
  resources/views/purchases/bills/create.blade.php
  resources/views/purchases/bills/edit.blade.php
  resources/views/sales/invoices/create.blade.php
  resources/views/sales/invoices/edit.blade.php
Labels: Code Style, Enhancement

#1233 Permissions trait
  app/Listeners/Update/V20/Version200.php
  app/Traits/Permissions.php
  database/seeds/Roles.php
Labels: Feature

#1234 Portal access and report long description updated
  app/Http/Controllers/Portal/Profile.php
  resources/views/common/reports/index.blade.php
  resources/views/partials/portal/navbar.blade.php
  resources/views/portal/profile/edit.blade.php
Labels: Bug, Code Style, Enhancement

#1235 File upload and review updated
  resources/views/partials/media/file.blade.php
  resources/views/partials/media/files.blade.php
  resources/views/portal/payments/show.blade.php
  resources/views/sales/invoices/show.blade.php
Labels: Bug, Code Style, Enhancement

#1236 Bill attachment updated
  resources/views/partials/media/file.blade.php
  resources/views/portal/payments/show.blade.php
  resources/views/purchases/bills/show.blade.php
Labels: Code Style, Enhancement

#1161 Show grand total for bills/invoices
  app/Http/Controllers/Purchases/Bills.php
  app/Http/Controllers/Sales/Invoices.php
  resources/assets/js/views/purchases/bills.js
  resources/assets/js/views/sales/invoices.js
Labels: Enhancement

#1239 Blank pages updated
  public/img/empty_pages/payments.png
  public/img/empty_pages/reconciliations.png
  public/img/empty_pages/taxes.png
  public/img/empty_pages/transfers.png
  resources/lang/en-GB/general.php
  resources/views/banking/reconciliations/index.blade.php
  resources/views/banking/transfers/index.blade.php
  resources/views/settings/taxes/index.blade.php
Labels: Code Style, Enhancement, Language Change

#1241 All list pages updated same height
  public/css/custom.css
  resources/views/banking/transactions/index.blade.php
  resources/views/portal/invoices/index.blade.php
  resources/views/portal/payments/index.blade.php
  resources/views/purchases/bills/show.blade.php
  resources/views/purchases/vendors/show.blade.php
  resources/views/sales/customers/show.blade.php
  resources/views/sales/invoices/show.blade.php
  resources/views/widgets/account_balance.blade.php
  resources/views/widgets/latest_expenses.blade.php
  resources/views/widgets/latest_income.blade.php
Labels: Code Style, Enhancement

#1242 Logos are updated from png to svg
  public/img/akaunting-logo-green.png
  public/img/akaunting-logo-green.svg
  public/img/akaunting-logo-white.png
  public/img/akaunting-logo-white.svg
  resources/views/common/items/index.blade.php
  resources/views/layouts/auth.blade.php
  resources/views/layouts/install.blade.php
  resources/views/partials/admin/menu.blade.php
  resources/views/partials/portal/menu.blade.php
Labels: Enhancement

#1243 Overflow rotation updated in items
  public/css/custom.css
  resources/views/purchases/bills/create.blade.php
  resources/views/purchases/bills/edit.blade.php
  resources/views/purchases/bills/show.blade.php
  resources/views/sales/invoices/create.blade.php
  resources/views/sales/invoices/edit.blade.php
  resources/views/sales/invoices/show.blade.php
Labels: Code Style, Enhancement

#1244 Invoice/bill status reflected
  public/css/element.css
  resources/assets/js/views/purchases/payments.js
  resources/assets/js/views/sales/revenues.js
  resources/views/purchases/payments/index.blade.php
  resources/views/sales/revenues/index.blade.php
Labels: Code Style, Enhancement

#1245 Wrong status updated
  resources/views/purchases/payments/index.blade.php
  resources/views/sales/revenues/index.blade.php
Labels: Bug

#1246 Unnecessary classes deleted and styles updated
  public/css/akaunting-color.css
  public/css/custom.css
  resources/views/auth/login/create.blade.php
  resources/views/common/dashboards/show.blade.php
  resources/views/modules/item/documentation.blade.php
  resources/views/portal/payments/show.blade.php
  resources/views/purchases/bills/create.blade.php
  resources/views/purchases/bills/edit.blade.php
  resources/views/purchases/bills/item.blade.php
  resources/views/purchases/bills/show.blade.php
  resources/views/purchases/payments/index.blade.php
  resources/views/sales/invoices/create.blade.php
  resources/views/sales/invoices/edit.blade.php
  resources/views/sales/invoices/item.blade.php
  resources/views/sales/invoices/show.blade.php
  resources/views/sales/revenues/index.blade.php
Labels: Code Style, Enhancement

#1247 Custom toggle and tag style updated
  public/css/custom.css
  public/css/element.css
Labels: Code Style, Enhancement

#1248 Compatibility deleted in core
  resources/views/modules/item/pre_sale.blade.php
  resources/views/modules/item/show.blade.php
Labels: Code Style, Enhancement

#1249 Action button alignment updated
  public/css/custom.css
  resources/views/purchases/bills/create.blade.php
  resources/views/purchases/bills/edit.blade.php
  resources/views/purchases/bills/item.blade.php
  resources/views/sales/invoices/create.blade.php
  resources/views/sales/invoices/edit.blade.php
  resources/views/sales/invoices/item.blade.php
Labels: Code Style, Enhancement

#1250 Invoice/bill attachment style updated
  resources/views/partials/media/file.blade.php
  resources/views/portal/payments/show.blade.php
  resources/views/purchases/bills/show.blade.php
  resources/views/sales/invoices/show.blade.php
Labels: Code Style, Enhancement

#1251 Passport reset response updated
  app/Http/Controllers/Auth/Forgot.php
  resources/views/auth/forgot/create.blade.php
Labels: Bug, Code Style, Enhancement

#1254 Pagination responsive updated
  public/css/akaunting-color.css
  public/css/custom.css
  resources/views/partials/admin/menu.blade.php
  resources/views/partials/admin/pagination.blade.php
  resources/views/partials/portal/menu.blade.php
Labels: Code Style, Enhancement

#1256 Footer and header responsive update
  public/css/custom.css
  public/css/element.css
  resources/views/partials/admin/header.blade.php
  resources/views/settings/company/edit.blade.php
  resources/views/settings/modules/edit.blade.php
Labels: Code Style, Enhancement

#1259 Save buttons responsive updated
  public/css/custom.css
  resources/views/auth/permissions/create.blade.php
  resources/views/auth/permissions/edit.blade.php
  resources/views/auth/roles/create.blade.php
  resources/views/auth/roles/edit.blade.php
  resources/views/auth/users/create.blade.php
  resources/views/auth/users/edit.blade.php
  resources/views/banking/accounts/create.blade.php
  resources/views/banking/accounts/edit.blade.php
  resources/views/banking/transfers/create.blade.php
  resources/views/banking/transfers/edit.blade.php
  resources/views/common/companies/create.blade.php
  resources/views/common/companies/edit.blade.php
  resources/views/common/dashboards/create.blade.php
  resources/views/common/dashboards/edit.blade.php
  resources/views/common/import/create.blade.php
  resources/views/common/items/create.blade.php
  resources/views/common/items/edit.blade.php
  resources/views/common/reports/create.blade.php
  resources/views/common/reports/edit.blade.php
  resources/views/layouts/auth.blade.php
  resources/views/portal/profile/edit.blade.php
  resources/views/purchases/bills/create.blade.php
  resources/views/purchases/bills/edit.blade.php
  resources/views/purchases/payments/create.blade.php
  resources/views/purchases/payments/edit.blade.php
  resources/views/purchases/vendors/create.blade.php
  resources/views/purchases/vendors/edit.blade.php
  resources/views/sales/customers/create.blade.php
  resources/views/sales/customers/edit.blade.php
  resources/views/sales/invoices/create.blade.php
  resources/views/sales/invoices/edit.blade.php
  resources/views/sales/revenues/create.blade.php
  resources/views/sales/revenues/edit.blade.php
  resources/views/settings/categories/create.blade.php
  resources/views/settings/categories/edit.blade.php
  resources/views/settings/company/edit.blade.php
  resources/views/settings/currencies/create.blade.php
  resources/views/settings/currencies/edit.blade.php
  resources/views/settings/default/edit.blade.php
  resources/views/settings/email/edit.blade.php
  resources/views/settings/invoice/edit.blade.php
  resources/views/settings/localisation/edit.blade.php
  resources/views/settings/modules/edit.blade.php
  resources/views/settings/schedule/edit.blade.php
  resources/views/settings/taxes/create.blade.php
  resources/views/settings/taxes/edit.blade.php
Labels: Code Style, Enhancement

#1260 Discount style updated
  resources/views/purchases/bills/create.blade.php
  resources/views/purchases/bills/edit.blade.php
  resources/views/sales/invoices/create.blade.php
  resources/views/sales/invoices/edit.blade.php
Labels: Code Style, Enhancement

#1261 Pwa updated
  manifest.json
  public/img/icons/akaunting-120x120.png
  public/img/icons/akaunting-128x128.png
  public/img/icons/akaunting-144x144.png
  public/img/icons/akaunting-152x152.png
  public/img/icons/akaunting-180x180.png
  public/img/icons/akaunting-192x192.png
  public/img/icons/akaunting-384x384.png
  public/img/icons/akaunting-512x512.png
  public/img/icons/akaunting-640x1136.png
  public/img/icons/akaunting-72x72.png
  public/img/icons/akaunting-96x96.png
  public/img/icons/splash-1242x2208.png
  public/img/icons/splash-1242x2688.png
  public/img/icons/splash-1536x2048.png
  public/img/icons/splash-1668x2224.png
  public/img/icons/splash-1668x2388.png
  public/img/icons/splash-2048x2732.png
  public/img/icons/splash-640x1136.png
  public/img/icons/splash-750x1334.png
  public/img/icons/splash-828x1792.png
  resources/views/partials/pwa/pwa.blade.php
  serviceworker.js
Labels: Code Style, Enhancement

#1262 Left menu stabilize updated
  public/css/custom.css
  resources/views/layouts/admin.blade.php
  resources/views/layouts/error.blade.php
  resources/views/layouts/modules.blade.php
  resources/views/layouts/portal.blade.php
Labels: Code Style, Enhancement

#1264 Malay language
  config/language.php
  resources/lang/ms-MY/accounts.php
  resources/lang/ms-MY/auth.php
  resources/lang/ms-MY/bills.php
  resources/lang/ms-MY/bulk_actions.php
  resources/lang/ms-MY/companies.php
  resources/lang/ms-MY/currencies.php
  resources/lang/ms-MY/customers.php
  resources/lang/ms-MY/dashboards.php
  resources/lang/ms-MY/demo.php
  resources/lang/ms-MY/email_templates.php
  resources/lang/ms-MY/errors.php
  resources/lang/ms-MY/footer.php
  resources/lang/ms-MY/general.php
  resources/lang/ms-MY/header.php
  resources/lang/ms-MY/import.php
  resources/lang/ms-MY/install.php
  resources/lang/ms-MY/invoices.php
  resources/lang/ms-MY/items.php
  resources/lang/ms-MY/maintenance.php
  resources/lang/ms-MY/messages.php
  resources/lang/ms-MY/modules.php
  resources/lang/ms-MY/notifications.php
  resources/lang/ms-MY/pagination.php
  resources/lang/ms-MY/passwords.php
  resources/lang/ms-MY/reconciliations.php
  resources/lang/ms-MY/recurring.php
  resources/lang/ms-MY/reports.php
  resources/lang/ms-MY/settings.php
  resources/lang/ms-MY/taxes.php
  resources/lang/ms-MY/transfers.php
  resources/lang/ms-MY/updates.php
  resources/lang/ms-MY/validation.php
  resources/lang/ms-MY/widgets.php
Labels: Feature

#1274 Added update::all command
  app/Console/Commands/BillReminder.php
  app/Console/Commands/FinishUpdate.php
  app/Console/Commands/InvoiceReminder.php
  app/Console/Commands/RecurringCheck.php
  app/Console/Commands/SampleData.php
  app/Console/Commands/Update.php
  app/Console/Commands/UpdateAll.php
  app/Console/Commands/UserSeed.php
  app/Utilities/Updater.php
  app/Utilities/Versions.php
Labels: Feature

#1275 Forgotten search string
  resources/assets/js/views/banking/transactions.js
  resources/views/banking/transactions/index.blade.php
Labels: Code Style, Enhancement

#1277 Fixed exports
  app/Exports/Banking/Transactions.php
  app/Exports/Purchases/Sheets/BillHistories.php
  app/Exports/Purchases/Sheets/BillItemTaxes.php
  app/Exports/Purchases/Sheets/BillItems.php
  app/Exports/Purchases/Sheets/BillTotals.php
  app/Exports/Purchases/Sheets/BillTransactions.php
  app/Exports/Sales/Sheets/InvoiceHistories.php
  app/Exports/Sales/Sheets/InvoiceItemTaxes.php
  app/Exports/Sales/Sheets/InvoiceItems.php
  app/Exports/Sales/Sheets/InvoiceTotals.php
  app/Exports/Sales/Sheets/InvoiceTransactions.php
Labels: Bug

#1281 Fixed update routes
  app/Http/Controllers/Install/Updates.php
  resources/views/install/updates/index.blade.php
  routes/admin.php
Labels: Bug

#1286 Action button alignment updated
  public/css/custom.css
  resources/views/purchases/bills/create.blade.php
  resources/views/purchases/bills/edit.blade.php
  resources/views/purchases/bills/item.blade.php
  resources/views/sales/invoices/create.blade.php
  resources/views/sales/invoices/edit.blade.php
  resources/views/sales/invoices/item.blade.php
Labels: Code Style, Enhancement

#1287 Import rules not applicable in map
  app/Abstracts/Import.php
  app/Imports/Purchases/Sheets/BillHistories.php
  app/Imports/Purchases/Sheets/BillItemTaxes.php
  app/Imports/Purchases/Sheets/BillItems.php
  app/Imports/Purchases/Sheets/BillTotals.php
  app/Imports/Purchases/Sheets/BillTransactions.php
  app/Imports/Purchases/Sheets/Bills.php
  app/Imports/Sales/Sheets/InvoiceHistories.php
  app/Imports/Sales/Sheets/InvoiceItemTaxes.php
  app/Imports/Sales/Sheets/InvoiceItems.php
  app/Imports/Sales/Sheets/InvoiceTotals.php
  app/Imports/Sales/Sheets/InvoiceTransactions.php
  app/Imports/Sales/Sheets/Invoices.php
Labels: Bug

#1289 Styling updated and unnecessary classes deleted
  public/css/custom.css
  public/css/print.css
  resources/views/partials/admin/empty_page.blade.php
Labels: Code Style, Enhancement

#1290 User logo format updated
  public/img/user.png
  public/img/user.svg
  resources/views/partials/admin/navbar.blade.php
  resources/views/partials/portal/navbar.blade.php
Labels: Code Style, Enhancement

#1294 Fatal error if no reviews available
  resources/views/partials/modules/reviews.blade.php
Labels: Bug

#1292 Get invoice items from request
  resources/views/sales/invoices/create.blade.php
Labels: Enhancement

#1301 Items updated to flexible structure
  public/css/custom.css
  resources/views/purchases/bills/create.blade.php
  resources/views/purchases/bills/edit.blade.php
  resources/views/purchases/bills/item.blade.php
  resources/views/sales/invoices/create.blade.php
  resources/views/sales/invoices/edit.blade.php
  resources/views/sales/invoices/item.blade.php
Labels: Code Style, Enhancement

#1302 Fix money group disabled attribute
  resources/assets/js/components/AkauntingMoney.vue
  resources/views/partials/form/money_group.blade.php
Labels: Bug

#1305 Fixed special chars in notifications
  app/Abstracts/Notification.php
  config/setting.php
Labels: Bug

#1306 Added language selection in company
  app/Jobs/Common/CreateCompany.php
  app/Jobs/Common/UpdateCompany.php
  resources/views/common/companies/create.blade.php
  resources/views/common/companies/edit.blade.php
Labels: Feature

#1307 Fix disabled attributes for money group
  .env.example
  resources/assets/js/components/AkauntingMoney.vue
  resources/views/banking/reconciliations/create.blade.php
  resources/views/banking/reconciliations/edit.blade.php
  resources/views/purchases/bills/create.blade.php
  resources/views/purchases/bills/edit.blade.php
  resources/views/sales/invoices/create.blade.php
  resources/views/sales/invoices/edit.blade.php
Labels: Feature

#1311 Not validating import file extension
  app/Http/Requests/Common/Import.php
  app/Providers/Validation.php
  resources/lang/en-GB/validation.php
Labels: Bug, Language Change

#1312 Not able to upload files
  resources/assets/js/plugins/form.js
Labels: Bug

#1313 Fix multi select group value
  resources/views/partials/form/multi_select_add_new_group.blade.php
  resources/views/partials/form/multi_select_group.blade.php
Labels: Bug
