Repository akaunting/akaunting, pull requests merged in 2020-03, with the labels that each got.

#1321 Lazy collections for exports
  app/Exports/Banking/Transactions.php
  app/Exports/Common/Items.php
  app/Exports/Purchases/Payments.php
  app/Exports/Purchases/Sheets/BillHistories.php
  app/Exports/Purchases/Sheets/BillItemTaxes.php
  app/Exports/Purchases/Sheets/BillItems.php
  app/Exports/Purchases/Sheets/BillTotals.php
  app/Exports/Purchases/Sheets/BillTransactions.php
  app/Exports/Purchases/Sheets/Bills.php
  app/Exports/Purchases/Vendors.php
  app/Exports/Sales/Customers.php
  app/Exports/Sales/Revenues.php
  app/Exports/Sales/Sheets/InvoiceHistories.php
  app/Exports/Sales/Sheets/InvoiceItemTaxes.php
  app/Exports/Sales/Sheets/InvoiceItems.php
  app/Exports/Sales/Sheets/InvoiceTotals.php
  app/Exports/Sales/Sheets/InvoiceTransactions.php
  app/Exports/Sales/Sheets/Invoices.php
Labels: Feature

#1322 Forgotten styles updated
  public/css/akaunting-color.css
  public/css/custom.css
  resources/views/auth/permissions/index.blade.php
  resources/views/common/dashboards/show.blade.php
  resources/views/modules/api_key/create.blade.php
  resources/views/purchases/bills/create.blade.php
  resources/views/purchases/bills/edit.blade.php
  resources/views/purchases/bills/item.blade.php
  resources/views/sales/invoices/create.blade.php
  resources/views/sales/invoices/edit.blade.php
  resources/views/sales/invoices/item.blade.php
Labels: Code Style, Enhancement

#1324 Left menu pinned updated
  resources/views/layouts/admin.blade.php
  resources/views/layouts/error.blade.php
  resources/views/layouts/modules.blade.php
  resources/views/layouts/portal.blade.php
  resources/views/partials/admin/scripts.blade.php
  resources/views/partials/portal/scripts.blade.php
Labels: Bug, Code Style, Enhancement

#1325 Attchment updated
  resources/views/purchases/payments/edit.blade.php
  resources/views/sales/revenues/edit.blade.php
Labels: Bug

#1329 Auto-generate bill number
  app/Http/Controllers/Purchases/Bills.php
  app/Listeners/Purchase/IncreaseNextBillNumber.php
  app/Models/Purchase/Bill.php
  app/Providers/Event.php
  app/Traits/Purchases.php
  resources/views/purchases/bills/create.blade.php
Labels: Feature

#1332 Selectbox add new new style
  resources/assets/js/components/AkauntingSelect.vue
  resources/views/partials/form/multi_select_add_new_group.blade.php
  resources/views/partials/form/select_add_new_group.blade.php
  resources/views/partials/form/select_group_add_new_group.blade.php
Labels: Enhancement

#1333 Updated translations
  resources/lang/ar-SA/auth.php
  resources/lang/ar-SA/bills.php
  resources/lang/ar-SA/bulk_actions.php
  resources/lang/ar-SA/currencies.php
  resources/lang/ar-SA/customers.php
  resources/lang/ar-SA/dashboards.php
  resources/lang/ar-SA/demo.php
  resources/lang/ar-SA/email_templates.php
  resources/lang/ar-SA/general.php
  resources/lang/ar-SA/header.php
  resources/lang/ar-SA/invoices.php
  resources/lang/ar-SA/maintenance.php
  resources/lang/ar-SA/messages.php
  resources/lang/ar-SA/modules.php
  resources/lang/ar-SA/reconciliations.php
  resources/lang/ar-SA/settings.php
  resources/lang/ar-SA/validation.php
  resources/lang/ar-SA/widgets.php
  resources/lang/hi-IN/auth.php
  resources/lang/hi-IN/bills.php
  resources/lang/hi-IN/bulk_actions.php
  resources/lang/hi-IN/companies.php
  resources/lang/hi-IN/customers.php
  resources/lang/hi-IN/dashboards.php
  resources/lang/hi-IN/demo.php
  resources/lang/hi-IN/errors.php
  resources/lang/hi-IN/general.php
  resources/lang/hi-IN/invoices.php
  resources/lang/hi-IN/maintenance.php
  resources/lang/hi-IN/messages.php
  resources/lang/hi-IN/modules.php
  resources/lang/hi-IN/pagination.php
  resources/lang/hi-IN/reports.php
  resources/lang/hi-IN/settings.php
  resources/lang/hi-IN/widgets.php
  resources/lang/nb-NO/auth.php
  resources/lang/nb-NO/bills.php
  resources/lang/nb-NO/bulk_actions.php
  resources/lang/nb-NO/companies.php
  resources/lang/nb-NO/customers.php
  resources/lang/nb-NO/dashboards.php
  resources/lang/nb-NO/demo.php
  resources/lang/nb-NO/email_templates.php
  resources/lang/nb-NO/errors.php
  resources/lang/nb-NO/general.php
  resources/lang/nb-NO/header.php
  resources/lang/nb-NO/invoices.php
  resources/lang/nb-NO/items.php
  resources/lang/nb-NO/maintenance.php
  resources/lang/nb-NO/messages.php
  resources/lang/nb-NO/modules.php
  resources/lang/nb-NO/pagination.php
  resources/lang/nb-NO/reconciliations.php
  resources/lang/nb-NO/reports.php
  resources/lang/nb-NO/settings.php
  resources/lang/nb-NO/taxes.php
  resources/lang/nb-NO/validation.php
  resources/lang/nb-NO/widgets.php
  resources/lang/tr-TR/email_templates.php
Labels: Enhancement

#1335 Fix typo in function name
  app/Http/Controllers/Banking/Reconciliations.php
  app/Models/Banking/Account.php
  app/Models/Setting/Category.php
  app/Widgets/IncomeByCategory.php
Labels: Enhancement

#1337 Reports data alignment updated
  app/Abstracts/Report.php
  public/css/akaunting-color.css
  public/css/custom.css
  public/css/print.css
  resources/views/partials/reports/table/footer.blade.php
  resources/views/partials/reports/table/header.blade.php
  resources/views/partials/reports/table/rows.blade.php
  resources/views/reports/profit_loss/content/footer.blade.php
  resources/views/reports/profit_loss/content/header.blade.php
  resources/views/reports/profit_loss/table/footer.blade.php
Labels: Code Style, Enhancement

#1338 Fixed currency conversion
  app/Abstracts/DocumentModel.php
  app/Http/Controllers/Portal/Invoices.php
  app/Http/Controllers/Purchases/Bills.php
  app/Http/Controllers/Sales/Invoices.php
  app/Jobs/Banking/CreateDocumentTransaction.php
  app/Jobs/Banking/CreateTransfer.php
  app/Jobs/Banking/UpdateTransfer.php
  app/Models/Banking/Transaction.php
  app/Traits/Currencies.php
  composer.json
Labels: Bug

#1339 Forgotten classes in reports
  resources/views/partials/reports/table/footer.blade.php
  resources/views/partials/reports/table/header.blade.php
  resources/views/partials/reports/table/rows.blade.php
  resources/views/reports/profit_loss/content/footer.blade.php
  resources/views/reports/profit_loss/content/header.blade.php
  resources/views/reports/profit_loss/table/footer.blade.php
Labels: Code Style, Enhancement

#1350 Not able to see changelog
  app/Utilities/Versions.php
  composer.json
Labels: Bug

#1351 Invoice template styles updated
  public/css/print.css
  resources/views/sales/invoices/print_default.blade.php
  resources/views/sales/invoices/print_modern.blade.php
Labels: Code Style, Enhancement

#1352 Prevent change/delete for reconciled records
  app/Jobs/Banking/DeleteTransaction.php
  app/Jobs/Banking/UpdateTransaction.php
  app/Jobs/Purchase/DeleteBill.php
  app/Jobs/Sale/DeleteInvoice.php
  app/Models/Banking/Transaction.php
  resources/lang/en-GB/messages.php
Labels: Enhancement

#1355 Left menu updated
  resources/views/partials/admin/menu.blade.php
  resources/views/partials/admin/scripts.blade.php
  resources/views/partials/portal/menu.blade.php
  resources/views/partials/portal/scripts.blade.php
Labels: Code Style, Enhancement

#1356 Laravel 7
  .env.example
  .env.testing
  .htaccess
  app/Console/Stubs/Modules/routes/admin.stub
  app/Console/Stubs/Modules/routes/portal.stub
  app/Exceptions/Handler.php
  app/Utilities/Overrider.php
  composer.json
  config/app.php
  config/auth.php
  config/cache.php
  config/cors.php
  config/database.php
  config/filesystems.php
  config/logging.php
  config/mail.php
  config/queue.php
  config/session.php
  database/seeds/SampleData.php
  index.php
  overrides/Illuminate/Translation/MessageSelector.php
  phpunit.xml
  resources/lang/en-GB/passwords.php
  routes/admin.php
  routes/api.php
  routes/channels.php
  routes/common.php
  routes/console.php
  routes/guest.php
  routes/install.php
  routes/portal.php
  routes/signed.php
  routes/wizard.php
  tests/CreatesApplication.php
  tests/TestCase.php
  tests/Unit/ExampleTest.php
Labels: Enhancement, Language Change

#1357 Mark bill as paid
  app/Http/Controllers/Purchases/Bills.php
  resources/lang/en-GB/bills.php
  resources/views/purchases/bills/show.blade.php
  routes/admin.php
Labels: Feature, Language Change

#1377 Bengali language
  config/language.php
  resources/lang/bn-BD/accounts.php
  resources/lang/bn-BD/auth.php
  resources/lang/bn-BD/bills.php
  resources/lang/bn-BD/bulk_actions.php
  resources/lang/bn-BD/companies.php
  resources/lang/bn-BD/currencies.php
  resources/lang/bn-BD/customers.php
  resources/lang/bn-BD/dashboards.php
  resources/lang/bn-BD/demo.php
  resources/lang/bn-BD/email_templates.php
  resources/lang/bn-BD/errors.php
  resources/lang/bn-BD/footer.php
  resources/lang/bn-BD/general.php
  resources/lang/bn-BD/header.php
  resources/lang/bn-BD/import.php
  resources/lang/bn-BD/install.php
  resources/lang/bn-BD/invoices.php
  resources/lang/bn-BD/items.php
  resources/lang/bn-BD/maintenance.php
  resources/lang/bn-BD/messages.php
  resources/lang/bn-BD/modules.php
  resources/lang/bn-BD/notifications.php
  resources/lang/bn-BD/pagination.php
  resources/lang/bn-BD/passwords.php
  resources/lang/bn-BD/reconciliations.php
  resources/lang/bn-BD/recurring.php
  resources/lang/bn-BD/reports.php
  resources/lang/bn-BD/settings.php
  resources/lang/bn-BD/taxes.php
  resources/lang/bn-BD/transfers.php
  resources/lang/bn-BD/updates.php
  resources/lang/bn-BD/validation.php
  resources/lang/bn-BD/widgets.php
Labels: Feature

#1378 Updated translations
  resources/lang/hi-IN/bills.php
  resources/lang/nl-NL/auth.php
  resources/lang/nl-NL/bills.php
  resources/lang/nl-NL/bulk_actions.php
  resources/lang/nl-NL/companies.php
  resources/lang/nl-NL/customers.php
  resources/lang/nl-NL/dashboard.php
  resources/lang/nl-NL/dashboards.php
  resources/lang/nl-NL/demo.php
  resources/lang/nl-NL/email_templates.php
  resources/lang/nl-NL/errors.php
  resources/lang/nl-NL/general.php
  resources/lang/nl-NL/header.php
  resources/lang/nl-NL/invoices.php
  resources/lang/nl-NL/items.php
  resources/lang/nl-NL/maintenance.php
  resources/lang/nl-NL/messages.php
  resources/lang/nl-NL/modules.php
  resources/lang/nl-NL/pagination.php
  resources/lang/nl-NL/passwords.php
  resources/lang/nl-NL/reconciliations.php
  resources/lang/nl-NL/reports.php
  resources/lang/nl-NL/settings.php
  resources/lang/nl-NL/taxes.php
  resources/lang/nl-NL/validation.php
  resources/lang/nl-NL/widgets.php
  resources/lang/pt-BR/bulk_actions.php
  resources/lang/pt-BR/messages.php
  resources/lang/pt-BR/passwords.php
  resources/lang/pt-BR/validation.php
Labels: Enhancement

#1267 multiple prop of AkauntingSelect.vue component should be passed as a …
  resources/views/partials/form/multi_select_add_new_group.blade.php
Labels: Bug

#1380 Added discount location setting
  app/Http/Controllers/Settings/Localisation.php
  app/Models/Purchase/BillItem.php
  app/Models/Sale/InvoiceItem.php
  resources/lang/en-GB/bills.php
  resources/lang/en-GB/invoices.php
  resources/lang/en-GB/settings.php
  resources/views/purchases/bills/create.blade.php
  resources/views/purchases/bills/edit.blade.php
  resources/views/purchases/bills/item.blade.php
  resources/views/purchases/bills/show.blade.php
  resources/views/sales/invoices/create.blade.php
  resources/views/sales/invoices/edit.blade.php
  resources/views/sales/invoices/item.blade.php
  resources/views/sales/invoices/show.blade.php
  resources/views/settings/localisation/edit.blade.php
Labels: Feature, Language Change

#1382 Cancel invoice/bill
  app/Abstracts/DocumentModel.php
  app/BulkActions/Purchases/Bills.php
  app/BulkActions/Sales/Invoices.php
  app/Events/Purchase/BillCancelled.php
  app/Events/Sale/InvoiceCancelled.php
  app/Http/Controllers/Purchases/Bills.php
  app/Http/Controllers/Sales/Invoices.php
  app/Jobs/Purchase/CancelBill.php
  app/Jobs/Sale/CancelInvoice.php
  app/Listeners/Purchase/MarkBillCancelled.php
  app/Listeners/Purchase/MarkBillReceived.php
  app/Listeners/Sale/MarkInvoiceCancelled.php
  app/Listeners/Sale/MarkInvoiceSent.php
  app/Listeners/Sale/MarkInvoiceViewed.php
  app/Providers/Event.php
  app/Traits/Purchases.php
  app/Traits/Sales.php
  database/factories/Bill.php
  database/factories/Invoice.php
  public/css/akaunting-color.css
  resources/lang/en-GB/bills.php
  resources/lang/en-GB/bulk_actions.php
  resources/lang/en-GB/invoices.php
  resources/views/portal/invoices/show.blade.php
  resources/views/portal/invoices/signed.blade.php
  resources/views/purchases/bills/index.blade.php
  resources/views/purchases/bills/show.blade.php
  resources/views/sales/invoices/index.blade.php
  resources/views/sales/invoices/show.blade.php
  routes/admin.php
Labels: Feature, Language Change

#1383 Fixed portal profile update
  app/Http/Controllers/Portal/Profile.php
Labels: Bug

#1386 Updated translations
  resources/lang/bg-BG/bills.php
  resources/lang/bg-BG/bulk_actions.php
  resources/lang/bg-BG/install.php
  resources/lang/bg-BG/invoices.php
  resources/lang/bg-BG/settings.php
  resources/lang/bn-BD/bills.php
  resources/lang/bn-BD/bulk_actions.php
  resources/lang/bn-BD/install.php
  resources/lang/bn-BD/invoices.php
  resources/lang/bn-BD/settings.php
  resources/lang/da-DK/bills.php
  resources/lang/da-DK/bulk_actions.php
  resources/lang/da-DK/install.php
  resources/lang/da-DK/invoices.php
  resources/lang/da-DK/settings.php
  resources/lang/de-DE/bills.php
  resources/lang/de-DE/bulk_actions.php
  resources/lang/de-DE/install.php
  resources/lang/de-DE/invoices.php
  resources/lang/de-DE/messages.php
  resources/lang/de-DE/settings.php
  resources/lang/es-MX/bills.php
  resources/lang/es-MX/bulk_actions.php
  resources/lang/es-MX/install.php
  resources/lang/es-MX/invoices.php
  resources/lang/es-MX/messages.php
  resources/lang/es-MX/passwords.php
  resources/lang/es-MX/settings.php
  resources/lang/es-MX/validation.php
  resources/lang/it-IT/bills.php
  resources/lang/it-IT/bulk_actions.php
  resources/lang/it-IT/install.php
  resources/lang/it-IT/invoices.php
  resources/lang/it-IT/settings.php
  resources/lang/nb-NO/bills.php
  resources/lang/nb-NO/bulk_actions.php
  resources/lang/nb-NO/install.php
  resources/lang/nb-NO/invoices.php
  resources/lang/nb-NO/settings.php
  resources/lang/pt-BR/bills.php
  resources/lang/pt-BR/bulk_actions.php
  resources/lang/pt-BR/install.php
  resources/lang/pt-BR/invoices.php
  resources/lang/pt-BR/settings.php
  resources/lang/tr-TR/bills.php
  resources/lang/tr-TR/bulk_actions.php
  resources/lang/tr-TR/install.php
  resources/lang/tr-TR/invoices.php
  resources/lang/tr-TR/modules.php
  resources/lang/tr-TR/settings.php
Labels: Enhancement
