Repository akaunting/akaunting, pull requests merged in 2020-10, with the labels that each got.

#1627 Import export for Transfers
  app/BulkActions/Banking/Transfers.php
  app/Exports/Banking/Transfers.php
  app/Http/Controllers/Banking/Transfers.php
  app/Imports/Banking/Transfers.php
  public/files/import/transfers.xlsx
  resources/views/banking/transfers/index.blade.php
  routes/admin.php
  tests/Feature/Banking/TransfersTest.php
Labels: Feature

#1631 Fix duplicate stack for item name input in edit invoice view
  resources/views/sales/invoices/item.blade.php
Labels: Bug

#1634 Debug js files
  webpack.mix.js
Labels: Enhancement

#1632 Format excel date cells as date for import/export
  app/Abstracts/Export.php
  app/Abstracts/Import.php
  app/Imports/Banking/Transfers.php
  public/files/import/bills.xlsx
  public/files/import/invoices.xlsx
  public/files/import/payments.xlsx
  public/files/import/revenues.xlsx
  public/files/import/transactions.xlsx
  public/files/import/transfers.xlsx
Labels: Enhancement

#1635 Menu glitch in mobile and tablet views
  public/css/custom.css
  resources/views/partials/admin/scripts.blade.php
Labels: Bug

#1641 Menu glitch in mobile and tablet views
  public/css/custom.css
  resources/views/partials/admin/scripts.blade.php
Labels: Bug
