Repository akaunting/akaunting, pull requests merged in 2021-11, with the labels that each got.

#2296 Currency index page style updated.
  resources/views/settings/currencies/index.blade.php
Labels: Bug

#2299 Fix passing custom routes to the SelectContactCard component.
  app/View/Components/SelectContactCard.php
  resources/views/components/documents/form/content.blade.php
  resources/views/components/documents/form/main.blade.php
  resources/views/components/documents/form/metadata.blade.php
  resources/views/components/select-contact-card.blade.php
Labels: Enhancement

#2297 Fix a duplication of the extension when uploading files.
  app/Traits/Uploads.php
  tests/Feature/Purchases/BillsTest.php
  tests/Feature/Sales/InvoicesTest.php
Labels: Bug

#2302 Account show page test added
  app/Http/Controllers/Banking/Accounts.php
  tests/Feature/Banking/AccountsTest.php
Labels: Enhancement

#2305 Fix not changing document templates and colours for modules
  app/Abstracts/View/Components/DocumentShow.php
  app/Abstracts/View/Components/DocumentTemplate.php
  app/Abstracts/View/Components/TransactionShow.php
Labels: Bug

#2313 Missing country, city, etc columns for import files.
  app/Http/Requests/Document/DocumentItem.php
  public/files/import/bills.xlsx
  public/files/import/customers.xlsx
  public/files/import/invoices.xlsx
  public/files/import/vendors.xlsx
Labels: Bug

#2314 Import validate issue fixed
  app/Traits/Import.php
Labels: Bug

#2316 Images and gifs bugfix solved in apps page
  resources/views/modules/item/documentation.blade.php
Labels: Bug

#2317 route fixed
  resources/views/purchases/payments/index.blade.php
Labels: Bug

#2318 fixed typo
  app/Abstracts/View/Components/TransactionShow.php
  app/Abstracts/View/Components/TransactionTemplate.php
  app/Abstracts/View/Components/TransferShow.php
  app/Abstracts/View/Components/TransferTemplate.php
  resources/lang/en-GB/payments.php
  resources/lang/en-GB/revenues.php
  resources/views/components/transactions/show/content.blade.php
  resources/views/components/transactions/show/transaction.blade.php
  resources/views/components/transactions/template/default.blade.php
Labels: Code Style, Language Change

#2322 route prefix fixed #1v0ueh7
  app/Abstracts/View/Components/DocumentShow.php
  app/Abstracts/View/Components/TransactionShow.php
  resources/views/components/documents/show/recurring-message.blade.php
  resources/views/components/transactions/show/recurring-message.blade.php
Labels: Bug

#2321 issue fixed using helper method #1v0u2zu
  resources/views/components/transactions/show/recurring-message.blade.php
Labels: Bug

#2323 Duplicate click issue fix
  resources/views/components/documents/show/timeline.blade.php
Labels: Bug
