Repository akaunting/akaunting, pull requests merged in 2021-07, with the labels that each got.

#2171 Currency conversion total edited for Invoices and Bills page.
  resources/assets/js/components/AkauntingCurrencyConversion.vue
  resources/assets/js/views/common/documents.js
  resources/views/components/documents/form/totals.blade.php
  resources/views/partials/admin/scripts.blade.php
Labels: Bug

#2173 Browser list updated
  package-lock.json
Labels: Enhancement

#2175 Price inputs formatted in edit & create items page
  resources/assets/js/views/common/items.js
Labels: Bug

#2176 Design edited in show pages for preview pdf
  resources/views/components/transactions/template/default.blade.php
Labels: Bug

#2182 Date inputs update in relation to admin payment term settings
  resources/assets/js/components/AkauntingDate.vue
  resources/views/banking/reconciliations/create.blade.php
  resources/views/components/documents/form/metadata.blade.php
  resources/views/partials/admin/scripts.blade.php
  resources/views/partials/portal/scripts.blade.php
Labels: Bug

#2183 time group 24hours attribute added
  resources/views/partials/form/time_group.blade.php
Labels: Enhancement

#2184 Fix portal dashboard redirection
  app/Traits/Users.php
Labels: Bug

#2185 Added transfer show page
  app/Abstracts/View/Components/TransferShow.php
  app/Abstracts/View/Components/TransferTemplate.php
  app/Events/Banking/TransferPrinting.php
  app/Http/Controllers/Banking/Transfers.php
  app/Http/Controllers/Modals/TransferTemplates.php
  app/Jobs/Banking/CreateTransfer.php
  app/Jobs/Banking/UpdateTransfer.php
  app/Models/Banking/Transfer.php
  app/View/Components/Transfers/Script.php
  app/View/Components/Transfers/Show/Attachment.php
  app/View/Components/Transfers/Show/Content.php
  app/View/Components/Transfers/Show/Footer.php
  app/View/Components/Transfers/Show/Header.php
  app/View/Components/Transfers/Show/Histories.php
  app/View/Components/Transfers/Show/TopButtons.php
  app/View/Components/Transfers/Show/Transfer.php
  app/View/Components/Transfers/Template/Ddefault.php
  app/View/Components/Transfers/Template/Second.php
  app/View/Components/Transfers/Template/Third.php
  config/setting.php
  public/img/transfer_templates/default.png
  public/img/transfer_templates/second.png
  public/img/transfer_templates/third.png
  resources/assets/js/views/banking/transfers.js
  resources/lang/en-GB/transfers.php
  resources/views/banking/transfers/create.blade.php
  resources/views/banking/transfers/edit.blade.php
  resources/views/banking/transfers/index.blade.php
  resources/views/banking/transfers/print_default.blade.php
  resources/views/banking/transfers/print_second.blade.php
  resources/views/banking/transfers/print_third.blade.php
  resources/views/banking/transfers/show.blade.php
  resources/views/components/transfers/script.blade.php
  resources/views/components/transfers/show/attachment.blade.php
  resources/views/components/transfers/show/content.blade.php
  resources/views/components/transfers/show/footer.blade.php
  resources/views/components/transfers/show/header.blade.php
  resources/views/components/transfers/show/histories.blade.php
  resources/views/components/transfers/show/top-buttons.blade.php
  resources/views/components/transfers/show/transfer.blade.php
  resources/views/components/transfers/template/default.blade.php
  resources/views/components/transfers/template/second.blade.php
  resources/views/components/transfers/template/third.blade.php
  resources/views/modals/settings/transfer_template.blade.php
  routes/admin.php
  tests/Feature/Banking/TransfersTest.php
Labels: Feature, Language Change

#2188 View of amounts edited for Reconciliation page
  resources/assets/js/views/banking/reconciliations.js
  resources/views/banking/reconciliations/create.blade.php
  resources/views/banking/reconciliations/edit.blade.php
Labels: Bug

#2190 fix: Update module edit form to allow number input
  resources/views/settings/modules/edit.blade.php
Labels: Enhancement

#2200 Fetch items only after default character limit is reached
  app/Abstracts/View/Components/DocumentForm.php
  app/View/Components/SelectItemButton.php
  config/setting.php
  resources/assets/js/components/AkauntingItemButton.vue
  resources/views/components/documents/form/content.blade.php
  resources/views/components/documents/form/items.blade.php
  resources/views/components/documents/form/main.blade.php
  resources/views/components/select-item-button.blade.php
Labels: Enhancement

#2202 makes possible right validation for temporary signed routes
  app/Http/Middleware/ValidateSignature.php
Labels: Enhancement

#2203 Transfer page currency rate enhancement
  app/Http/Controllers/Banking/Transfers.php
  app/Models/Banking/Transfer.php
  resources/assets/js/views/banking/transfers.js
  resources/views/banking/transfers/create.blade.php
  resources/views/banking/transfers/edit.blade.php
  resources/views/components/transfers/show/header.blade.php
  resources/views/partials/form/text_group.blade.php
Labels: Enhancement

#2204 Report print not showing chart
  resources/views/layouts/print.blade.php
  resources/views/partials/print/scripts.blade.php
Labels: Bug

#2210 Disable non-numeric and negative values for quantity input
  public/css/custom.css
  resources/views/components/documents/form/line-item.blade.php
Labels: Enhancement

#2211 Redirect link for bulk actions
  app/Http/Controllers/Common/BulkActions.php
  resources/assets/js/plugins/bulk-action.js
Labels: Enhancement
