Repository akaunting/akaunting, pull requests merged in 2021-05, with the labels that each got.

#2013 Change storeInvoicePdfAndGetPath method to storeDocumentPdfAndGetPath…
  app/Notifications/Portal/PaymentReceived.php
  app/Notifications/Sale/Invoice.php
  app/Traits/Documents.php
Labels: Enhancement

#1981 Move document footer to the end of the document
  public/css/print.css
  resources/views/components/documents/template/classic.blade.php
  resources/views/components/documents/template/default.blade.php
Labels: Enhancement

#2014 Category name edited for long text
  resources/views/common/items/index.blade.php
  resources/views/purchases/payments/index.blade.php
  resources/views/sales/revenues/index.blade.php
Labels: Enhancement

#2015 Add item bugfix solved for ios mobile devices
  public/css/custom.css
Labels: Bug

#2019 Customer export test fails when the apps create a customer in their t…
  tests/Feature/Sales/CustomersTest.php
Labels: Bug

#2028 Admin not able to print/pdf signed invoice
  app/Http/Requests/Portal/InvoiceShow.php
Labels: Bug

#2029 previous quarter shortcut on the dashboard date filter fixed
  app/Traits/DateTime.php
Labels: Bug

#2046 Add company_id column to media tables
  app/Listeners/Update/V21/Version2114.php
  app/Models/Common/Media.php
  app/Providers/Event.php
  app/Scopes/Company.php
  app/Traits/Media.php
  app/Traits/Uploads.php
  database/migrations/2021_05_17_000000_core_v2114.php
Labels: Enhancement

#2053 'Element-ui popper position bugfix solved'
  public/css/custom.css
Labels: Bug

#2056 Added Translations api endpoint
  app/Http/Controllers/Api/Common/Translations.php
  routes/api.php
Labels: Feature

#2060 Allow modules to provide a custom title for the "advanced" section in a document
  app/Abstracts/View/Components/DocumentForm.php
  resources/views/components/documents/form/advanced.blade.php
Labels: Enhancement

#2064 Wizard
  app/Http/Controllers/Settings/Settings.php
  app/Http/Controllers/Wizard/Companies.php
  app/Http/Controllers/Wizard/Currencies.php
  app/Http/Controllers/Wizard/Data.php
  app/Http/Controllers/Wizard/Finish.php
  app/Http/Controllers/Wizard/Taxes.php
  resources/assets/js/Wizard.vue
  resources/assets/js/components/AkauntingDate.vue
  resources/assets/js/components/AkauntingDropzoneFileUpload.vue
  resources/assets/js/components/forms/AkauntingRadioGroup.vue
  resources/assets/js/mixins/global.js
  resources/assets/js/mixins/wizardAction.js
  resources/assets/js/views/wizard/Company.vue
  resources/assets/js/views/wizard/Currencies.vue
  resources/assets/js/views/wizard/Finish.vue
  resources/assets/js/views/wizard/Taxes.vue
  resources/assets/js/views/wizard/company.js
  resources/assets/js/views/wizard/currencies.js
  resources/assets/js/views/wizard/finish.js
  resources/assets/js/views/wizard/taxes.js
  resources/assets/js/wizard.js
  resources/views/layouts/wizard.blade.php
  resources/views/partials/wizard/content.blade.php
  resources/views/partials/wizard/pagination.blade.php
  resources/views/partials/wizard/scripts.blade.php
  resources/views/wizard/companies/edit.blade.php
  resources/views/wizard/currencies/index.blade.php
  resources/views/wizard/finish/index.blade.php
  resources/views/wizard/taxes/index.blade.php
  routes/wizard.php
  tests/Feature/Wizard/CompaniesTest.php
  tests/Feature/Wizard/CurrenciesTest.php
  tests/Feature/Wizard/TaxesTest.php
  webpack.mix.js
Labels: Enhancement

#2066 Changed api show and store method..
  app/Http/Controllers/Api/Auth/Permissions.php
  app/Http/Controllers/Api/Auth/Roles.php
  app/Http/Controllers/Api/Auth/Users.php
  app/Http/Controllers/Api/Banking/Accounts.php
  app/Http/Controllers/Api/Banking/Reconciliations.php
  app/Http/Controllers/Api/Banking/Transactions.php
  app/Http/Controllers/Api/Banking/Transfers.php
  app/Http/Controllers/Api/Common/Companies.php
  app/Http/Controllers/Api/Common/Contacts.php
  app/Http/Controllers/Api/Common/Dashboards.php
  app/Http/Controllers/Api/Common/Items.php
  app/Http/Controllers/Api/Common/Reports.php
  app/Http/Controllers/Api/Document/DocumentTransactions.php
  app/Http/Controllers/Api/Document/Documents.php
  app/Http/Controllers/Api/Settings/Categories.php
  app/Http/Controllers/Api/Settings/Currencies.php
  app/Http/Controllers/Api/Settings/Settings.php
  app/Http/Controllers/Api/Settings/Taxes.php
Labels: Enhancement

#2068 Added app changelog pagination
  app/Http/Controllers/Modules/Item.php
  app/Traits/Modules.php
  resources/assets/js/views/modules/item.js
  resources/views/modules/item/show.blade.php
  resources/views/partials/modules/releases.blade.php
Labels: Enhancement

#2069 Invoice styling bugfix edited
  resources/views/components/documents/form/line-item.blade.php
Labels: Enhancement

#2071 Console errors
  resources/assets/js/components/AkauntingModalAddNew.vue
  resources/assets/js/components/AkauntingSelect.vue
  resources/assets/js/components/AkauntingSelectRemote.vue
Labels: Bug
