Repository akaunting/akaunting, pull requests merged in 2021-09, with the labels that each got.

#2238 Permissions arranged
  resources/views/banking/accounts/index.blade.php
  resources/views/banking/transfers/index.blade.php
  resources/views/partials/documents/index/card-table-row.blade.php
  resources/views/purchases/payments/index.blade.php
  resources/views/purchases/vendors/index.blade.php
  resources/views/sales/customers/index.blade.php
  resources/views/sales/revenues/index.blade.php
Labels: Enhancement

#2215 Improve UI on add/edit items on invoice & bill pages
  public/css/akaunting-color.css
  resources/assets/js/components/AkauntingContactCard.vue
  resources/assets/js/components/AkauntingDate.vue
  resources/assets/js/components/AkauntingItemButton.vue
  resources/assets/js/plugins/functions.js
  resources/assets/js/views/common/documents.js
  resources/views/components/documents/form/buttons.blade.php
  resources/views/components/documents/form/line-item.blade.php
  resources/views/partials/form/money_group.blade.php
Labels: Enhancement

#2239 Format currencies on cash flow widget tooltip and yAxes
  app/Traits/Charts.php
Labels: Enhancement

#2243 wizard company country dropdown options issue
  resources/views/partials/wizard/scripts.blade.php
Labels: Bug

#2242 format fixed on document factories
  database/factories/Document.php
Labels: Code Style

#2241 Allow to add Module's fields to the search and filter
  app/Abstracts/Model.php
  app/Events/Common/SearchStringApplied.php
  app/Events/Common/SearchStringApplying.php
  app/View/Components/SearchString.php
Labels: Enhancement

#2256 country field value changed to `company.country` (#1hwqn9e)
  app/Http/Controllers/Wizard/Companies.php
  app/Jobs/Common/CreateCompany.php
  resources/views/modals/customers/create.blade.php
  resources/views/modals/vendors/create.blade.php
  resources/views/purchases/vendors/create.blade.php
  resources/views/sales/customers/create.blade.php
  resources/views/settings/default/edit.blade.php
Labels: Enhancement

#2264 Popover styling broken in document pages
  resources/views/components/documents/form/totals.blade.php
Labels: Bug

#2249 Get source from the request if the document's item has not item_id
  app/Jobs/Document/CreateDocumentItemsAndTotals.php
Labels: Bug

#2271 portal customer address details added
  resources/views/portal/profile/edit.blade.php
Labels: Enhancement
