Repository akaunting/akaunting, pull requests merged in 2021-06, with the labels that each got.

#2073 Search & Filter set default filter.
  app/View/Components/SearchString.php
  resources/assets/js/components/AkauntingSearch.vue
  resources/views/components/search-string.blade.php
Labels: Feature

#2074 Report show set default financial year filter.
  app/Traits/DateTime.php
  resources/lang/en-GB/general.php
  resources/views/partials/reports/filter.blade.php
Labels: Enhancement, Language Change

#2072 Spin styling, modules bugfix and file upload bugfix
  app/Http/Controllers/Wizard/Data.php
  resources/assets/js/Wizard.vue
  resources/assets/js/views/wizard/Company.vue
  resources/assets/js/views/wizard/Currencies.vue
  resources/assets/js/views/wizard/Finish.vue
  resources/assets/js/views/wizard/Taxes.vue
  resources/views/layouts/wizard.blade.php
Labels: Enhancement

#2075 Wizard page re-factoring..
  app/Http/ViewComposers/Wizard.php
  app/Providers/ViewComposer.php
  resources/assets/js/Wizard.vue
  resources/assets/js/views/wizard/Company.vue
  resources/views/partials/wizard/scripts.blade.php
  routes/wizard.php
Labels: Enhancement

#2077 Date time picker can't correct work when I change default language.
  public/css/custom.css
  resources/assets/js/views/wizard/Company.vue
  resources/views/layouts/wizard.blade.php
  resources/views/partials/form/date_group.blade.php
Labels: Bug

#2079 Default english language error occured
  resources/assets/js/views/wizard/Company.vue
Labels: Bug

#2080 Added missing migration from 2.1.12
  app/Listeners/Update/V21/Version2114.php
  app/Listeners/Update/V21/Version2116.php
  app/Providers/Event.php
Labels: Bug

#2082 Delete ıtem modal class removed
  resources/assets/js/mixins/wizardAction.js
Labels: Bug

#2081 Currencies bugfix change language
  resources/views/partials/form/bulk_action_row_group.blade.php
Labels: Bug

#2078 Invoice styling bugfix
  public/css/custom.css
  resources/views/components/documents/form/line-item.blade.php
Labels: Bug

#2085 global search based on livewire improved
  app/Http/Controllers/Common/Search.php
  app/Http/Livewire/Common/Search.php
  composer.json
  overrides/livewire/LivewireServiceProvider.php
  resources/assets/js/views/common/search.js
  resources/views/livewire/common/search.blade.php
  resources/views/partials/admin/navbar.blade.php
  resources/views/partials/admin/scripts.blade.php
  routes/admin.php
  webpack.mix.js
Labels: Feature

#2086 Portal dashboard added date filter
  app/Http/Controllers/Portal/Dashboard.php
  resources/assets/js/views/portal/dashboard.js
  resources/views/portal/dashboard/index.blade.php
Labels: Feature

#2084 Invoice and Bill 'Add an Item' area styling development
  public/css/custom.css
  resources/views/components/documents/form/line-item.blade.php
  resources/views/components/documents/form/totals.blade.php
Labels: Bug

#2093 Named parameter in PHP 8
  app/Abstracts/View/Components/DocumentTemplate.php
Labels: Bug

#2094 Login, Forget Password console error fixed.
  resources/views/layouts/auth.blade.php
Labels: Enhancement

#2095 module import download 'xls|xslx' format added
  .htaccess
  nginx.example.com.conf
Labels: Bug

#2097 Icon background color edited for Reports Page.
  public/css/akaunting-color.css
  public/css/custom.css
  resources/views/components/documents/form/line-item.blade.php
Labels: Bug

#2100 Left menu active item color fix
  public/css/akaunting-color.css
Labels: Bug

#2106 Closing Balance, Cleared Amount and Difference currency showed of Reconciliation Page
  public/css/akaunting-color.css
  public/css/custom.css
  resources/views/banking/reconciliations/create.blade.php
  resources/views/banking/reconciliations/edit.blade.php
Labels: Bug

#2107 Transaction button styling changed at the Create page of Reconciliation page
  resources/views/banking/reconciliations/create.blade.php
Labels: Enhancement

#2108 Long text problem at the Invoice and Bills page.
  resources/assets/js/components/AkauntingContactCard.vue
Labels: Bug

#2109 Report page per widget clear own cache
  app/Abstracts/Report.php
  app/Console/Commands/ReportReminder.php
  app/Console/Kernel.php
  app/Http/Controllers/Common/Reports.php
  resources/assets/js/views/common/reports.js
  resources/views/common/reports/index.blade.php
  routes/admin.php
Labels: Enhancement

#2110 Fixed User set locale, but not working translation
  app/Jobs/Install/DisableModule.php
  app/Jobs/Install/EnableModule.php
  app/Jobs/Install/InstallModule.php
  app/Jobs/Install/UninstallModule.php
  app/Utilities/Overrider.php
  database/seeds/Modules.php
  database/seeds/TestCompany.php
Labels: Bug

#2111 Small right button structure edited in the Card view.
  resources/views/common/reports/index.blade.php
  resources/views/partials/widgets/stats_header.blade.php
Labels: Enhancement

#2112 Added record ownership
  app/Abstracts/Import.php
  app/Abstracts/Model.php
  app/Jobs/Banking/CreateAccount.php
  app/Jobs/Banking/CreateBankingDocumentTransaction.php
  app/Jobs/Banking/CreateReconciliation.php
  app/Jobs/Banking/CreateTransaction.php
  app/Jobs/Banking/CreateTransfer.php
  app/Jobs/Common/CreateCompany.php
  app/Jobs/Common/CreateContact.php
  app/Jobs/Common/CreateDashboard.php
  app/Jobs/Common/CreateItem.php
  app/Jobs/Common/CreateReport.php
  app/Jobs/Document/CreateDocument.php
  app/Jobs/Setting/CreateCategory.php
  app/Jobs/Setting/CreateCurrency.php
  app/Jobs/Setting/CreateTax.php
  app/Listeners/Update/V21/Version2117.php
  app/Models/Auth/Permission.php
  app/Models/Auth/Role.php
  app/Models/Auth/User.php
  app/Models/Banking/Account.php
  app/Models/Banking/Reconciliation.php
  app/Models/Banking/Transaction.php
  app/Models/Banking/Transfer.php
  app/Models/Common/Company.php
  app/Models/Common/Contact.php
  app/Models/Common/Dashboard.php
  app/Models/Common/Item.php
  app/Models/Common/Recurring.php
  app/Models/Common/Report.php
  app/Models/Common/Widget.php
  app/Models/Document/Document.php
  app/Models/Setting/Category.php
  app/Models/Setting/Currency.php
  app/Models/Setting/Setting.php
  app/Models/Setting/Tax.php
  app/Traits/Owners.php
  app/Traits/Tenants.php
  app/Transformers/Banking/Account.php
  app/Transformers/Banking/Reconciliation.php
  app/Transformers/Banking/Transaction.php
  app/Transformers/Banking/Transfer.php
  app/Transformers/Common/Company.php
  app/Transformers/Common/Contact.php
  app/Transformers/Common/Dashboard.php
  app/Transformers/Common/Item.php
  app/Transformers/Common/Report.php
  app/Transformers/Common/Widget.php
  app/Transformers/Document/Document.php
  app/Transformers/Setting/Category.php
  app/Transformers/Setting/Currency.php
  app/Transformers/Setting/Tax.php
  app/Utilities/helpers.php
  database/migrations/2021_06_17_000000_core_v2117.php
Labels: Feature

#2117 Show validation errors on Reset Password page
  app/Http/Controllers/Auth/Reset.php
  resources/views/auth/reset/create.blade.php
Labels: Bug

#2118 Flatpickr minimum date controlled Invoice and Reconciliations page.
  resources/assets/js/components/AkauntingDate.vue
  resources/assets/js/views/banking/reconciliations.js
  resources/assets/js/views/common/documents.js
  resources/views/banking/reconciliations/create.blade.php
  resources/views/components/documents/form/metadata.blade.php
  resources/views/partials/form/date_group.blade.php
Labels: Enhancement

#2120 Added Notification page
  app/Abstracts/Export.php
  app/Abstracts/Livewire/Document.php
  app/Http/Controllers/Common/Notifications.php
  app/Http/Livewire/Common/Notifications/Exports.php
  app/Http/Livewire/Common/Notifications/Imports.php
  app/Http/Livewire/Common/Notifications/NewApps.php
  app/Http/Livewire/Common/Notifications/Recurring.php
  app/Http/Livewire/Common/Notifications/Reminder.php
  app/Http/ViewComposers/Header.php
  app/Jobs/Common/CreateMediableForExport.php
  app/Notifications/Common/ExportCompleted.php
  app/Notifications/Common/ExportFailed.php
  app/Notifications/Common/ImportCompleted.php
  app/Notifications/Common/ImportFailed.php
  app/Notifications/Portal/PaymentReceived.php
  app/Notifications/Purchase/Bill.php
  app/Notifications/Sale/Invoice.php
  app/Utilities/Export.php
  app/Utilities/Import.php
  public/vendor/bootstrap-notify/bootstrap-notify.min.js
  resources/lang/en-GB/general.php
  resources/lang/en-GB/header.php
  resources/lang/en-GB/notifications.php
  resources/views/common/notifications/index.blade.php
  resources/views/livewire/common/notifications/exports.blade.php
  resources/views/livewire/common/notifications/imports.blade.php
  resources/views/livewire/common/notifications/new-apps.blade.php
  resources/views/livewire/common/notifications/recurring.blade.php
  resources/views/livewire/common/notifications/reminder.blade.php
  resources/views/partials/admin/navbar.blade.php
  resources/views/partials/admin/scripts.blade.php
  resources/views/vendor/livewire/bootstrap.blade.php
  resources/views/vendor/livewire/default.blade.php
  resources/views/vendor/livewire/simple-bootstrap.blade.php
  resources/views/vendor/livewire/simple-tailwind.blade.php
  resources/views/vendor/livewire/tailwind.blade.php
  routes/admin.php
Labels: Feature, Language Change

#2125 DashboardsTest updated and Widget factory added.
  app/Models/Common/Widget.php
  database/factories/Widget.php
  tests/Feature/Common/DashboardsTest.php
Labels: Enhancement

#2123 All long texts controlled for all items page.
  resources/views/banking/accounts/index.blade.php
  resources/views/banking/reconciliations/index.blade.php
  resources/views/banking/transactions/index.blade.php
  resources/views/banking/transfers/index.blade.php
  resources/views/purchases/payments/index.blade.php
  resources/views/purchases/vendors/index.blade.php
  resources/views/sales/customers/index.blade.php
  resources/views/sales/revenues/index.blade.php
Labels: Enhancement

#2132 Name not show where it is used "col-aka" classname
  app/Abstracts/View/Components/DocumentIndex.php
  resources/views/purchases/vendors/index.blade.php
  resources/views/sales/customers/index.blade.php
Labels: Bug

#2129 Textarea value not show in Bootstrap modal.
  resources/views/modals/customers/edit.blade.php
  resources/views/modals/vendors/edit.blade.php
  resources/views/partials/form/textarea_group.blade.php
Labels: Bug

#2137 Responsive control edited as Boostrap show-hide classname.(#9hzxey)
  resources/views/auth/users/index.blade.php
  resources/views/common/items/index.blade.php
  resources/views/partials/widgets/standard_header.blade.php
Labels: Bug

#2136 module history description is fixed #mz7u2p
  app/Listeners/Update/CreateModuleUpdatedHistory.php
  resources/lang/en-GB/modules.php
Labels: Bug

#2139 Prevents making unnecessary requests for global search
  resources/views/livewire/common/search.blade.php
Labels: Bug

#2145 Added limit to import
  app/Abstracts/Import.php
  app/Http/Requests/Common/Import.php
  config/excel.php
  resources/lang/en-GB/import.php
  resources/views/common/import/create.blade.php
Labels: Feature

#2147 Added scope for collection export
  app/Abstracts/Model.php
  app/Exports/Banking/Transactions.php
  app/Exports/Banking/Transfers.php
  app/Exports/Common/Sheets/ItemTaxes.php
  app/Exports/Common/Sheets/Items.php
  app/Exports/Purchases/Payments.php
  app/Exports/Purchases/Sheets/BillHistories.php
  app/Exports/Purchases/Sheets/BillItemTaxes.php
  app/Exports/Purchases/Sheets/BillItems.php
  app/Exports/Purchases/Sheets/BillTotals.php
  app/Exports/Purchases/Sheets/BillTransactions.php
  app/Exports/Purchases/Sheets/Bills.php
  app/Exports/Purchases/Vendors.php
  app/Exports/Sales/Customers.php
  app/Exports/Sales/Revenues.php
  app/Exports/Sales/Sheets/InvoiceHistories.php
  app/Exports/Sales/Sheets/InvoiceItemTaxes.php
  app/Exports/Sales/Sheets/InvoiceItems.php
  app/Exports/Sales/Sheets/InvoiceTotals.php
  app/Exports/Sales/Sheets/InvoiceTransactions.php
  app/Exports/Sales/Sheets/Invoices.php
  app/Exports/Settings/Categories.php
  resources/lang/en-GB/messages.php
Labels: Enhancement

#2149 Notification page styling
  app/Http/Controllers/Common/Notifications.php
  app/Http/Livewire/Common/Notifications/NewApps.php
  resources/views/common/notifications/index.blade.php
  resources/views/livewire/common/notifications/exports.blade.php
  resources/views/livewire/common/notifications/imports.blade.php
  resources/views/livewire/common/notifications/new-apps.blade.php
  resources/views/livewire/common/notifications/recurring.blade.php
  resources/views/livewire/common/notifications/reminder.blade.php
Labels: Enhancement

#2156 stacks added for transaction default component
  resources/views/components/transactions/template/default.blade.php
Labels: Enhancement

#2157 Currency conversion development for ınovices and Bills page.
  resources/assets/js/components/AkauntingCurrencyConversion.vue
  resources/assets/js/views/common/documents.js
  resources/views/components/documents/form/totals.blade.php
Labels: Enhancement

#2159 MultipleSheets import validation message (#mx7kmv)
  app/Abstracts/ImportMultipleSheets.php
  app/Imports/Common/Items.php
  app/Imports/Purchases/Bills.php
  app/Imports/Sales/Invoices.php
  app/Providers/Queue.php
Labels: Bug

#2160 Add an ability to the AkauntingSelect component to show options as is…
  resources/assets/js/components/AkauntingSelect.vue
  resources/views/partials/form/select_group.blade.php
Labels: Enhancement

#2161 "Select Remote" component edited for empty data.
  resources/assets/js/components/AkauntingSelectRemote.vue
Labels: Enhancement

#2162 Allow using the dependent validation rules in import.
  app/Abstracts/Import.php
  app/Imports/Purchases/Sheets/Bills.php
  app/Imports/Sales/Sheets/Invoices.php
Labels: Enhancement

#2163 Search box not show when the page is first loaded.
  resources/assets/js/components/AkauntingSearch.vue
  resources/views/components/search-string.blade.php
Labels: Enhancement

#2164 Customer show page styling..
  app/Http/Controllers/Sales/Customers.php
  resources/lang/en-GB/revenues.php
  resources/views/sales/customers/index.blade.php
  resources/views/sales/customers/show.blade.php
  resources/views/sales/revenues/create.blade.php
  routes/admin.php
Labels: Enhancement

#2165 Textarea value not show all pages.
  resources/views/partials/form/textarea_group.blade.php
Labels: Bug

#2166 Optimize using the dependent validation rules in import.
  app/Abstracts/Import.php
Labels: Enhancement

#2167 Show template development done for Vendor page.
  app/Http/Controllers/Purchases/Vendors.php
  resources/assets/js/views/purchases/vendors.js
  resources/assets/js/views/sales/customers.js
  resources/lang/en-GB/payments.php
  resources/views/purchases/payments/create.blade.php
  resources/views/purchases/vendors/index.blade.php
  resources/views/purchases/vendors/show.blade.php
Labels: Enhancement

#2169 Search box done development for blade
  resources/assets/js/components/AkauntingSearch.vue
  resources/views/components/search-string.blade.php
  resources/views/partials/admin/scripts.blade.php
Labels: Bug

#2170 Default currency edited for conversion
  resources/assets/js/components/AkauntingCurrencyConversion.vue
  resources/assets/js/views/common/documents.js
Labels: Bug
