Repository akaunting/akaunting, pull requests merged in 2021-04, with the labels that each got.

#1960 Added bootstrap's source map files
  public/vendor/bootstrap/dist/css/bootstrap-grid.min.css.map
  public/vendor/bootstrap/dist/css/bootstrap-reboot.min.css.map
  public/vendor/bootstrap/dist/css/bootstrap.min.css.map
  public/vendor/bootstrap/dist/js/bootstrap.bundle.min.js.map
  public/vendor/bootstrap/dist/js/bootstrap.min.js.map
Labels: Bug

#1968 Add permissions for landing pages
  app/Listeners/Auth/AddLandingPages.php
Labels: Enhancement

#1972 Fix landing page issue
  app/Exceptions/Handler.php
Labels: Enhancement

#1973 Add readonly attribute for text editor
  resources/assets/js/components/AkauntingHtmlEditor.vue
  resources/views/partials/form/text_editor_group.blade.php
Labels: Enhancement

#1977 Change selected object to array to prevent undefined error forEach on…
  resources/assets/js/components/AkauntingSelectRemote.vue
Labels: Enhancement

#1983 items of request array should be manipulated seperately
  app/Jobs/Document/CreateDocumentItem.php
Labels: Enhancement

#1982 thousands separator and decimal mark must be different
  app/Http/Requests/Setting/Currency.php
Labels: Enhancement

#1988 fix: typo
  resources/lang/en-GB/email_templates.php
Labels: Language Change

#1990 Not sent => Not received for bill
  resources/lang/en-GB/bills.php
Labels: Language Change

#1991 Add Notification class to DocumentReminded event
  app/Console/Commands/RecurringCheck.php
  app/Events/Document/DocumentRecurring.php
  app/Listeners/Document/SendDocumentRecurringNotification.php
Labels: Bug

#1996 Typo fixed
  resources/views/components/documents/show/timeline.blade.php
Labels: Bug

#2007 Added Polish language
  config/language.php
Labels: Feature

#2010 Add company_id into suggestion module's url
  app/Http/ViewComposers/Suggestions.php
Labels: Bug

#2012 Unusage bootstrap variables ejected
  resources/assets/sass/core/utilities/_backgrounds.scss
  resources/assets/sass/core/utilities/_text.scss
Labels: Enhancement

#2011 Update customer/user relationships
  app/Http/Requests/Auth/User.php
  app/Http/Requests/Common/Contact.php
  app/Http/Requests/Portal/Profile.php
  app/Jobs/Auth/UpdateUser.php
  app/Jobs/Common/UpdateContact.php
Labels: Bug
