Repository akaunting/akaunting, pull requests merged in 2021-02, with the labels that each got.

#1822 Document color for modules
  app/Abstracts/View/Components/DocumentTemplate.php
Labels: Bug

#1823 Fix background color typo to be able to sent it from module views
  app/Abstracts/View/Components/DocumentShow.php
  app/Abstracts/View/Components/DocumentTemplate.php
  resources/views/components/documents/show/content.blade.php
  resources/views/components/documents/show/document.blade.php
  resources/views/components/documents/template/classic.blade.php
  resources/views/components/documents/template/default.blade.php
  resources/views/components/documents/template/modern.blade.php
Labels: Bug

#1837 Added Azerbaijani language
  config/language.php
Labels: Feature

#1838 Allow modules to provide a translation for a search filter.
  app/View/Components/SearchString.php
Labels: Enhancement

#1840 Update create.blade.php
  resources/views/sales/customers/create.blade.php
Labels: Bug

#1842 File group drag and drop developement
  app/Http/Controllers/Purchases/Payments.php
  app/Http/Controllers/Sales/Revenues.php
  app/Http/Kernel.php
  app/Http/Middleware/Dropzone.php
  app/Http/Requests/Banking/Transaction.php
  app/Jobs/Banking/CreateTransaction.php
  app/Jobs/Banking/UpdateTransaction.php
  app/Jobs/Document/UpdateDocument.php
  app/Models/Banking/Transaction.php
  app/Traits/Uploads.php
  resources/assets/js/components/AkauntingDropzoneFileUpload.vue
  resources/assets/js/plugins/form.js
  resources/views/partials/form/file_group.blade.php
  resources/views/purchases/payments/create.blade.php
  resources/views/purchases/payments/edit.blade.php
  resources/views/sales/revenues/create.blade.php
  resources/views/sales/revenues/edit.blade.php
  routes/admin.php
  routes/portal.php
Labels: Enhancement

#1844 code refactoring for recent works related to dropzone
  app/Http/Middleware/Dropzone.php
  resources/assets/js/components/AkauntingDropzoneFileUpload.vue
Labels: Enhancement

#1847 Missing 'Edit your business address' translation
  resources/lang/en-GB/items.php
  resources/lang/en-GB/settings.php
  resources/views/components/documents/form/company.blade.php
  resources/views/components/documents/form/line-item.blade.php
Labels: Language Change

#1848 Wrong company details on invoice create page
  app/View/Components/Documents/Form/Company.php
Labels: Bug

#1846 Fix transfers import
  app/Imports/Banking/Transfers.php
Labels: Bug

#1849 Add hidden category_id input if it's hidden
  resources/views/components/documents/form/advanced.blade.php
Labels: Bug

#1850 Improved import upload page..
  app/Abstracts/Http/Controller.php
  app/Http/Controllers/Banking/Transactions.php
  app/Http/Controllers/Banking/Transfers.php
  app/Http/Controllers/Common/Items.php
  app/Http/Controllers/Purchases/Bills.php
  app/Http/Controllers/Purchases/Payments.php
  app/Http/Controllers/Purchases/Vendors.php
  app/Http/Controllers/Sales/Customers.php
  app/Http/Controllers/Sales/Invoices.php
  app/Http/Controllers/Sales/Revenues.php
  resources/assets/js/views/common/imports.js
  resources/views/common/import/create.blade.php
  webpack.mix.js
Labels: Enhancement

#1852 key variable must be considered if it is defined in search string
  app/View/Components/SearchString.php
Labels: Enhancement

#1853 prefix definition is fixed by converting the use of slug to kebab
  app/View/Components/SearchString.php
Labels: Bug

#1851 Added import/export, bulk action export feature test
  tests/Feature/Common/ItemsTest.php
  tests/Feature/Purchases/BillsTest.php
  tests/Feature/Purchases/PaymentsTest.php
  tests/Feature/Purchases/VendorsTest.php
  tests/Feature/Sales/CustomersTest.php
  tests/Feature/Sales/InvoicesTest.php
  tests/Feature/Sales/RevenuesTest.php
Labels: Enhancement

#1859 Added import export for categories
  app/Exports/Settings/Categories.php
  app/Http/Controllers/Settings/Categories.php
  app/Imports/Settings/Categories.php
  public/files/import/categories.xlsx
  resources/views/settings/categories/index.blade.php
  routes/admin.php
Labels: Feature

#1867 module prefix should be converted with kebab instead of slug
  app/View/Components/SearchString.php
Labels: Enhancement

#1870 Show a correct text in a delete modal for modules
  app/Abstracts/View/Components/Document.php
  app/Abstracts/View/Components/DocumentIndex.php
  resources/views/components/documents/index/card-body.blade.php
  resources/views/components/documents/index/content.blade.php
Labels: Enhancement

#1875 akaunting select dynamicOptions update
  resources/assets/js/components/AkauntingSelect.vue
  resources/assets/js/components/AkauntingSelectRemote.vue
Labels: Enhancement

#1876 Fix tooltip issue for "Send Email" button
  resources/views/components/documents/show/timeline.blade.php
  resources/views/components/documents/show/top-buttons.blade.php
Labels: Bug

#1879 invoice or bill date filter is fixed
  config/search-string.php
Labels: Enhancement

#1882 fixing typo and bug when group is true
  resources/assets/js/components/AkauntingSelect.vue
  resources/assets/js/components/AkauntingSelectRemote.vue
Labels: Enhancement

#1883 Make dynamic invoice settings for documents
  app/Abstracts/View/Components/DocumentForm.php
  app/Abstracts/View/Components/DocumentShow.php
  app/Abstracts/View/Components/DocumentTemplate.php
  app/Http/Controllers/Modals/DocumentItemColumns.php
  app/Traits/Documents.php
  config/type.php
  resources/views/components/documents/form/company.blade.php
  resources/views/components/documents/form/content.blade.php
  resources/views/components/documents/form/footer.blade.php
  resources/views/components/documents/form/main.blade.php
  resources/views/components/documents/form/note.blade.php
  resources/views/modals/documents/item_columns.blade.php
Labels: Enhancement

#1886 date filter will work based on company format and the selection of da…
  app/View/Components/SearchString.php
  resources/assets/js/components/AkauntingSearch.vue
  resources/views/components/search-string.blade.php
Labels: Enhancement

#1821 Format in the datepicker
  app/Utilities/helpers.php
  resources/assets/js/components/AkauntingDate.vue
  resources/views/banking/reconciliations/create.blade.php
  resources/views/banking/transfers/create.blade.php
  resources/views/banking/transfers/edit.blade.php
  resources/views/components/documents/form/metadata.blade.php
  resources/views/components/search-string.blade.php
  resources/views/partials/form/date_group.blade.php
  resources/views/partials/form/date_time_group.blade.php
  resources/views/purchases/payments/create.blade.php
  resources/views/purchases/payments/edit.blade.php
  resources/views/sales/revenues/create.blade.php
  resources/views/sales/revenues/edit.blade.php
Labels: Enhancement

#1888 unnecessary code removed
  app/View/Components/SearchString.php
Labels: Enhancement

#1889 it should parse date-related parameters
  app/Traits/SearchString.php
Labels: Enhancement

#1891 values of selected filters are arranged #1869
  resources/assets/js/components/AkauntingSearch.vue
Labels: Enhancement
