Repository akaunting/akaunting, pull requests merged in 2021-01, with the labels that each got.

#1711 Fix some usages of translation strings.
  app/Http/Controllers/Purchases/Bills.php
  app/Http/Controllers/Sales/Invoices.php
  app/Listeners/Document/MarkDocumentCancelled.php
  app/Listeners/Document/MarkDocumentReceived.php
  app/Listeners/Document/MarkDocumentViewed.php
Labels: Bug

#1710 Leverage translation strings in the bulk actions modal.
  resources/views/partials/form/bulk_action_row_group.blade.php
Labels: Bug

#1722 Fix downloading a bill's PDF file
  app/Abstracts/View/Components/DocumentShow.php
  app/Http/Controllers/Purchases/Bills.php
Labels: Bug

#1723 minor bugs fixed related to the items of documents
  resources/assets/js/views/common/documents.js
  resources/views/components/documents/form/line-item.blade.php
Labels: Bug

#1724 Refactoring total and line discount calculation according to new design
  resources/assets/js/views/common/documents.js
  resources/views/components/documents/form/items.blade.php
  resources/views/components/documents/form/line-item.blade.php
  resources/views/components/documents/form/totals.blade.php
Labels: Enhancement

#1726 entries of items will be reflected automatically to the entries of fo…
  resources/assets/js/views/common/documents.js
Labels: Enhancement

#1728 minor changes made on akaunting-date component and used partials
  resources/assets/js/components/AkauntingDate.vue
  resources/views/partials/form/date_group.blade.php
  resources/views/partials/form/date_time_group.blade.php
  resources/views/partials/form/time_group.blade.php
Labels: Enhancement

#1732 Add Document/Transaction/Contact types to the config
  app/Abstracts/View/Components/DocumentForm.php
  app/Abstracts/View/Components/DocumentIndex.php
  app/Abstracts/View/Components/DocumentShow.php
  app/Events/Auth/ApiPermissionsAssigning.php
  app/Http/Requests/Document/Document.php
  app/Listeners/Auth/SetPermissionControllerForApi.php
  app/Listeners/Document/MarkDocumentCancelled.php
  app/Listeners/Document/MarkDocumentReceived.php
  app/Listeners/Document/MarkDocumentSent.php
  app/Listeners/Document/MarkDocumentViewed.php
  app/Providers/Event.php
  app/Traits/Permissions.php
  app/View/Components/Documents/Form/Company.php
  config/type.php
Labels: Enhancement

#1736 checkbox group is adjusted
  resources/assets/js/views/common/documents.js
  resources/views/partials/form/checkbox_group.blade.php
Labels: Enhancement

#1737 Add Livewire
  composer.json
  config/livewire.php
  public/vendor/livewire/livewire.js
  public/vendor/livewire/livewire.js.map
  public/vendor/livewire/manifest.json
  resources/views/partials/admin/head.blade.php
  resources/views/partials/admin/scripts.blade.php
Labels: Feature

#1739 option_sortable prop is activated for select components
  resources/assets/js/components/AkauntingSelect.vue
  resources/assets/js/components/AkauntingSelectRemote.vue
Labels: Enhancement

#1740 fixing an exception that throws if the value of 'multiple' is true
  resources/assets/js/components/AkauntingSelect.vue
  resources/assets/js/components/AkauntingSelectRemote.vue
Labels: Bug

#1741 naming of variables updated and redundancy created by use of the comp…
  resources/assets/js/components/AkauntingSelect.vue
  resources/assets/js/components/AkauntingSelectRemote.vue
Labels: Bug

#1743 Remove nullable property from due_at column
  database/migrations/2020_10_13_000000_core_v210.php
Labels: Bug

#1746 invoiced_at_input_* => issued_at_input_*
  resources/views/components/documents/template/classic.blade.php
  resources/views/components/documents/template/default.blade.php
  resources/views/components/documents/template/modern.blade.php
Labels: Bug

#1742 Add Document/Transaction/Contact types to the config vol 2
  app/Abstracts/View/Components/Document.php
  app/Abstracts/View/Components/DocumentForm.php
  app/Abstracts/View/Components/DocumentIndex.php
  app/Abstracts/View/Components/DocumentShow.php
  app/Abstracts/View/Components/DocumentTemplate.php
  app/Http/Requests/Document/Document.php
  app/Listeners/Document/MarkDocumentCancelled.php
  app/Listeners/Document/MarkDocumentReceived.php
  app/Listeners/Document/MarkDocumentSent.php
  app/Listeners/Document/MarkDocumentViewed.php
  app/Notifications/Portal/PaymentReceived.php
  app/Traits/Documents.php
  app/Traits/Permissions.php
  app/View/Components/Documents/Form/Advanced.php
  app/View/Components/Documents/Form/Company.php
  config/type.php
  resources/lang/en-GB/bills.php
  resources/lang/en-GB/documents.php
  resources/lang/en-GB/invoices.php
  resources/views/components/documents/form/advanced.blade.php
  resources/views/components/documents/form/buttons.blade.php
  resources/views/components/documents/form/content.blade.php
  resources/views/purchases/payments/index.blade.php
  resources/views/purchases/vendors/show.blade.php
  resources/views/sales/customers/show.blade.php
  resources/views/sales/revenues/index.blade.php
Labels: Enhancement, Language Change

#1747 Remove type from company title and subheading
  resources/views/components/documents/form/company.blade.php
Labels: Enhancement

#1748 Fix document item columns
  app/Abstracts/View/Components/DocumentShow.php
  resources/views/components/documents/form/items.blade.php
  resources/views/components/documents/form/line-item.blade.php
  resources/views/components/documents/template/classic.blade.php
  resources/views/components/documents/template/default.blade.php
Labels: Enhancement

#1749 Add request object to DocumentCreated event
  app/BulkActions/Sales/Invoices.php
  app/Console/Commands/RecurringCheck.php
  app/Jobs/Document/DuplicateDocument.php
  app/Listeners/Document/SettingFieldCreated.php
  app/Listeners/Document/SettingFieldUpdated.php
  database/factories/Document.php
  tests/Feature/Sales/InvoicesTest.php
Labels: Enhancement

#1751 Fix showing a correct category in a document.
  resources/views/components/documents/form/advanced.blade.php
Labels: Bug

#1750 Allow to use the script component with modules' custom scripts.
  app/View/Components/Documents/Script.php
  resources/views/components/documents/script.blade.php
Labels: Enhancement

#1754 Add due_at column for modules that don't have the due date field when…
  app/Listeners/Update/V21/Version210.php
Labels: Enhancement

#1755 Fix notification error when creating sample data
  app/Listeners/Document/SendDocumentPaymentNotification.php
  config/type.php
  database/factories/Document.php
Labels: Bug

#1756 Fix not showing bills' transactions
  app/Models/Document/Document.php
Labels: Bug

#1757 Fix the error when exporting documents
  app/Exports/Purchases/Sheets/BillTransactions.php
  app/Exports/Sales/Sheets/InvoiceTransactions.php
Labels: Bug

#1763 Get contact details from request's old input
  app/Abstracts/View/Components/DocumentForm.php
Labels: Feature

#1767 Remove pluck method from update script
  app/Listeners/Update/V21/Version210.php
Labels: Enhancement

#1769 Fix getting a document template for modules.
  app/Abstracts/View/Components/DocumentShow.php
Labels: Bug

#1770 Portal payments store card added
  resources/assets/js/components/CreditCard/CardForm.vue
  resources/assets/js/views/portal/invoices.js
  resources/views/partials/portal/payment_method/hosted.blade.php
Labels: Enhancement

#1772 Add company_id and type index to documents table
  database/migrations/2020_10_13_000000_core_v210.php
Labels: Enhancement

#1773 card component select card future
  resources/assets/js/components/CreditCard/CardForm.vue
  resources/assets/js/views/portal/invoices.js
  resources/views/partials/portal/payment_method/hosted.blade.php
  resources/views/portal/invoices/signed.blade.php
Labels: Feature

#1771 component dropzone related works
  resources/assets/js/components/Inputs/DropzoneFileUpload.vue
  resources/views/auth/users/create.blade.php
  resources/views/auth/users/edit.blade.php
  resources/views/common/companies/create.blade.php
  resources/views/common/companies/edit.blade.php
  resources/views/common/items/create.blade.php
  resources/views/common/items/edit.blade.php
  resources/views/components/documents/form/company.blade.php
  resources/views/partials/form/file_group.blade.php
  resources/views/portal/profile/edit.blade.php
  resources/views/purchases/vendors/create.blade.php
  resources/views/purchases/vendors/edit.blade.php
  resources/views/settings/company/edit.blade.php
  resources/views/wizard/companies/edit.blade.php
Labels: Enhancement

#1778 akaunting dropzone related works
  resources/assets/js/components/AkauntingDropzoneFileUpload.vue
  resources/views/partials/form/file_group.blade.php
Labels: Enhancement

#1780 portal payment method issues
  modules/OfflinePayments/Http/Controllers/Payment.php
  modules/OfflinePayments/Resources/views/show.blade.php
  modules/OfflinePayments/Resources/views/signed.blade.php
  resources/assets/js/views/portal/invoices.js
Labels: Bug

#1781 Put JS dependencies in order.
  package.json
Labels: Enhancement

#1788 portal payment card issues
  resources/assets/js/components/CreditCard/CardForm.vue
  resources/lang/en-GB/general.php
  resources/views/partials/portal/payment_method/hosted.blade.php
Labels: Enhancement

#1792 maxFiles have to be given to akaunting dropzone component
  resources/views/partials/form/file_group.blade.php
Labels: Enhancement

#1793 fixed App\Notifications\Sale\Invoice getTagsReplacement() - updated f…
  app/Notifications/Sale/Invoice.php
Labels: Bug

#1799 Add polymorphic relation update to migration script
  app/Listeners/Update/V21/Version210.php
Labels: Enhancement

#1800 Allow to use custom warning about existing relations in modules.
  app/Traits/Relationships.php
Labels: Enhancement

#1801 Fix migration issue
  app/Listeners/Update/V21/Version210.php
Labels: Bug

#1803 Fix 'table not found' error in migration
  app/Listeners/Update/V21/Version210.php
Labels: Enhancement

#1809 Missing column formatting for exports
  app/Exports/Purchases/Sheets/Bills.php
  app/Exports/Sales/Sheets/Invoices.php
Labels: Bug

#1810 minor bug fixed on AkauntingSelect.vue
  resources/assets/js/components/AkauntingSelect.vue
Labels: Bug

#1811 onCalculateTotal should be called with timeout
  resources/assets/js/views/common/documents.js
Labels: Enhancement

#1812 Fixed document_item_id required error when importing
  app/Imports/Purchases/Sheets/BillItemTaxes.php
  app/Imports/Sales/Sheets/InvoiceItemTaxes.php
Labels: Bug

#1813 Add try-catch to show the formatting error to the user
  app/Abstracts/Import.php
Labels: Bug

#1814 Do not include jQuery twice.
  resources/assets/js/bootstrap.js
Labels: Bug

#1815 options prop is converted to configurations data variable and maxFile…
  resources/assets/js/components/AkauntingDropzoneFileUpload.vue
Labels: Bug

#1816 acceptedFiles parameter is removed due to default value is defined fo…
  resources/assets/js/components/AkauntingDropzoneFileUpload.vue
  resources/views/auth/users/create.blade.php
  resources/views/auth/users/edit.blade.php
  resources/views/common/companies/create.blade.php
  resources/views/common/companies/edit.blade.php
  resources/views/common/items/create.blade.php
  resources/views/common/items/edit.blade.php
  resources/views/components/documents/form/advanced.blade.php
  resources/views/components/documents/form/company.blade.php
  resources/views/portal/profile/edit.blade.php
  resources/views/purchases/vendors/create.blade.php
  resources/views/purchases/vendors/edit.blade.php
  resources/views/settings/company/edit.blade.php
  resources/views/wizard/companies/edit.blade.php
Labels: Enhancement

#1817 preview option is added to dropzone
  resources/assets/js/components/AkauntingDropzoneFileUpload.vue
  resources/views/partials/form/file_group.blade.php
Labels: Enhancement

#1818 Added API for dashboards
  app/Abstracts/Http/Controller.php
  app/Abstracts/Widget.php
  app/Http/Controllers/Api/Common/Dashboards.php
  app/Http/Controllers/Api/Common/Items.php
  app/Transformers/Common/Dashboard.php
  app/Transformers/Common/Widget.php
  routes/api.php
Labels: Feature

#1819 dropzone component is arranged
  app/Models/Document/Document.php
  resources/assets/js/components/AkauntingDropzoneFileUpload.vue
  resources/views/common/companies/edit.blade.php
  resources/views/common/items/edit.blade.php
  resources/views/partials/form/file_group.blade.php
Labels: Enhancement

#1645 Edit offline payment method issue
  modules/OfflinePayments/Http/Controllers/Settings.php
Labels: Bug
