Repository akaunting/akaunting, pull requests merged in 2021-08, with the labels that each got.

#2218 Account show page
  app/Http/Controllers/Banking/Accounts.php
  app/Http/Livewire/Common/Search.php
  app/Listeners/Report/AddSearchString.php
  app/Models/Banking/Account.php
  public/vendor/livewire/livewire.js
  public/vendor/livewire/livewire.js.map
  public/vendor/livewire/manifest.json
  resources/assets/js/views/banking/accounts.js
  resources/lang/en-GB/accounts.php
  resources/lang/en-GB/general.php
  resources/views/banking/accounts/index.blade.php
  resources/views/banking/accounts/show.blade.php
  resources/views/partials/reports/filter.blade.php
  routes/admin.php
Labels: Feature, Language Change

#2223 Adding discount as an amount
  app/Jobs/Document/CreateDocumentItem.php
  app/Jobs/Document/CreateDocumentItemsAndTotals.php
  resources/assets/js/views/common/documents.js
  resources/views/components/documents/form/line-item.blade.php
  resources/views/components/documents/form/totals.blade.php
  resources/views/components/documents/template/line-item.blade.php
Labels: Feature

#2226 Revenue/Payment js file enhancement and fixed show page delete button.
  resources/assets/js/views/banking/transactions.js
  resources/assets/js/views/purchases/payments.js
  resources/assets/js/views/sales/revenues.js
  resources/views/purchases/payments/create.blade.php
  resources/views/purchases/payments/edit.blade.php
  resources/views/purchases/payments/index.blade.php
  resources/views/sales/revenues/create.blade.php
  resources/views/sales/revenues/edit.blade.php
  resources/views/sales/revenues/index.blade.php
  webpack.mix.js
Labels: Bug, Enhancement

#2227 Transaction not edit, duplicate, delete etc button for Transferred
  app/Models/Banking/Transaction.php
  resources/views/components/transactions/show/top-buttons.blade.php
Labels: Bug

#2228 Transfer added created by and show page account link
  app/Abstracts/View/Components/TransferShow.php
  app/Jobs/Banking/CreateTransfer.php
  resources/views/components/transfers/show/content.blade.php
  resources/views/components/transfers/show/header.blade.php
Labels: Enhancement

#2229 Seletbox add clear button
  resources/assets/js/components/AkauntingSelect.vue
  resources/assets/js/components/AkauntingSelectRemote.vue
  resources/views/partials/form/multi_select_add_new_group.blade.php
  resources/views/partials/form/multi_select_group.blade.php
  resources/views/partials/form/multi_select_remote_add_new_group.blade.php
  resources/views/partials/form/multi_select_remote_group.blade.php
  resources/views/partials/form/select_add_new_group.blade.php
  resources/views/partials/form/select_group.blade.php
  resources/views/partials/form/select_group_add_new_group.blade.php
  resources/views/partials/form/select_group_group.blade.php
  resources/views/partials/form/select_remote_add_new_group.blade.php
  resources/views/partials/form/select_remote_group.blade.php
Labels: Enhancement

#2230 Fixed account show page opening_balance currency
  resources/views/banking/accounts/show.blade.php
Labels: Bug

#2232 attributes parameter added to form provider
  app/Providers/Form.php
Labels: Bug

#2233 reconciled attribute should be seperated from paid
  app/Models/Document/Document.php
Labels: Bug
