Repository akaunting/akaunting, pull requests merged in 2021-03, with the labels that each got.

#1894 Error on reports when recurring the invoice
  app/Utilities/Recurring.php
Labels: Bug

#1927 Send notification on update failure
  app/Console/Commands/Update.php
  app/Events/Install/UpdateFailed.php
  app/Listeners/Update/SendNotificationOnFailure.php
  app/Notifications/Install/UpdateFailed.php
  app/Providers/Event.php
  composer.json
  composer.lock
  config/update.php
  resources/lang/en-GB/notifications.php
Labels: Feature

#1933 install page email validation has been fixed
  app/Http/Controllers/Install/Settings.php
  app/Http/Requests/Install/Setting.php
Labels: Enhancement

#1936 Overwrite button styles for ColorPicker element
  public/css/custom.css
Labels: Enhancement

#1938 account filter on transfers solved
  config/search-string.php
Labels: Bug

#1940 id column is added to config of search strings
  config/search-string.php
Labels: Enhancement

#1942 Currencies widget added
  app/Utilities/Widgets.php
  app/Widgets/Currencies.php
  database/seeds/Permissions.php
  resources/lang/en-GB/widgets.php
  resources/views/widgets/currencies.blade.php
Labels: Feature

#1945 show attribute added to number group partial
  resources/views/partials/form/number_group.blade.php
Labels: Enhancement

#1946 Add "From/To Account Rate" fields in transfer create/edit page
  app/Http/Controllers/Banking/Transfers.php
  app/Jobs/Banking/CreateTransfer.php
  app/Jobs/Banking/UpdateTransfer.php
  resources/assets/js/views/banking/transfers.js
  resources/lang/en-GB/transfers.php
  resources/views/banking/transfers/create.blade.php
  resources/views/banking/transfers/edit.blade.php
Labels: Feature

#1947 Change company relationships to documents on deletion
  app/Jobs/Common/DeleteCompany.php
Labels: Enhancement

#1954 show attribute added to form partials
  resources/views/partials/form/checkbox_group.blade.php
  resources/views/partials/form/email_group.blade.php
  resources/views/partials/form/file_group.blade.php
  resources/views/partials/form/invoice_text.blade.php
  resources/views/partials/form/password_group.blade.php
  resources/views/partials/form/radio_group.blade.php
  resources/views/partials/form/text_editor_group.blade.php
  resources/views/partials/form/text_group.blade.php
  resources/views/partials/form/textarea_group.blade.php
Labels: Enhancement

#1959 Delete dashboard/report after module uninstall
  app/Http/Controllers/Common/Dashboards.php
  app/Http/Controllers/Common/Widgets.php
  app/Jobs/Common/CreateDashboard.php
  app/Listeners/Module/FinishUninstallation.php
  app/Models/Common/Dashboard.php
  app/Models/Common/Report.php
  app/Providers/Event.php
  app/Traits/Users.php
  app/Utilities/Widgets.php
  database/seeds/Dashboards.php
Labels: Enhancement
