Repository akaunting/akaunting, pull requests merged in 2022-10, with the labels that each got.

#2647 No record text controlled for reviews
  resources/views/components/layouts/modules/show/reviews.blade.php
Labels: Bug

#2649 Template customization change
  resources/views/components/documents/show/template.blade.php
  resources/views/components/transactions/show/template.blade.php
Labels: Enhancement

#2650 Tailwind safelist configuration
  presets.js
  public/css/app.css
  safelist.txt
Labels: Enhancement, Code Style

#2653 Report print.css updated
  public/css/print.css
  resources/views/components/reports/detail/table.blade.php
Labels: Enhancement

#2656 Value checked on dynamic options for Select components
  resources/assets/js/components/AkauntingSelect.vue
  resources/assets/js/components/AkauntingSelectRemote.vue
  resources/views/components/form/group/select.blade.php
Labels: Bug, Enhancement

#2661 Frontend developments
  public/css/app.css
  resources/assets/js/plugins/form.js
  resources/views/components/dropdown/index.blade.php
  safelist.txt
Labels: Bug, Code Style

#2663 Modal widths updated (#3nnbz9w)
  resources/assets/js/components/AkauntingModal.vue
  resources/assets/js/components/AkauntingModalAddNew.vue
  resources/assets/js/views/banking/transactions.js
  resources/assets/js/views/common/documents.js
  resources/views/modals/companies/edit.blade.php
Labels: Enhancement

#2641 Show correct date for sent recurring invoices
  resources/views/components/documents/show/children.blade.php
Labels: Bug

#2665 Responsive control
  public/css/app.css
  resources/assets/sass/app.css
  resources/views/components/documents/form/items.blade.php
  resources/views/components/documents/form/line-item.blade.php
  resources/views/widgets/cash_flow.blade.php
  safelist.txt
Labels: Bug

#2669 Target blank for link
  public/akaunting-js/generalAction.js
  public/css/app.css
Labels: Enhancement

#2674 Some console error fixed
  public/css/app.css
  resources/assets/js/components/AkauntingColor.vue
  resources/assets/js/plugins/form.js
Labels: Bug

#2676 Some console error fixed
  resources/assets/js/components/AkauntingContactCard.vue
  resources/assets/js/components/AkauntingSearch.vue
  resources/assets/js/components/AkauntingSelect.vue
  resources/assets/js/components/AkauntingSelectRemote.vue
  resources/assets/js/mixins/global.js
  resources/views/settings/categories/create.blade.php
Labels: Bug

#2678 When category update is wrong, it gives undefined variable error
  app/Http/Controllers/Settings/Categories.php
Labels: Bug

#2677 Widget chart label integer format added
  app/Traits/Charts.php
Labels: Enhancement

#2681 Some interface problems fixed
  public/css/app.css
  resources/views/components/documents/form/totals.blade.php
  resources/views/modules/item/show.blade.php
  resources/views/widgets/bank_feeds.blade.php
  safelist.txt
Labels: Bug

#2683 Image text truncated for file is corrupt
  resources/views/auth/users/index.blade.php
  resources/views/components/layouts/admin/menu.blade.php
  resources/views/components/layouts/portal/menu.blade.php
Labels: Bug, Enhancement

#2685 Select component when the option is cleared, trigger the event issue
  resources/views/components/form/group/select.blade.php
Labels: Enhancement

#2684 Chart label formatter type updated
  app/Abstracts/Report.php
Labels: Enhancement

#2686 Dashboard responsive control & Parent&Child icon control
  public/css/app.css
  resources/assets/js/components/AkauntingSelectRemote.vue
  resources/assets/js/components/AkauntingWidget.vue
  resources/assets/sass/app.css
Labels: Bug

#2689 Typo for truncate development
  public/akaunting-js/generalAction.js
Labels: Bug

#2690 Autocomplete disabled for form elements
  public/akaunting-js/generalAction.js
Labels: Enhancement

#2691 Autocomplete disabled from laravel components
  public/akaunting-js/generalAction.js
Labels: Enhancement

#2692 Item selected styling on document
  public/css/app.css
  resources/assets/sass/app.css
Labels: Enhancement, Feature

#2694 Icon line fixed for marquee animation
  public/akaunting-js/generalAction.js
Labels: Bug

#2695 Spacing synchronized for Company form on Wizard page
  resources/assets/js/views/wizard/Company.vue
Labels: Bug

#2696 Some responsive bugfix solved
  public/css/app.css
  resources/views/components/documents/form/line-item.blade.php
  resources/views/modules/item/show.blade.php
  safelist.txt
Labels: Bug

#2697 Width edited for file component on wizard page
  resources/assets/js/views/wizard/Company.vue
Labels: Bug

#2699 Validation control for multi select
  public/css/app.css
  resources/assets/sass/app.css
Labels: Bug

#2700 Start&End date color edited for datepicker
  public/css/app.css
  resources/assets/sass/app.css
Labels: Bug

#2701 Newly added item appear
  resources/assets/js/components/AkauntingContactCard.vue
Labels: Bug

#2703 Added prevent.default() for Install form
  resources/assets/js/views/install/Database.vue
  resources/assets/js/views/install/Language.vue
  resources/assets/js/views/install/Settings.vue
Labels: Bug

#2704 Overflow disabled for dashboard on responsive
  resources/views/widgets/cash_flow.blade.php
Labels: Bug

#2698 Tailwind upgraded to 3.2.1 version
  app/View/Components/Table/Tr.php
  app/View/Presenters/Menu.php
  package.json
  presets.js
  public/css/app.css
  resources/assets/js/views/wizard/Currencies.vue
  resources/assets/sass/app.css
  resources/views/components/delete-button.blade.php
  resources/views/components/documents/index/information.blade.php
  resources/views/components/layouts/admin/menu.blade.php
  resources/views/components/layouts/portal/menu.blade.php
  resources/views/components/table/actions.blade.php
  resources/views/components/tooltip.blade.php
  resources/views/livewire/report/pin.blade.php
  resources/views/settings/categories/index.blade.php
Labels: Enhancement, Code Style, Feature
