Repository akaunting/akaunting, pull requests merged in 2022-06, with the labels that each got.

#2402 typo fixed
  app/Models/Banking/Transaction.php
Labels: Code Style

#2403 Ui improvements
  public/css/app.css
  public/css/print.css
  resources/assets/js/components/AkauntingConnectTransactions.vue
  resources/views/auth/login/create.blade.php
  resources/views/auth/register/create.blade.php
  resources/views/components/layouts/modules/item.blade.php
  resources/views/components/modules/item.blade.php
Labels: Enhancement

#2414 Selected bugfix solved for Single File in Import Page
  public/css/app.css
  resources/assets/js/components/AkauntingDropzoneFileUpload.vue
  resources/views/auth/users/create.blade.php
  resources/views/auth/users/edit.blade.php
Labels: Bug

#2416 job used for creating user
  app/Jobs/Common/UpdateContact.php
Labels: Bug

#2425 show selected category on category component
  app/View/Components/Form/Group/Category.php
Labels: Bug

#2427 Currency symbol added to account name
  app/Models/Banking/Account.php
  app/View/Components/Form/Group/Account.php
Labels: Enhancement

#2435 Ui feedbacks & bugfixes solved
  public/akaunting-js/generalAction.js
  resources/assets/js/components/AkauntingSearch.vue
  resources/assets/js/mixins/wizardAction.js
  resources/assets/js/views/wizard/Company.vue
  resources/assets/js/views/wizard/Currencies.vue
  resources/assets/js/views/wizard/Taxes.vue
  resources/views/common/items/index.blade.php
  resources/views/components/documents/index/information.blade.php
Labels: Bug, Enhancement

#2444 Widget model alias scope added
  app/Models/Common/Widget.php
Labels: Enhancement

#2448 Select placeholder made dynamic
  app/Abstracts/View/Components/Form.php
  resources/views/components/form/group/select.blade.php
  resources/views/components/form/input/select.blade.php
Labels: Enhancement

#2449 translation duplicated
  resources/lang/en-GB/general.php
Labels: Code Style

#2454 Print css prefix
  public/css/print.css
  resources/views/components/documents/show/template.blade.php
  resources/views/components/documents/template/classic.blade.php
  resources/views/components/documents/template/default.blade.php
  resources/views/components/documents/template/modern.blade.php
  resources/views/components/transactions/show/template.blade.php
  resources/views/components/transactions/template/default.blade.php
  resources/views/components/transfers/show/content.blade.php
  resources/views/components/transfers/template/default.blade.php
  resources/views/components/transfers/template/second.blade.php
  resources/views/components/transfers/template/third.blade.php
Labels: Bug, Code Style

#2459 type check for route parameter
  app/View/Components/DeleteButton.php
Labels: Enhancement

#2462 Remove classname action for modals
  resources/assets/js/components/AkauntingCompanyEdit.vue
  resources/assets/js/components/AkauntingContactCard.vue
  resources/assets/js/components/AkauntingEditItemColumns.vue
  resources/assets/js/components/AkauntingItemButton.vue
  resources/assets/js/components/AkauntingSelect.vue
  resources/assets/js/components/AkauntingSelectRemote.vue
  resources/assets/js/components/AkauntingWidget.vue
  resources/assets/js/components/Modal.vue
  resources/assets/js/mixins/global.js
  resources/assets/js/views/banking/transactions.js
  resources/assets/js/views/common/documents.js
Labels: Bug

#2465 Styling development for more actions in Dashboard & Report
  public/css/app.css
  resources/views/common/dashboards/show.blade.php
  resources/views/common/reports/index.blade.php
  resources/views/components/widgets/header.blade.php
  resources/views/livewire/menu/favorite.blade.php
  resources/views/livewire/menu/favorites.blade.php
  resources/views/livewire/report/pin.blade.php
Labels: Enhancement

#2466 Button animation when form posting moved global folder
  app/View/Components/Button.php
  resources/views/auth/forgot/create.blade.php
  resources/views/auth/login/create.blade.php
  resources/views/auth/reset/create.blade.php
  resources/views/banking/reconciliations/create.blade.php
  resources/views/banking/reconciliations/edit.blade.php
  resources/views/banking/transfers/show.blade.php
  resources/views/common/import/create.blade.php
  resources/views/components/button/index.blade.php
  resources/views/components/button/loading.blade.php
  resources/views/components/form/buttons.blade.php
  resources/views/components/layouts/modules/show/releases.blade.php
  resources/views/components/layouts/modules/show/reviews.blade.php
  resources/views/components/modules/items.blade.php
Labels: Enhancement

#2470 Report view edited for summary print
  public/css/print.css
  resources/views/components/reports/summary.blade.php
  resources/views/components/reports/summary/table/body.blade.php
  resources/views/components/reports/summary/table/row.blade.php
Labels: Enhancement

#2474 Item name initinals added
  app/Models/Common/Item.php
Labels: Enhancement

#2475 Search string edited & added notes for menu scripts
  resources/assets/js/components/AkauntingSearch.vue
  resources/lang/en-GB/general.php
  resources/views/components/documents/form/items.blade.php
  resources/views/components/layouts/admin/scripts.blade.php
  resources/views/components/layouts/portal/scripts.blade.php
  resources/views/components/search-string.blade.php
Labels: Enhancement

#2484 Hidden side bar scenario
  resources/views/components/layouts/admin/scripts.blade.php
  resources/views/components/layouts/portal/scripts.blade.php
Labels: Bug

#2487 The click link then active loading and disabled feature
  public/akaunting-js/generalAction.js
  public/css/app.css
  resources/assets/sass/app.css
  resources/views/components/layouts/modules.blade.php
  resources/views/components/layouts/modules/show/buttons.blade.php
  resources/views/components/link/loading.blade.php
Labels: Enhancement

#2486 Hover animation development
  app/View/Components/Link/Hover.php
  presets.js
  public/css/app.css
  resources/assets/js/components/AkauntingContactCard.vue
  resources/assets/js/views/wizard/Currencies.vue
  resources/assets/sass/app.css
  resources/lang/en-GB/general.php
  resources/views/common/dashboards/show.blade.php
  resources/views/common/reports/index.blade.php
  resources/views/components/documents/form/line-item.blade.php
  resources/views/components/documents/form/totals.blade.php
  resources/views/components/documents/show/get-paid.blade.php
  resources/views/components/documents/show/make-payment.blade.php
  resources/views/components/index/bulkaction/index.blade.php
  resources/views/components/layouts/admin/menu.blade.php
  resources/views/components/layouts/modules/bar.blade.php
  resources/views/components/layouts/portal/menu.blade.php
  resources/views/components/link/hover.blade.php
  resources/views/components/modules/items.blade.php
  resources/views/components/show/accordion/head.blade.php
  resources/views/components/show/no-records.blade.php
  resources/views/components/tips/fixed.blade.php
  resources/views/components/tips/relative.blade.php
  resources/views/components/transactions/show/attachment.blade.php
  resources/views/components/transactions/show/children.blade.php
  resources/views/components/transactions/show/create.blade.php
  resources/views/components/transactions/show/schedule.blade.php
  resources/views/components/transfers/show/attachment.blade.php
  resources/views/components/transfers/show/create.blade.php
  resources/views/components/widgets/header.blade.php
  resources/views/livewire/report/pins.blade.php
  resources/views/portal/invoices/preview.blade.php
  resources/views/portal/invoices/show.blade.php
  resources/views/portal/invoices/signed.blade.php
  resources/views/portal/payments/preview.blade.php
  resources/views/portal/payments/show.blade.php
  resources/views/portal/payments/signed.blade.php
  resources/views/settings/email-templates/edit.blade.php
  resources/views/widgets/receivables_payables.blade.php
Labels: Enhancement

#2494 bulk actions in the users fixed #33dqhgt
  resources/views/auth/users/index.blade.php
Labels: Bug

#2496 Unused classname ejected
  resources/views/banking/reconciliations/create.blade.php
  resources/views/banking/reconciliations/edit.blade.php
  resources/views/common/import/create.blade.php
  resources/views/components/form/accordion/index.blade.php
  resources/views/components/form/section/index.blade.php
  resources/views/components/show/accordion/index.blade.php
Labels: Enhancement

#2499 Attachments controlled for responsive
  public/css/app.css
  resources/assets/js/components/AkauntingDropzoneFileUpload.vue
  resources/views/components/media/file.blade.php
Labels: Bug

#2501 Company forms
  resources/assets/js/views/common/companies.js
  resources/views/common/companies/create.blade.php
  resources/views/common/companies/edit.blade.php
  resources/views/components/contacts/form/address.blade.php
  resources/views/components/form/group/country.blade.php
  resources/views/modals/customers/create.blade.php
  resources/views/modals/customers/edit.blade.php
  resources/views/modals/vendors/create.blade.php
  resources/views/modals/vendors/edit.blade.php
  resources/views/portal/profile/edit.blade.php
Labels: Enhancement
