Repository akaunting/akaunting, pull requests merged in 2022-08, with the labels that each got.

#2564 Animation added for Title in Modules Banner
  resources/views/components/layouts/modules.blade.php
  resources/views/components/modules/banners.blade.php
Labels: Feature

#2572 Page loading ejected from Vue instance
  resources/assets/js/mixins/global.js
  resources/views/components/loading/absolute.blade.php
  resources/views/components/loading/content.blade.php
  resources/views/components/loading/menu.blade.php
Labels: Bug

#2573 Slider links styling edited for Payment Methods
  resources/views/portal/invoices/preview.blade.php
  resources/views/portal/invoices/show.blade.php
  resources/views/portal/invoices/signed.blade.php
Labels: Bug

#2574 Rtl controlled for document and transaction show
  public/css/print.css
  resources/views/components/form/accordion/head.blade.php
  resources/views/components/form/section/head.blade.php
  resources/views/components/media/file.blade.php
  resources/views/components/show/accordion/head.blade.php
  resources/views/components/show/accordion/index.blade.php
  resources/views/components/transactions/show/attachment.blade.php
  resources/views/components/transactions/show/children.blade.php
  resources/views/components/transactions/show/create.blade.php
  resources/views/components/transactions/show/schedule.blade.php
  resources/views/components/transactions/show/transfer.blade.php
  resources/views/components/transactions/template/default.blade.php
Labels: Bug

#2578 Categories import sample file type field development
  public/files/import/categories.xlsx
Labels: Enhancement

#2579 Search component again edited for RTL view.
  public/css/app.css
  resources/assets/js/components/AkauntingSearch.vue
  resources/views/components/reports/summary/chart.blade.php
Labels: Bug

#2584 Added spacing for invoice columns
  resources/views/settings/invoice/edit.blade.php
Labels: Bug

#2588 Fix: Download file should be possible regardless delete permissions.
  resources/views/components/media/file.blade.php
Labels: Bug

#2591 Button disabled when submit for Wizard Company
  resources/assets/js/views/wizard/Company.vue
Labels: Bug

#2597 Value reduced of z-index for empty page badge
  resources/views/components/empty-page.blade.php
Labels: Bug

#2600 Checkbox Responsive Control
  resources/views/components/form/group/checkbox.blade.php
Labels: Bug

#2598 Frontend Issues
  presets.js
  public/css/app.css
  resources/assets/js/components/AkauntingItemButton.vue
  resources/assets/js/components/AkauntingSwitch.vue
  resources/assets/js/views/wizard/Finish.vue
  resources/assets/sass/app.css
  resources/views/auth/users/edit.blade.php
  resources/views/components/documents/form/line-item.blade.php
  resources/views/components/documents/form/totals.blade.php
  resources/views/components/form/accordion/head.blade.php
  resources/views/components/form/accordion/index.blade.php
  resources/views/components/form/section/head.blade.php
  resources/views/components/show/accordion/head.blade.php
  resources/views/components/transfers/show/attachment.blade.php
  resources/views/components/transfers/show/create.blade.php
  resources/views/components/transfers/show/transactions.blade.php
Labels: Bug, Enhancement

#2602 Long text controlled for Page Title
  resources/views/components/empty-page.blade.php
  resources/views/components/layouts/admin/header.blade.php
  resources/views/components/layouts/preview/header.blade.php
  resources/views/components/layouts/signed/header.blade.php
  resources/views/components/title.blade.php
Labels: Bug, Feature

#2599 Multiple root elements detected error fix.
  resources/views/livewire/menu/favorite.blade.php
Labels: Bug

#2603 Added warning message for exist js file
  resources/lang/en-GB/install.php
  resources/views/components/layouts/install.blade.php
Labels: Bug, Enhancement

#2604 Alignment controlled for dashboard titles
  resources/views/components/widgets/header.blade.php
Labels: Bug

#2605 Disable email input on reset page
  app/Models/Auth/User.php
  app/Notifications/Auth/Reset.php
  resources/views/auth/reset/create.blade.php
  resources/views/components/form/group/email.blade.php
Labels: Enhancement

#2606 Tooltip appear in Dashboard title
  resources/views/components/title.blade.php
Labels: Bug

#2607 Code refactoring for title component
  resources/views/components/title.blade.php
Labels: Code Style

#2608 Delete icon styling control for dropzone component
  public/css/app.css
  public/css/third_party/dropzone_custom.css
Labels: Bug

#2609 Responsive controlled for recurring section
  resources/assets/js/components/AkauntingRecurring.vue
Labels: Bug
