Repository akaunting/akaunting, pull requests merged in 2022-12, with the labels that each got.

#2785 Added spacing for head buttons
  public/css/app.css
  resources/assets/sass/app.css
Labels: Bug

#2789 Added custom style for loading
  resources/views/components/loading/content.blade.php
Labels: Code Style

#2788 Position of stacks in contact show
  resources/views/components/contacts/show/content.blade.php
Labels: Bug

#2787 The flash value appear in the description.
  tests/Feature/FeatureTestCase.php
Labels: Bug

#2792 Right column styling and RTL controlled for Wizard finish step
  public/css/app.css
  resources/assets/js/views/wizard/Finish.vue
Labels: Bug

#2791 Added delete widget to module uninstall listener
  app/Listeners/Module/FinishUninstallation.php
Labels: Enhancement

#2793 Position of stacks in account show
  resources/views/banking/accounts/show.blade.php
Labels: Bug

#2794 Missing stack in transaction template blade
  resources/views/components/transactions/template/default.blade.php
Labels: Bug

#2796 Javascript console errors
  public/css/app.css
  resources/assets/js/views/common/documents.js
  resources/assets/sass/app.css
Labels: Bug

#2798 Javascript console error fixed
  resources/assets/js/components/AkauntingSearch.vue
Labels: Bug

#2800 Loading styling converted to custom css
  public/css/custom_loading.css
  resources/views/components/layouts/admin/head.blade.php
  resources/views/components/layouts/auth/head.blade.php
  resources/views/components/layouts/modules/head.blade.php
  resources/views/components/layouts/portal/head.blade.php
  resources/views/components/layouts/preview/head.blade.php
  resources/views/components/layouts/signed/head.blade.php
  resources/views/components/loading/absolute.blade.php
  resources/views/components/loading/content.blade.php
Labels: Enhancement

#2795 Table line action attribute issue
  app/View/Components/Table/Actions.php
Labels: Enhancement

#2804 Javascript console error fixed
  public/akaunting-js/generalAction.js
Labels: Bug

#2806 Tooltip & Popper console error fixed
  public/akaunting-js/generalAction.js
Labels: Bug

#2807 Unused development ejected for loading component
  resources/views/components/layouts/admin.blade.php
  resources/views/components/layouts/modules.blade.php
Labels: Bug

#2810 Tailwind class name controlled for javascript file
  public/css/app.css
  resources/assets/js/views/settings/settings.js
  resources/assets/sass/app.css
Labels: Code Style

#2811 Javascript console error fixed
  resources/assets/js/views/common/items.js
  resources/views/common/items/create.blade.php
  resources/views/common/items/edit.blade.php
Labels: Bug

#2813 Javascript console error fixed
  public/akaunting-js/generalAction.js
  resources/assets/js/views/common/documents.js
Labels: Bug

#2814 Unused control ejected from Contact Card component
  resources/assets/js/components/AkauntingContactCard.vue
Labels: Bug

#2812 added checkbox group disabled attribute
  resources/views/components/form/group/checkbox.blade.php
Labels: Enhancement

#2816 Shake removed
  public/akaunting-js/generalAction.js
  public/css/app.css
  resources/assets/js/components/AkauntingCompanyEdit.vue
  resources/assets/js/components/AkauntingContactCard.vue
  resources/assets/js/components/AkauntingEditItemColumns.vue
  resources/assets/js/components/AkauntingItemButton.vue
  resources/assets/js/components/AkauntingModal.vue
  resources/assets/js/components/AkauntingModalAddNew.vue
  resources/assets/js/components/AkauntingSelect.vue
  resources/assets/js/components/AkauntingSelectRemote.vue
  resources/assets/js/components/AkauntingWidget.vue
  resources/assets/js/components/Modal.vue
  resources/assets/js/mixins/global.js
  resources/assets/sass/app.css
  resources/views/components/layouts/admin.blade.php
  resources/views/components/layouts/auth.blade.php
  resources/views/components/layouts/error.blade.php
  resources/views/components/layouts/modules.blade.php
  resources/views/components/layouts/portal.blade.php
Labels: Enhancement, Code Style

#2818 Modal refactoring
  resources/assets/js/components/AkauntingModalAddNew.vue
  resources/assets/js/views/common/documents.js
Labels: Enhancement, Code Style

#2819 Condition added into the tax for exception
  resources/assets/js/views/common/documents.js
Labels: Bug

#2820 Unused lines ejected from tailwind.config.js
  presets.js
Labels: Code Style

#2821 Head of table styling for Bill Create/Edit
  resources/views/components/documents/form/items.blade.php
Labels: Bug

#2822 contact user update invite disabled
  resources/assets/js/views/common/contacts.js
  resources/views/components/contacts/form/general.blade.php
Labels: Bug

#2824 Console error fixed
  resources/assets/js/views/common/documents.js
Labels: Bug

#2827 Exception fixed from search
  resources/assets/js/components/AkauntingSearch.vue
Labels: Bug

#2826 Refactoring Tests
  tests/Feature/Banking/TransactionsTest.php
  tests/Feature/Common/ItemsTest.php
  tests/Feature/Purchases/BillsTest.php
  tests/Feature/Purchases/VendorsTest.php
  tests/Feature/Sales/CustomersTest.php
  tests/Feature/Sales/InvoicesTest.php
Labels: Enhancement

#2829 User landing_page field validations
  app/Http/Requests/Auth/User.php
Labels: Bug

#2828 Transfer test refactoring
  database/factories/Transfer.php
  tests/Feature/Banking/TransfersTest.php
Labels: Enhancement

#2830 Company test
  database/factories/Company.php
  tests/Feature/Common/CompaniesTest.php
Labels: Enhancement

#2831 Some frontend improvements
  public/akaunting-js/generalAction.js
  public/css/app.css
  resources/assets/sass/app.css
Labels: Bug

#2832 Added custom css class
  public/css/app.css
  resources/assets/sass/app.css
Labels: Enhancement

#2833 Sub icons controlled for select component
  resources/assets/js/components/AkauntingSelect.vue
  resources/assets/js/components/AkauntingSelectRemote.vue
Labels: Bug

#2836 Scenario of disable sale/purchase price done
  app/Models/Common/Item.php
  app/View/Components/Documents/Form/ItemButton.php
  resources/assets/js/components/AkauntingItemButton.vue
Labels: Bug

#2837 Selected controlled for dynamic select component
  resources/assets/js/components/AkauntingSelect.vue
  resources/assets/js/components/AkauntingSelectRemote.vue
  resources/views/components/layouts/modules.blade.php
  resources/views/modules/item/show.blade.php
Labels: Bug

#2838 Sort error fixed from widget component.
  resources/assets/js/components/AkauntingWidget.vue
Labels: Bug

#2839 Updates trait
  app/Traits/Updates.php
Labels: Enhancement

#2840 add zero payment
  app/Http/Requests/Banking/Transaction.php
Labels: Bug

#2841 Collect function in models
  app/Abstracts/Model.php
  app/Models/Auth/User.php
Labels: Enhancement

#2842 Javascript console error fixed
  resources/assets/js/views/common/documents.js
Labels: Bug

#2843 Unworked code ejected from regex
  resources/assets/js/views/common/documents.js
Labels: Bug

#2846 419 error controlled
  resources/assets/js/plugins/form.js
Labels: Bug

#2835 Modal component refactored
  resources/assets/js/components/AkauntingModalAddNew.vue
  resources/assets/js/mixins/global.js
  resources/assets/js/views/settings/settings.js
Labels: Code Style

#2847 Condition added for number replace
  resources/assets/js/views/common/documents.js
Labels: Bug

#2848 Error request controlled
  resources/assets/js/plugins/form.js
Labels: Bug

#2849 Sortable development for items in Document pages
  package-lock.json
  package.json
  resources/assets/js/views/common/documents.js
  resources/views/components/documents/form/line-item.blade.php
Labels: Enhancement

#2845 Add payment button disabled control
  app/Models/Document/Document.php
  resources/views/components/documents/show/get-paid.blade.php
  resources/views/components/documents/show/make-payment.blade.php
Labels: Enhancement

#2852 Inventory stock action
  config/type.php
Labels: Enhancement

#2851 Category search title
  app/Models/Setting/Category.php
Labels: Enhancement

#2853 Removed Document cancel button checking
  app/Abstracts/View/Components/Documents/Show.php
  resources/views/components/documents/show/more-buttons.blade.php
Labels: Code Style

#2854 Landing page not found issue
  app/Traits/Users.php
Labels: Bug

#2855 Frontend improvements
  public/css/app.css
  resources/assets/js/components/AkauntingSwitch.vue
  resources/views/components/form/group/switch.blade.php
  resources/views/modules/item/show.blade.php
Labels: Bug, Code Style
