Repository akaunting/akaunting, pull requests merged in 2022-09, with the labels that each got.

#2614 Modal size updated
  resources/assets/js/mixins/global.js
Labels: Enhancement

#2618 Component For Js Variable Assignment In Blade
  app/View/Components/Script/Declaration.php
  resources/views/components/script/declaration.blade.php
Labels: Feature

#2620 Styling development
  app/View/Components/Documents/Index/Information.php
  resources/views/auth/users/index.blade.php
  resources/views/banking/accounts/index.blade.php
  resources/views/common/companies/index.blade.php
  resources/views/common/import/create.blade.php
  resources/views/components/contacts/index/content.blade.php
  resources/views/components/contacts/show/content.blade.php
  resources/views/components/documents/index/information.blade.php
  resources/views/components/documents/index/recurring_templates.blade.php
  resources/views/modals/invoices/share.blade.php
Labels: Bug, Enhancement

#2622 RTL controlled for toggle component & print template
  public/css/app.css
  public/css/print.css
  resources/assets/sass/app.css
  resources/views/components/documents/template/default.blade.php
  resources/views/components/documents/template/modern.blade.php
  resources/views/components/form/group/toggle.blade.php
Labels: Bug

#2625 Import slider.css for payment methods slider in Portal
  resources/views/components/layouts/portal/head.blade.php
  resources/views/components/layouts/signed/head.blade.php
  resources/views/portal/invoices/show.blade.php
Labels: Bug

#2630 Bulk actions minor issues
  app/Abstracts/BulkAction.php
  resources/assets/js/plugins/bulk-action.js
Labels: Bug

#2632 Added pointer-event-none for when anchor link trigger
  app/View/Presenters/Menu.php
  resources/views/banking/accounts/show.blade.php
  resources/views/banking/transactions/index.blade.php
  resources/views/banking/transfers/index.blade.php
  resources/views/common/dashboards/show.blade.php
  resources/views/common/items/index.blade.php
  resources/views/common/reports/index.blade.php
  resources/views/components/contacts/index/more-buttons.blade.php
  resources/views/components/contacts/show/more-buttons.blade.php
  resources/views/components/delete-button.blade.php
  resources/views/components/documents/index/more-buttons.blade.php
  resources/views/components/documents/show/more-buttons.blade.php
  resources/views/components/layouts/admin/menu.blade.php
  resources/views/components/layouts/portal/menu.blade.php
  resources/views/components/table/actions.blade.php
  resources/views/components/transactions/show/more-buttons.blade.php
  resources/views/components/transfers/show/more-buttons.blade.php
  resources/views/components/widgets/header.blade.php
  resources/views/settings/categories/index.blade.php
  resources/views/settings/taxes/index.blade.php
Labels: Enhancement

#2633 Dropdown text html structure changed
  resources/assets/js/components/AkauntingContactCard.vue
  resources/assets/js/views/wizard/Currencies.vue
  resources/assets/js/views/wizard/Taxes.vue
  resources/views/common/dashboards/show.blade.php
  resources/views/components/delete-link.blade.php
  resources/views/components/dropdown/button.blade.php
  resources/views/components/dropdown/link.blade.php
  resources/views/components/table/actions.blade.php
  resources/views/components/transactions/show/more-buttons.blade.php
  resources/views/components/transfers/show/more-buttons.blade.php
  resources/views/components/widgets/header.blade.php
Labels: Enhancement

#2634 v-model refactoring for mobile phones on vue
  resources/assets/js/components/AkauntingContactCard.vue
  resources/assets/js/components/AkauntingDocumentButton.vue
  resources/assets/js/components/AkauntingItemButton.vue
Labels: Bug

#2638 Credit card icons added into the Card Component
  public/img/credit_card/amex.png
  public/img/credit_card/chip.png
  public/img/credit_card/dinersclub.png
  public/img/credit_card/discover.png
  public/img/credit_card/jcb.png
  public/img/credit_card/mastercard.png
  public/img/credit_card/troy.png
  public/img/credit_card/unionpay.png
  public/img/credit_card/visa.png
  resources/assets/js/components/CreditCard/Card.vue
Labels: Bug, Enhancement

#2639 Add item responsive control
  public/css/app.css
  resources/assets/sass/app.css
  resources/views/components/documents/form/items.blade.php
Labels: Bug

#2640 Text size choice added for Title component
  app/View/Components/Title.php
  resources/views/components/title.blade.php
Labels: Enhancement, Code Style

#2643 Added variable in Modal Add New File
  resources/assets/js/components/AkauntingModalAddNew.vue
Labels: Code Style

#2645 Sub category icon is appear on search list
  resources/assets/js/components/AkauntingSearch.vue
Labels: Enhancement
