Repository akaunting/akaunting, pull requests merged in 2022-07, with the labels that each got.

#2498 User works
  app/Events/Auth/InvitationCreated.php
  app/Http/Controllers/Auth/Register.php
  app/Jobs/Auth/CreateInvitation.php
  app/Jobs/Auth/CreateUser.php
  app/Jobs/Auth/DeleteUser.php
  app/Jobs/Auth/UpdateUser.php
  app/Listeners/Auth/DeleteUserInvitation.php
  app/Listeners/Auth/SendUserInvitation.php
  app/Listeners/Update/V30/Version304.php
  app/Models/Auth/User.php
  app/Models/Auth/UserInvitation.php
  app/Providers/Event.php
  app/Traits/Users.php
  database/migrations/2022_06_28_000000_core_v304.php
  resources/views/auth/users/edit.blade.php
  resources/views/auth/users/index.blade.php
  tests/Feature/Auth/UsersTest.php
Labels: Enhancement

#2503 Document payment update issue fixed
  app/Http/Controllers/Modals/DocumentTransactions.php
  app/Jobs/Banking/UpdateBankingDocumentTransaction.php
  resources/assets/js/views/common/documents.js
  resources/views/modals/documents/payment.blade.php
Labels: Bug

#2504 Document show amount due dynamized
  app/View/Components/Documents/Show/GetPaid.php
  app/View/Components/Documents/Show/MakePayment.php
Labels: Bug

#2512 Creating information modal only Firefox users.
  public/akaunting-js/generalAction.js
Labels: Enhancement

#2518 Console errors fixed
  resources/views/components/form/group/checkbox.blade.php
  resources/views/components/form/group/editor.blade.php
  resources/views/components/form/group/email.blade.php
  resources/views/components/form/group/file.blade.php
  resources/views/components/form/group/number.blade.php
  resources/views/components/form/group/password.blade.php
  resources/views/components/form/group/radio.blade.php
  resources/views/components/form/group/text.blade.php
  resources/views/components/form/group/textarea.blade.php
  resources/views/components/form/label.blade.php
Labels: Bug

#2519 Buttons styling in modules page
  resources/views/components/layouts/modules/show/buttons.blade.php
  resources/views/modules/item/show.blade.php
Labels: Bug

#2522 Add new modal min date option
  resources/assets/js/components/AkauntingModalAddNew.vue
Labels: Enhancement

#2528 Transaction send mail improvements
  app/Models/Banking/Transaction.php
  app/Models/Document/Document.php
  resources/assets/js/views/banking/transactions.js
  resources/views/modals/transactions/email.blade.php
Labels: Enhancement

#2531 Invoice import sample file updated
  public/files/import/invoices.xlsx
Labels: Bug

#2536 Preview dialogue styling for Invoices index in Portal
  resources/views/portal/invoices/index.blade.php
Labels: Bug

#2537 Transaction export date format column updated
  app/Exports/Banking/Transactions.php
  app/Exports/Purchases/Sheets/BillTransactions.php
  app/Exports/Sales/Sheets/InvoiceTransactions.php
Labels: Bug

#2540 Create new if import has no currency code
  app/Imports/Banking/Transactions.php
  app/Imports/Banking/Transfers.php
  app/Imports/Purchases/Sheets/BillTransactions.php
  app/Imports/Purchases/Sheets/Bills.php
  app/Imports/Purchases/Vendors.php
  app/Imports/Sales/Customers.php
  app/Imports/Sales/Sheets/InvoiceTransactions.php
  app/Imports/Sales/Sheets/Invoices.php
  app/Traits/Import.php
Labels: Enhancement

#2539 Live search development for Apps search bar
  app/Http/Controllers/Modules/Tiles.php
  resources/assets/js/views/modules/apps.js
  resources/lang/en-GB/modules.php
  resources/views/components/layouts/modules/bar.blade.php
Labels: Feature

#2541 Export pagination issue fix
  resources/views/components/dropdown/link.blade.php
Labels: Bug

#2542 Item billing information checkbox issue fix
  resources/assets/js/views/common/items.js
Labels: Bug

#2546 Omnipay authorize function
  app/Traits/Omnipay.php
Labels: Enhancement

#2547 Add new modal function in Global.js
  resources/assets/js/mixins/global.js
Labels: Enhancement

#2548 Send To Button Controlling
  public/css/app.css
  resources/assets/js/views/common/documents.js
  resources/views/components/documents/form/buttons.blade.php
  resources/views/portal/invoices/preview.blade.php
  resources/views/portal/invoices/signed.blade.php
Labels: Bug

#2551 Console error fixed for Invoice edit columns modal
  resources/assets/js/views/common/documents.js
  resources/views/components/documents/form/buttons.blade.php
  resources/views/components/documents/form/items.blade.php
  resources/views/components/form/group/invoice_text.blade.php
  resources/views/portal/invoices/preview.blade.php
  resources/views/portal/invoices/signed.blade.php
Labels: Bug

#2555 Logout link is wrong for portal
  app/Listeners/Menu/ShowInProfile.php
Labels: Bug

#2556 Hyperlink added for html editor
  resources/assets/js/components/AkauntingHtmlEditor.vue
Labels: Feature

#2557 Html editor link controlled when link update
  public/css/app.css
  public/css/third_party/vue-html-editor_custom.css
  resources/assets/js/components/AkauntingHtmlEditor.vue
Labels: Feature

#2559 On Before unload controlled when press type button
  resources/assets/js/views/common/documents.js
Labels: Bug

#2560 user creating fixed for unit tests
  app/Jobs/Auth/CreateUser.php
Labels: Bug

#2562 tax duplication fixed
  app/Models/Document/DocumentItemTax.php
Labels: Bug

#2565 Loading controlled for show page
  resources/views/components/loading/absolute.blade.php
Labels: Bug
