Repository akaunting/akaunting, pull requests merged in 2022-11, with the labels that each got.

#2711 Export contact test updated
  tests/Feature/Purchases/VendorsTest.php
  tests/Feature/Sales/CustomersTest.php
Labels: Bug

#2713 Modal styling for Change Log Modal
  public/css/app.css
  resources/assets/sass/app.css
  resources/views/install/updates/index.blade.php
Labels: Bug

#2715 Changed slider structure in slider for Portal / Signed / Preview pages.
  public/css/app.css
  resources/assets/js/views/portal/apps.js
  resources/assets/sass/app.css
  resources/views/install/updates/index.blade.php
  resources/views/portal/invoices/preview.blade.php
  resources/views/portal/invoices/show.blade.php
  resources/views/portal/invoices/signed.blade.php
  resources/views/reports/profit_loss/content/header.blade.php
Labels: Bug, Enhancement

#2716 Tailwind 3.2.1 group-hover development ejected
  app/View/Components/Table/Tr.php
  public/css/app.css
  resources/views/components/table/actions.blade.php
Labels: Bug

#2717 Payment method button styling
  resources/views/components/payment_method/redirect.blade.php
Labels: Bug

#2714 Responsive control checked
  presets.js
  public/css/app.css
  public/css/print.css
  resources/assets/js/components/AkauntingModal.vue
  resources/assets/js/components/AkauntingModalAddNew.vue
  resources/assets/js/components/AkauntingRecurring.vue
  resources/assets/js/components/NotificationPlugin/Notification.vue
  resources/assets/sass/app.css
  resources/views/auth/users/index.blade.php
  resources/views/banking/accounts/show.blade.php
  resources/views/banking/reconciliations/create.blade.php
  resources/views/banking/reconciliations/edit.blade.php
  resources/views/components/contacts/show/buttons.blade.php
  resources/views/components/contacts/show/content.blade.php
  resources/views/components/documents/index/information.blade.php
  resources/views/components/documents/template/classic.blade.php
  resources/views/components/empty-page.blade.php
  resources/views/components/form/group/invoice_text.blade.php
  resources/views/components/index/summary.blade.php
  resources/views/components/layouts/admin/footer.blade.php
  resources/views/components/layouts/modules/bar.blade.php
  resources/views/components/layouts/portal/footer.blade.php
  resources/views/components/layouts/preview.blade.php
  resources/views/components/layouts/preview/footer.blade.php
  resources/views/components/layouts/signed/footer.blade.php
  resources/views/components/modules/banners.blade.php
  resources/views/components/reports/detail/table.blade.php
  resources/views/components/show/content/index.blade.php
  resources/views/components/show/content/left.blade.php
  resources/views/components/show/summary/left.blade.php
  resources/views/components/show/summary/right.blade.php
  resources/views/components/tabs/index.blade.php
  resources/views/components/tabs/nav-link.blade.php
  resources/views/components/tabs/nav.blade.php
  resources/views/portal/invoices/signed.blade.php
  resources/views/reports/profit_loss/content/footer.blade.php
  resources/views/reports/tax_summary/content/header.blade.php
  resources/views/settings/invoice/edit.blade.php
  safelist.txt
Labels: Bug, Enhancement

#2720 Hidden class ejected from payment description
  resources/views/components/payment_method/redirect.blade.php
Labels: Bug

#2721 Style on redirect payment page (signed or portal)
  resources/lang/en-GB/portal.php
  resources/views/components/payment_method/redirect.blade.php
Labels: Enhancement

#2722 The names of stacks in blades (document & transaction)
  resources/views/components/documents/template/classic.blade.php
  resources/views/components/documents/template/default.blade.php
  resources/views/components/documents/template/modern.blade.php
  resources/views/components/transactions/template/default.blade.php
Labels: Bug

#2723 Module buttons styling controlled
  public/css/app.css
  resources/assets/sass/app.css
  resources/views/components/layouts/modules/show/buttons.blade.php
  resources/views/components/layouts/modules/show/information.blade.php
  resources/views/modules/item/show.blade.php
Labels: Bug

#2724 The names of stacks in blades (transaction & transfer)
  resources/views/components/transactions/template/default.blade.php
  resources/views/components/transfers/template/default.blade.php
  resources/views/components/transfers/template/second.blade.php
  resources/views/components/transfers/template/third.blade.php
Labels: Enhancement

#2725 Html structure changed for tips
  resources/views/components/tips/fixed.blade.php
  resources/views/components/tips/relative.blade.php
Labels: Bug, Enhancement

#2726 Spacing ejected from tabs in apps show
  resources/views/modules/item/show.blade.php
Labels: Bug

#2730 Empty page button title improvement
  app/View/Components/EmptyPage.php
Labels: Enhancement

#2732 Added new responsive class name for mobile compatibility
  app/View/Components/Form/Group/File.php
  public/css/app.css
  resources/assets/js/components/AkauntingDropzoneFileUpload.vue
  resources/assets/js/views/settings/settings.js
  resources/views/components/form/group/invoice_text.blade.php
  resources/views/components/show/summary/index.blade.php
  resources/views/components/show/summary/left.blade.php
  resources/views/settings/invoice/edit.blade.php
  safelist.txt
Labels: Bug, Enhancement

#2733 Added new styling class name for plans page
  presets.js
  public/css/app.css
  resources/assets/sass/app.css
  safelist.txt
Labels: Enhancement, Feature

#2735 Added missing css class names
  presets.js
  public/css/app.css
Labels: Bug

#2734 Mobile improvements
  public/css/app.css
  resources/assets/sass/app.css
  resources/views/components/show/content/index.blade.php
Labels: Bug

#2737 Added specific class name for mobile preview
  public/css/app.css
  resources/assets/sass/app.css
Labels: Enhancement

#2739 Simple icons styling
  public/css/app.css
  resources/assets/sass/app.css
Labels: Bug

#2740 Icon svg styling for left menu
  public/css/app.css
  resources/assets/sass/app.css
Labels: Bug

#2741 Code refactoring for animate marquee
  public/akaunting-js/generalAction.js
Labels: Bug

#2743 Actions development for mobile
  app/View/Components/DeleteLink.php
  public/akaunting-js/generalAction.js
  public/css/app.css
  resources/views/components/delete-button.blade.php
  resources/views/components/table/actions-mobile.blade.php
  resources/views/components/table/actions.blade.php
  safelist.txt
Labels: Enhancement

#2742 Settings of page header
  public/akaunting-js/generalAction.js
  public/css/app.css
  resources/assets/sass/app.css
  resources/views/components/layouts/admin/header.blade.php
  resources/views/components/layouts/portal/header.blade.php
  resources/views/components/layouts/preview/header.blade.php
  resources/views/components/layouts/signed/header.blade.php
  resources/views/components/suggestions.blade.php
  resources/views/components/title.blade.php
  resources/views/livewire/menu/favorite.blade.php
  safelist.txt
Labels: Bug, Code Style

#2744 Appearance problem for Print Template
  public/css/app.css
  public/css/print.css
  resources/views/components/documents/show/template.blade.php
  resources/views/components/documents/template/classic.blade.php
  resources/views/components/transactions/show/template.blade.php
  resources/views/components/transfers/show/content.blade.php
Labels: Bug

#2745 New badge appear into the tax
  resources/assets/js/components/AkauntingSelect.vue
  resources/assets/js/components/AkauntingSelectRemote.vue
Labels: Bug

#2746 Styling development for attachments
  public/css/app.css
  resources/assets/js/components/AkauntingDropzoneFileUpload.vue
  resources/assets/sass/app.css
  resources/views/components/media/file.blade.php
Labels: Bug

#2747 Payment method problem
  resources/assets/js/views/portal/apps.js
  resources/views/portal/invoices/preview.blade.php
  resources/views/portal/invoices/show.blade.php
  resources/views/portal/invoices/signed.blade.php
Labels: Bug

#2727 Swiper slider added into the tabs.
  resources/assets/js/mixins/global.js
  resources/views/components/contacts/show/content.blade.php
  resources/views/components/tabs/index.blade.php
  resources/views/components/tabs/nav-link.blade.php
  resources/views/components/tabs/nav.blade.php
Labels: Enhancement, Feature

#2748 Front-end developments
  public/akaunting-js/generalAction.js
  public/css/app.css
  resources/assets/sass/app.css
  resources/views/banking/accounts/show.blade.php
  resources/views/components/layouts/admin/header.blade.php
  resources/views/components/layouts/portal/header.blade.php
  resources/views/components/layouts/preview/header.blade.php
  resources/views/components/layouts/signed/header.blade.php
  resources/views/portal/invoices/preview.blade.php
  resources/views/portal/invoices/show.blade.php
  resources/views/portal/invoices/signed.blade.php
Labels: Bug

#2749 Mark new error
  resources/assets/js/components/AkauntingSelect.vue
  resources/assets/js/components/AkauntingSelectRemote.vue
Labels: Bug

#2750 Added responsive class for portal pages
  resources/views/components/layouts/portal/header.blade.php
  resources/views/components/layouts/preview/header.blade.php
  resources/views/components/layouts/signed/header.blade.php
Labels: Bug

#2751 Unnecessary span ejected from banking show
  resources/views/banking/accounts/show.blade.php
Labels: Bug

#2754 Wizard responsive compatibled
  public/css/app.css
  resources/assets/js/views/wizard/Company.vue
  resources/assets/js/views/wizard/Currencies.vue
  resources/assets/js/views/wizard/Finish.vue
  resources/assets/js/views/wizard/Steps.vue
  resources/assets/sass/app.css
  safelist.txt
Labels: Bug

#2757 Props name fixed
  resources/views/components/form/group/recurring.blade.php
Labels: Bug

#2760 Loading converted to alpine.js
  resources/assets/js/components/AkauntingModal.vue
  resources/assets/js/components/AkauntingModalAddNew.vue
  resources/views/components/layouts/admin/menu.blade.php
  resources/views/components/layouts/portal/menu.blade.php
  resources/views/components/loading/absolute.blade.php
  resources/views/components/loading/content.blade.php
  resources/views/components/loading/menu.blade.php
Labels: Bug, Code Style

#2756 Type issue in category import
  app/Imports/Settings/Categories.php
  app/Traits/Import.php
Labels: Bug

#2761 Sentry integration
  app/Exceptions/Trackers/Bugsnag.php
  app/Exceptions/Trackers/Sentry.php
  app/Traits/Trackers.php
  app/View/Components/Script/Exceptions/Trackers.php
  package-lock.json
  package.json
  resources/assets/js/exceptions/trackers/bugsnag.js
  resources/assets/js/exceptions/trackers/sentry.js
  resources/assets/js/mixins/global.js
  resources/views/components/layouts/admin/head.blade.php
  resources/views/components/layouts/modules/head.blade.php
  resources/views/components/layouts/portal/head.blade.php
  resources/views/components/layouts/preview/head.blade.php
  resources/views/components/layouts/signed/head.blade.php
  resources/views/components/layouts/wizard/head.blade.php
  resources/views/components/script/exceptions/trackers.blade.php
Labels: Enhancement

#2763 Suggestion buttons styling
  public/css/app.css
  resources/assets/sass/app.css
  resources/views/components/layouts/admin/header.blade.php
  resources/views/components/layouts/portal/header.blade.php
  resources/views/components/layouts/preview/header.blade.php
  resources/views/components/layouts/signed/header.blade.php
Labels: Bug

#2764 Added white space into the status for Show page
  resources/views/components/show/status.blade.php
Labels: Bug

#2762 Apps update center version update checking downgrade
  app/Http/Controllers/Install/Updates.php
  resources/lang/en-GB/modules.php
Labels: Enhancement

#2765 Console error cleared from payment methods
  public/akaunting-js/generalAction.js
  resources/views/components/form/group/invoice_text.blade.php
  resources/views/components/form/group/select.blade.php
  resources/views/components/form/input/select.blade.php
  resources/views/portal/invoices/preview.blade.php
  resources/views/portal/invoices/show.blade.php
  resources/views/portal/invoices/signed.blade.php
Labels: Bug

#2766 Fixed javascript console error
  public/akaunting-js/generalAction.js
Labels: Bug

#2767 Javascript error fixed from modal in Invoice edit modal
  resources/assets/js/components/AkauntingModalAddNew.vue
  resources/views/modals/documents/item_columns.blade.php
Labels: Bug

#2768 Fixed errors
  public/akaunting-js/generalAction.js
Labels: Bug

#2771 Loading component refactored
  resources/views/components/loading/absolute.blade.php
  resources/views/components/loading/content.blade.php
Labels: Bug

#2773 Relationships count warning text updated
  app/Traits/Relationships.php
Labels: Enhancement

#2774 Added style class into the tabs
  public/akaunting-js/generalAction.js
  resources/views/components/layouts/admin/header.blade.php
  resources/views/components/layouts/portal/header.blade.php
  resources/views/components/layouts/preview/header.blade.php
  resources/views/components/layouts/signed/header.blade.php
  resources/views/components/tabs/nav-link.blade.php
  resources/views/components/tabs/nav.blade.php
  resources/views/livewire/menu/favorite.blade.php
Labels: Bug

#2775 Added responsive classname
  public/akaunting-js/generalAction.js
  resources/assets/js/mixins/global.js
  resources/views/components/tabs/index.blade.php
Labels: Code Style

#2776 Code refactoring for animate marquee
  public/akaunting-js/generalAction.js
Labels: Code Style

#2777 Unused styling strokes ejected from Modals
  resources/assets/js/components/AkauntingConnectTransactions.vue
  resources/assets/js/components/AkauntingModal.vue
  resources/assets/js/components/AkauntingModalAddNew.vue
Labels: Bug

#2778 Responsive code refactoring
  public/akaunting-js/generalAction.js
Labels: Bug

#2780 Switch styling for apps show
  public/akaunting-js/generalAction.js
  public/css/app.css
  resources/assets/js/components/AkauntingSearch.vue
  resources/assets/js/views/portal/apps.js
  resources/views/components/layouts/modules/show/buttons.blade.php
  resources/views/components/layouts/modules/show/price.blade.php
  resources/views/components/layouts/modules/show/toggle.blade.php
  resources/views/modules/item/show.blade.php
  safelist.txt
Labels: Enhancement

#2782 Disabled contacts show in contact area
  resources/assets/js/components/AkauntingContactCard.vue
Labels: Bug

#2784 RTL controlled for actions modal
  public/css/app.css
  resources/assets/js/components/AkauntingModal.vue
  resources/assets/js/components/AkauntingModalAddNew.vue
  resources/views/components/table/actions-mobile.blade.php
Labels: Bug
