Repository akaunting/akaunting, pull requests merged in 2023-05, with the labels that each got.

#2963 Added user show page
  app/Http/Controllers/Auth/Users.php
  app/Models/Auth/User.php
  resources/views/auth/users/index.blade.php
  resources/views/auth/users/show.blade.php
Labels: Feature

#2966 added transaction number interface
  app/Http/Controllers/Banking/Transactions.php
  app/Interfaces/Utility/TransactionNumber.php
  app/Providers/Binding.php
  app/Traits/Transactions.php
  app/Utilities/TransactionNumber.php
  database/factories/Transaction.php
Labels: Feature

#2972 transaction duplicate reconliled issue fix
  app/Models/Banking/Transaction.php
Labels: Bug

#2973 Import type improvement
  app/Models/Common/Item.php
  app/Traits/Import.php
Labels: Enhancement

#2977 fix number digit component label
  app/View/Components/Form/Group/NumberDigit.php
  resources/views/settings/invoice/edit.blade.php
Labels: Enhancement

#2974 allow attaching uploaded files when sending mails
  app/Http/Requests/Common/CustomMail.php
  app/Jobs/Document/SendDocumentAsCustomMail.php
  app/Notifications/Sale/Invoice.php
  resources/lang/en-GB/general.php
  resources/views/modals/invoices/email.blade.php
Labels: Feature

#2970 add 'inline' route to allow embedding uploads
  app/Http/Controllers/Common/Uploads.php
  app/Traits/Uploads.php
  routes/admin.php
Labels: Feature
