Repository akaunting/akaunting, pull requests merged in 2023-10, with the labels that each got.

#3046 When importing, the file name is overflowing.
  resources/assets/js/components/AkauntingImport.vue
  resources/views/components/documents/form/line-item.blade.php
Labels: Bug

#3065 fix typo in Form.php
  app/Abstracts/View/Components/Documents/Form.php
Labels: Bug

#3066 If the contact email is empty, save&sent will be disabled.
  app/Http/Controllers/Modals/DocumentTransactions.php
  app/Models/Common/Contact.php
  app/Models/Document/Document.php
  resources/assets/js/components/AkauntingContactCard.vue
  resources/assets/js/components/AkauntingModalAddNew.vue
  resources/assets/js/mixins/global.js
  resources/views/components/documents/form/buttons.blade.php
  resources/views/components/documents/show/send.blade.php
Labels: Enhancement

#3067 Add confidential email (bcc) sending feature
  app/Abstracts/Notification.php
  app/Jobs/Banking/SendTransactionAsCustomMail.php
  app/Jobs/Document/SendDocumentAsCustomMail.php
Labels: Enhancement

#3070 Fixed export filter issue
  app/Utilities/Export.php
Labels: Bug

#3071 Fixed contact person validation issue
  app/Http/Requests/Common/Contact.php
  app/Jobs/Common/CreateContactPersons.php
  resources/views/components/contacts/form/persons.blade.php
Labels: Bug

#3073 Fixed contact person duplicate issue
  app/Models/Common/Contact.php
Labels: Bug

#3072 Filter issue in report printing fixed
  app/Abstracts/Report.php
Labels: Bug

#3077 Typo fixed in Show.php file
  app/Abstracts/View/Components/Contacts/Show.php
Labels: Code Style

#3075 Fixed dashboard bulk action issues
  app/BulkActions/Common/Dashboards.php
  app/Jobs/Common/DeleteDashboard.php
Labels: Bug

#3074 Fixed create document company logo issue
  app/Listeners/Document/SettingFieldCreated.php
  app/Listeners/Document/SettingFieldUpdated.php
Labels: Bug

#3083 Fixed delete button route issue
  app/View/Components/DeleteButton.php
Labels: Bug

#3080 setTimeOut removed while loading
  resources/views/components/loading/absolute.blade.php
  resources/views/components/loading/content.blade.php
  resources/views/components/loading/menu.blade.php
Labels: Enhancement

#3084 Add new events
  app/Events/Common/ContactCreated.php
  app/Events/Common/ContactCreating.php
  app/Events/Common/ContactDeleted.php
  app/Events/Common/ContactDeleting.php
  app/Events/Common/ContactUpdated.php
  app/Events/Common/ContactUpdating.php
  app/Events/Common/ItemCreated.php
  app/Events/Common/ItemCreating.php
  app/Events/Common/ItemDeleted.php
  app/Events/Common/ItemDeleting.php
  app/Events/Common/ItemUpdated.php
  app/Events/Common/ItemUpdating.php
  app/Events/Setting/CurrencyCreated.php
  app/Events/Setting/CurrencyCreating.php
  app/Events/Setting/CurrencyDeleted.php
  app/Events/Setting/CurrencyDeleting.php
  app/Events/Setting/CurrencyUpdated.php
  app/Events/Setting/CurrencyUpdating.php
  app/Events/Setting/TaxCreated.php
  app/Events/Setting/TaxCreating.php
  app/Events/Setting/TaxDeleted.php
  app/Events/Setting/TaxDeleting.php
  app/Events/Setting/TaxUpdated.php
  app/Events/Setting/TaxUpdating.php
  app/Jobs/Common/CreateContact.php
  app/Jobs/Common/CreateItem.php
  app/Jobs/Common/DeleteContact.php
  app/Jobs/Common/DeleteItem.php
  app/Jobs/Common/UpdateContact.php
  app/Jobs/Common/UpdateItem.php
  app/Jobs/Setting/CreateCurrency.php
  app/Jobs/Setting/CreateTax.php
  app/Jobs/Setting/DeleteCurrency.php
  app/Jobs/Setting/DeleteTax.php
  app/Jobs/Setting/UpdateCurrency.php
  app/Jobs/Setting/UpdateTax.php
Labels: Enhancement

#3082 Update README.md
  README.md
Labels: Language Change
