Repository akaunting/akaunting, pull requests merged in 2023-03, with the labels that each got.

#2912 Vue cannot read length issue
  app/Abstracts/Report.php
Labels: Bug

#2913 Added modal component use parent methods and data
  resources/assets/js/components/AkauntingModalAddNew.vue
Labels: Enhancement

#2914 this.errors is undefined issue
  resources/assets/js/plugins/error.js
  resources/assets/js/plugins/form.js
  resources/assets/js/views/common/documents.js
Labels: Bug

#2916 Document share button cursor and payment button styling fixed
  resources/views/components/documents/show/get-paid.blade.php
  resources/views/components/documents/show/make-payment.blade.php
  resources/views/modals/transactions/share.blade.php
Labels: Enhancement

#2918 Category types saved incorrectly in database issue
  app/Listeners/Update/V30/Version3013.php
  app/Providers/Event.php
  app/Traits/Categories.php
Labels: Bug

#2921 Validation issues for import
  app/Abstracts/Import.php
  app/Http/Requests/Banking/Transaction.php
  app/Http/Requests/Common/Item.php
  app/Http/Requests/Document/Document.php
  app/Http/Requests/Setting/Tax.php
  app/Imports/Banking/Transactions.php
  app/Imports/Banking/Transfers.php
  app/Imports/Common/Sheets/ItemTaxes.php
  app/Imports/Common/Sheets/Items.php
  app/Imports/Purchases/Sheets/BillHistories.php
  app/Imports/Purchases/Sheets/BillItemTaxes.php
  app/Imports/Purchases/Sheets/BillItems.php
  app/Imports/Purchases/Sheets/BillTotals.php
  app/Imports/Purchases/Sheets/BillTransactions.php
  app/Imports/Purchases/Sheets/Bills.php
  app/Imports/Purchases/Vendors.php
  app/Imports/Sales/Customers.php
  app/Imports/Sales/Sheets/InvoiceHistories.php
  app/Imports/Sales/Sheets/InvoiceItemTaxes.php
  app/Imports/Sales/Sheets/InvoiceItems.php
  app/Imports/Sales/Sheets/InvoiceTotals.php
  app/Imports/Sales/Sheets/InvoiceTransactions.php
  app/Imports/Sales/Sheets/Invoices.php
  app/Imports/Settings/Categories.php
  app/Imports/Settings/Taxes.php
  app/Traits/Import.php
  app/Utilities/Import.php
Labels: Enhancement

#2919 Added item_type column to the document's export file
  app/Exports/Purchases/Sheets/BillItems.php
  app/Exports/Sales/Sheets/InvoiceItems.php
Labels: Enhancement

#2920 Log import errors
  app/Utilities/Import.php
Labels: Enhancement

#2924 Fix search string value issue
  app/View/Components/SearchString.php
Labels: Enhancement

#2925 Update example excel files
  public/files/import/bills.xlsx
  public/files/import/invoices.xlsx
Labels: Enhancement

#2926 Input hides long tax text in new bill page bug
  resources/views/components/documents/form/line-item.blade.php
Labels: Bug

#2929 Updates trait, migration option
  app/Traits/Updates.php
Labels: Enhancement

#2933 fix akunting pwa icon missing
  resources/views/components/layouts/pwa/head.blade.php
  serviceworker.js
Labels: Bug

#2932 Fix always fallback invoice item column settings
  app/Abstracts/View/Components/Documents/Form.php
Labels: Bug

#2931 Fixed translation strings in item column settings
  app/Http/Controllers/Modals/DocumentItemColumns.php
Labels: Bug

#2930 Toggles is not align in the settings invoice page
  resources/views/settings/invoice/edit.blade.php
Labels: Bug

#2935 using laravel default cors package
  app/Http/Kernel.php
  composer.json
  composer.lock
Labels: Code Style

#2942 New Recurring Invoice page validation position changed right to bottom
  resources/assets/js/components/AkauntingRecurring.vue
  resources/views/components/button/hover.blade.php
  resources/views/components/link/hover.blade.php
Labels: Bug

#2943 Progress bar text color changed
  public/css/element.css
Labels: Bug

#2944 Apps text in footer not appear
  resources/views/components/layouts/admin/footer.blade.php
  resources/views/components/layouts/portal/footer.blade.php
  resources/views/components/layouts/preview/footer.blade.php
  resources/views/components/layouts/signed/footer.blade.php
Labels: Bug

#2947 Search string translate filter name
  app/View/Components/SearchString.php
Labels: Bug

#2951 Sizing style issue on contact page
  resources/views/components/contacts/form/general.blade.php
Labels: Bug

#2950 Updated bill sample export file
  public/files/import/bills.xlsx
Labels: Bug

#2952 Sizing style issue on document page
  resources/views/components/documents/form/company.blade.php
Labels: Bug

#2954 Tabs component ignore hash option
  resources/views/components/tabs/index.blade.php
Labels: Enhancement

#2955 Added placeholder akaunting date
  resources/assets/js/components/AkauntingDate.vue
Labels: Enhancement
