Repository akaunting/akaunting, pull requests merged in 2023-08, with the labels that each got.

#3014 Added hover animation to apps and Wizard steps aligned
  resources/assets/js/views/wizard/Finish.vue
  resources/assets/js/views/wizard/Steps.vue
Labels: Enhancement

#3015 Wizard spacing control
  resources/assets/js/views/wizard/Finish.vue
  resources/views/components/documents/show/send.blade.php
Labels: Enhancement

#3016 Loading animation added to button.
  resources/views/components/index/bulkaction/index.blade.php
Labels: Bug

#3020 Fixed mobile delete action issue
  resources/views/components/table/actions-mobile.blade.php
Labels: Bug

#3019 Issue with headers pushing descriptions
  public/css/print.css
  resources/views/components/layouts/admin/menu.blade.php
  resources/views/components/layouts/portal/menu.blade.php
Labels: Bug

#3021 Apps content is overflowing
  resources/views/components/layouts/modules/bar.blade.php
Labels: Bug

#3022 Fixed import tax unique type issue
  app/Imports/Settings/Taxes.php
Labels: Bug

#3023 Added dashboards relationship to UserDashboard model
  app/Models/Auth/UserDashboard.php
Labels: Enhancement

#2877 Bind title and subheading to the respective document
  app/Abstracts/View/Components/Documents/Form.php
  app/Abstracts/View/Components/Documents/Show.php
  app/Abstracts/View/Components/Documents/Template.php
  app/Models/Document/Document.php
  database/migrations/2023_01_19_153034_add_title_subheading_to_documents.php
  resources/views/components/documents/form/company.blade.php
  resources/views/components/documents/form/metadata.blade.php
Labels: Feature

#3025 Currency code is duplicated when an existing currency code is selected in the sorted list
  resources/assets/js/components/AkauntingSelect.vue
Labels: Bug

#3027 Add import has row data check
  app/Abstracts/Import.php
  app/Imports/Banking/Transactions.php
Labels: Enhancement

#3028 When the "Download PDF" is clicked on the invoice page, the total is not aligned with the note.
  public/css/print.css
  resources/views/components/documents/template/classic.blade.php
  resources/views/components/documents/template/default.blade.php
  resources/views/components/documents/template/modern.blade.php
Labels: Bug

#3029 RTL issues solved
  resources/assets/js/components/AkauntingColor.vue
  resources/assets/js/views/wizard/Currencies.vue
  resources/views/components/contacts/index/content.blade.php
  resources/views/components/documents/form/totals.blade.php
  resources/views/widgets/receivables_payables.blade.php
  safelist.txt
Labels: Bug

#3030 Error message pushing Quantity input
  resources/views/components/documents/form/line-item.blade.php
Labels: Bug

#3031 Added transaction delete events
  app/Events/Banking/TransactionDeleted.php
  app/Events/Banking/TransactionDeleting.php
  app/Jobs/Banking/DeleteTransaction.php
Labels: Enhancement

#3032 Added account events
  app/Events/Banking/AccountCreated.php
  app/Events/Banking/AccountCreating.php
  app/Events/Banking/AccountDeleted.php
  app/Events/Banking/AccountDeleting.php
  app/Events/Banking/AccountUpdated.php
  app/Events/Banking/AccountUpdating.php
  app/Jobs/Banking/CreateAccount.php
  app/Jobs/Banking/DeleteAccount.php
  app/Jobs/Banking/UpdateAccount.php
Labels: Enhancement

#3033 Delete button is not where it should be in RTL
  resources/views/components/layouts/admin/menu.blade.php
  resources/views/components/layouts/portal/menu.blade.php
Labels: Bug

#3035 Loading color fixed
  resources/assets/js/views/wizard/Finish.vue
Labels: Bug

#3036 Added relationship to module history model
  app/Models/Module/ModuleHistory.php
Labels: Enhancement

#3038 Progress bar is not visible and scroll is showing problem solved
  resources/assets/js/bootstrap.js
  resources/views/components/layouts/auth.blade.php
  resources/views/components/layouts/install.blade.php
Labels: Bug

#3039 Texts are nested in invoice
  public/css/print.css
Labels: Bug

#3040 Recurring-invoice page schedule align problem solved
  resources/assets/js/components/AkauntingRecurring.vue
Labels: Bug

#3041 Error text does not disappear when option changes
  resources/assets/js/components/AkauntingRecurring.vue
  resources/views/components/documents/form/line-item.blade.php
Labels: Bug
