Repository akaunting/akaunting, pull requests merged in 2023-07, with the labels that each got.

#2996 Add description when fetch document item
  app/Http/Resources/Document/DocumentItem.php
Labels: Enhancement

#2997 Wizard Finish style changed
  resources/assets/js/components/NotificationPlugin/Notification.vue
  resources/assets/js/views/wizard/Finish.vue
  resources/assets/js/views/wizard/Steps.vue
Labels: Enhancement

#2998 Description is overflowing in App modal
  resources/views/components/layouts/modules/bar.blade.php
Labels: Bug

#3000 Left menu chevron not rotating
  resources/views/components/layouts/admin/scripts.blade.php
  resources/views/components/layouts/portal/scripts.blade.php
Labels: Bug

#3001 Alpine.js Upgrade from 2.8.2 to 3.13.3
  public/vendor/alpinejs/alpine.min.js
Labels: Enhancement

#3004 Scroll added when items are too many
  resources/assets/js/components/AkauntingItemButton.vue
Labels: Enhancement

#3005 Added extra time to open tooltip
  resources/views/components/documents/index/information.blade.php
Labels: Enhancement

#3007 Import transaction type issue fixed
  app/Imports/Banking/Transactions.php
Labels: Bug

#3011 Import page re-design
  app/Http/Controllers/Common/Import.php
  app/View/Components/Form/Group/Import.php
  app/View/Components/Form/Input/Import.php
  public/css/app.css
  public/css/third_party/dropzone_custom.css
  public/img/import.png
  resources/assets/js/components/AkauntingImport.vue
  resources/assets/js/mixins/global.js
  resources/lang/en-GB/import.php
  resources/views/common/import/create.blade.php
  resources/views/components/form/group/import.blade.php
  resources/views/components/form/input/import.blade.php
Labels: Enhancement, Language Change
