Repository akaunting/akaunting, pull requests merged in 2023-01, with the labels that each got.

#2857 Document show contact link
  app/Abstracts/View/Components/Documents/Template.php
  resources/views/components/documents/template/classic.blade.php
  resources/views/components/documents/template/default.blade.php
  resources/views/components/documents/template/modern.blade.php
Labels: Enhancement

#2865 Fix sample data
  database/factories/Document.php
  database/factories/Transaction.php
Labels: Code Style

#2869 Typo issue
  resources/views/components/transactions/template/default.blade.php
Labels: Bug

#2870 Portal profile address finder compability
  resources/views/portal/profile/edit.blade.php
Labels: Enhancement

#2875 RTL for Tips: Align text to left and revert image
  public/css/app.css
  resources/views/components/tips/fixed.blade.php
  resources/views/components/tips/relative.blade.php
  safelist.txt
Labels: Enhancement

#2872 document: hide edit button in accordion if missing update permission
  resources/views/components/documents/show/create.blade.php
Labels: Enhancement
