Repository akaunting/akaunting, pull requests merged in 2024-07, with the labels that each got.

#3178 Fixed bulk actions edit transaction issue
  app/BulkActions/Banking/Transactions.php
Labels: Bug

#3177 Added bulk action download
  app/Abstracts/BulkAction.php
  app/BulkActions/Sales/Invoices.php
  app/Http/Controllers/Sales/Invoices.php
  app/Jobs/Common/CreateMediableForDownload.php
  app/Jobs/Common/CreateZipForDownload.php
  app/Jobs/Document/DownloadDocument.php
  app/Notifications/Common/DownloadCompleted.php
  app/Notifications/Common/DownloadFailed.php
  resources/lang/en-GB/bulk_actions.php
  resources/lang/en-GB/messages.php
  resources/lang/en-GB/notifications.php
  resources/views/components/layouts/print/scripts.blade.php
Labels: Enhancement

#3179 Fixed default settings validation
  app/Http/Requests/Setting/Setting.php
  resources/views/settings/default/edit.blade.php
Labels: Enhancement

#3181 Fixed document show style issues
  resources/views/components/documents/template/classic.blade.php
  resources/views/components/documents/template/default.blade.php
  resources/views/components/documents/template/modern.blade.php
Labels: Bug

#3180 Added new currency
  config/money.php
Labels: Enhancement

#3182 Fix split transaction duplicate issue
  app/Jobs/Banking/SplitTransaction.php
  app/Models/Banking/Transaction.php
  app/Utilities/TransactionNumber.php
Labels: Bug

#3183 In Safari browser, the password shortcut appears above the password show/hide icon
  resources/views/components/form/input/password.blade.php
Labels: Bug

#3186 Added address format
  app/Http/Requests/Setting/Setting.php
  app/Models/Common/Company.php
  app/Models/Common/Contact.php
  app/Models/Document/Document.php
  app/Traits/Contacts.php
  config/setting.php
  resources/lang/en-GB/settings.php
  resources/views/components/contacts/show/content.blade.php
  resources/views/settings/default/edit.blade.php
Labels: Enhancement

#3174 Add Valet driver
  LocalValetDriver.php
Labels: Feature

#3189 Change // to html comment on print layout
  resources/views/components/layouts/print/scripts.blade.php
Labels: Bug
