Repository akaunting/akaunting, pull requests merged in 2024-04, with the labels that each got.

#3151 Fixed export multisheets filter issue
  app/Utilities/Export.php
Labels: Bug

#3153 Add export validation warning message
  app/Abstracts/Export.php
  app/Exports/Banking/Transactions.php
  app/Exports/Banking/Transfers.php
  app/Exports/Common/Sheets/ItemTaxes.php
  app/Exports/Common/Sheets/Items.php
  app/Exports/Settings/Categories.php
  app/Exports/Settings/Taxes.php
  config/excel.php
  resources/lang/en-GB/general.php
  resources/lang/en-GB/validation.php
Labels: Feature, Language Change

#3154 Password Hide/Show added
  resources/views/components/form/input/password.blade.php
  resources/views/components/layouts/auth/head.blade.php
  resources/views/components/layouts/auth/scripts.blade.php
Labels: Enhancement

#3155 Password Hide/Show fixed
  resources/views/components/form/input/password.blade.php
Labels: Bug

#3156 Fixed sub category delete issues
  app/Jobs/Setting/DeleteCategory.php
Labels: Bug

#3149 Fix request validation errors
  app/Http/Requests/Auth/User.php
  app/Http/Requests/Banking/Transaction.php
  app/Http/Requests/Document/Document.php
  app/Http/Requests/Setting/Currency.php
  app/Http/Requests/Setting/Tax.php
Labels: Enhancement
