Repository akaunting/akaunting, pull requests merged in 2024-09, with the labels that each got.

#3211 RTL issues fixed
  resources/assets/js/components/AkauntingCompanyEdit.vue
  resources/assets/js/components/AkauntingContactCard.vue
  resources/views/auth/users/index.blade.php
Labels: Enhancement

#3213 Online Payments page style fixed
  resources/views/components/layouts/admin.blade.php
  safelist.txt
Labels: Enhancement

#3216 Fixed report filter period issue
  app/Abstracts/Listeners/Report.php
Labels: Bug

#3217 The issue of displaying long months in the date filter has been resol…
  app/Traits/DateTime.php
Labels: Bug

#3219 Tab feature style fixed
  resources/assets/js/components/NotificationPlugin/Notification.vue
  resources/views/components/tabs/nav-link.blade.php
  resources/views/components/tabs/nav.blade.php
  resources/views/livewire/tab/pin.blade.php
Labels: Enhancement

#3220 Multi-dashboard feature without slide animation
  resources/views/common/dashboards/show.blade.php
Labels: Feature
